app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss
app/views/govuk_component/docs/taxonomy_sidebar.yml

We will be iterating both components as part of a multivariate test. This commit avoids a more thorough refactor to make them identical, in favour of making them alike. It’s an alternative to #1177.
* Port related links styles directly from related links component
* Makes two components similar
* Increases spacing around links for easier clicking on mobile
* Adds more examples
This PR does not address:
* Need to use `pub-c` as the prefix
* Inconsistent API between related links and taxonomy sidebar
* Style re-use between components
https://govuk-static-pr-1185.herokuapp.com/component-guide/taxonomy_sidebar
Part of:
https://trello.com/c/FN3ppmn2/60-update-taxonomy-related-links-in-right-column-to-match-the-design-used-by-mainstream-browse-related-links
Old on left, new on right

Style taxonomy sidebar like related links

---

app/views/root/_base.html.erb

Existing footer link to Worldwide goes through a redirect to the destination, this pr links directly to it instead.

Change footer link to point directly at destination page

---

app/assets/javascripts/surveys.js

Along with the extension we did in #1189, HMRC would also like to try
changing the banner text on the survey to encourage more responses.

Change banner text for HMRC child benefit and tax payments surveys

---

app/assets/javascripts/modules/cross-domain-tracking.js
app/assets/javascripts/start-modules.js
spec/javascripts/modules/cross-domain-tracking.spec.js

This allows a generic method of cross domain tracking for links on GOV.UK.
This will be useful for when our govspeak extension is used in content,
where only content designers can author what goes into the body of the page.
Here we're using native DOM methods rather than jQuery fragments because, for
whatever reason jQuery produces a fragment that does not allow inspection of hostname.
(I think this is because we can't inject a fragment into a real dom)
So rather than add additional overhead to the users' javascript, the tests are a little more verbose.
Will also allow us to replace https://github.com/alphagov/frontend/blob/master/app/views/transaction/_cross_domain_analytics.html.erb
Trello: https://trello.com/c/ppqXaGPk/122-create-a-govspeak-component-for-buttons

Add global cross domain tracking

---

app/views/govuk_component/task_list_header.raw.html.erb
test/govuk_component/task_list_header_test.rb

- add GA tracking to both main link and skip link
- records: EventCategory = ‘tasklistHeaderClicked’, Action = 'top', eventlabel = [link url], dimension29 = [link text]
- as detailed in 'Sticky navigation' section of https://docs.google.com/document/d/1bvUR4i8aARl-gPGHt3dzDoPFU3RZNgM7he3zB3ua2Gk/
Both links shown below:
Trello: https://trello.com/c/d6B6hRhh/292-restore-tracking-on-task-list-header-%F0%9F%9A%97

Add click tracking to task list header links

---

app/assets/javascripts/govuk-component/tasklist.js
spec/javascripts/govuk-component/task-list-spec.js

- add task list size ('Big' or 'Small') to Open all / Close all clicks eventLabel
- do the same for panel links i.e. links in lists in the accordion-like bits of the task list
Trello: https://trello.com/c/pLUMn48c/260-check-the-all-data-is-rolling-in-from-the-learning-to-drive-a-car-beta-%F0%9F%9A%97

Update task list tracking

---

app/views/govuk_component/docs/alpha_label.yml
app/views/govuk_component/docs/analytics_meta_tags.yml
app/views/govuk_component/docs/beta_label.yml
app/views/govuk_component/docs/breadcrumbs.yml
app/views/govuk_component/docs/button.yml
app/views/govuk_component/docs/document_footer.yml
app/views/govuk_component/docs/government_navigation.yml
app/views/govuk_component/docs/govspeak.yml
app/views/govuk_component/docs/govspeak_html_publication.yml
app/views/govuk_component/docs/metadata.yml
app/views/govuk_component/docs/option_select.yml
app/views/govuk_component/docs/organisation_logo.yml
app/views/govuk_component/docs/previous_and_next_navigation.yml
app/views/govuk_component/docs/related_items.yml
app/views/govuk_component/docs/search.yml
app/views/govuk_component/docs/taxonomy_sidebar.yml

Updating some of the static components with accessibility criteria.
I haven't touched the following so they're still displaying the 'no accessibility criteria' warning. If anyone has any ideas, let me know...
- [Government Navigation](https://govuk-static.herokuapp.com/component-guide/government_navigation)
- [Govspeak Content](https://govuk-static.herokuapp.com/component-guide/govspeak)
- [Govspeak Content HTML Publications](https://govuk-static.herokuapp.com/component-guide/govspeak_html_publication)
Component Guide PR Link: https://govuk-static-pr-1198.herokuapp.com/component-guide

Add accessibility acceptance criteria

---

app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss
app/views/govuk_component/docs/taxonomy_sidebar.yml
app/views/govuk_component/taxonomy_sidebar.raw.html.erb
config/locales/en.yml
test/govuk_component/taxonomy_sidebar_test.rb

We are developing a [new navigation sidebar component](https://github.com/alphagov/government-frontend/pull/542) in government-frontend. We need to bring the taxonomy sidebar component design in line with the new related links. Ideally we'd be updating this component to follow our [component conventions](https://github.com/alphagov/govuk_publishing_components/blob/master/docs/component_conventions.md), e.g: using BEM, but this is probably a bigger piece of work, especially with the caching issues we've had previously when updating static components.
Component Guide: https://govuk-static-pr-1200.herokuapp.com/component-guide/taxonomy_sidebar
**Note: this change will affect the taxonomy sidebar across all applications (not just government-frontend). Example pages to tests are:**
- [Detailed …

Update design of taxonomy sidebar

---

app/assets/javascripts/surveys.js

For:
https://trello.com/c/VHI37aMw/307-govuk-survey-hmrc-pensions
https://trello.com/c/qaGtU6va/308-govuk-survey-hmrc-company-car
Both surveys will have a 1-in-6 frequency on the `/tax-on-your-private-pension` path, and the `/update-company-car-details` path respectively.
- The private pensions survey will run for 3 months, until February 28, 2018.
- The  company car survey will run for 6 weeks, until January 11, 2018

Add HMRC Pensions and Car Tax surveys

---

Gemfile
Gemfile.lock
app/assets/stylesheets/govuk-component/_button.scss
app/views/govuk_component/button.raw.html.erb
app/views/govuk_component/docs/button.yml
app/views/govuk_component/docs/document_footer.yml
app/views/govuk_component/docs/government_navigation.yml
app/views/govuk_component/docs/option_select.yml
test/govuk_component/button_test.rb

By default buttons should have no margin bottom,
but sometimes it's useful to break up a page, for example if a button is at the bottom of a page.

Add margin bottom support to buttons

---

app/assets/stylesheets/govuk-component/_component.scss
app/assets/stylesheets/govuk-component/_task-list-related.scss
app/views/govuk_component/docs/task_list_related.yml
app/views/govuk_component/task_list_related.raw.html.erb
config/locales/en.yml
test/govuk_component/task_list_related_test.rb

Designed to go above (and below) a small task list in the sidebar, to provide a link back to the main task list. Secondary purpose is underneath the same task list, to show links to other task lists this page might be a part of.
In context:
- [Component guide page](https://govuk-static-pr-1209.herokuapp.com/component-guide/task_list_related)
- [Trello card](https://trello.com/c/T6XscwyL/386-create-task-list-sidebar-part-of-links-component)

Create task list related links component

---

app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss
app/views/govuk_component/docs/taxonomy_sidebar.yml
app/views/govuk_component/taxonomy_sidebar.raw.html.erb
config/locales/en.yml
test/govuk_component/taxonomy_sidebar_test.rb

https://trello.com/c/zzot5dZq/157-taxonomy-sidebar-add-link-to-collections
https://trello.com/c/NtD5rC4S/121-taxonomy-sidebar
This combines the changes from https://github.com/alphagov/static/pull/1200 to make the taxonomy sidebar styles similar to the related-navigation component and also the feature of rendering collections links below the taxon links.

Update taxonomy sidebar design

---

app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss

Static template code can sit in the application caches long enough
for the wrong combination of CSS and template code to render on page.
This leads to a broken looking component. So add the old styles to support
the deployment of the recent update to the taxonomy sidebar.
These styles can be removed once the applications are up to date.
Old styles taken from: https://github.com/alphagov/static/blob/dda614f2037f75951536af2a10672d1cc4aed1c6/app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss
cc @nickcolley @vanitabarrett

Re-add old taxonomy styles for better deployment support

---

app/assets/javascripts/surveys.js

It's been requested that we remove the "Treejack" survey earlier than the expiration date.

Remove survey earlier than expiration date

---

doc/surveys.md

Adds a JS template in the docs for both URL surveys and Email surveys. This will make it much easier to define these surveys without having to dig through commits for an example.
For: https://trello.com/c/NGbngoqS/23-update-docs-for-surveys

Updates survey docs

---

app/assets/javascripts/surveys.js

For: 
- https://trello.com/c/9ASPCGG7/8-1-post-test-sign-up-survey
- https://trello.com/c/AhwNPAqS/7-1-pre-study-sign-up
The first survey is a URL survey and will run between 17-18 Jan 2018. 
The second survey is an email survey and will run between 22-23 Jan 2018.
Depends on: https://github.com/alphagov/feedback/pull/298

Adds new treejack surveys

---

Dockerfile

We use the docker image as part of the publishing end to end tests.
We also run the publishing-e2e-tests in Rails production mode, so
want to pre-compile the assets in the same way that production will.

Compile assets into the Docker image

---

app/assets/javascripts/surveys.js

https://trello.com/c/jh8HyMZB/120-launch-a-survey-for-tree-testing
The original requirements for this survey was that it should appear on
/browse/visa-immigration and 2641 other unique paths. However, it was
unfeasible to include this list of paths in the survey.js file, which
would considerably increase the size of the file (from ~32kB to 296kB).
As an alternative approach, we have chosen a subset of organisations and
a handful of paths that receive a high volume of pageviews but would not
be covered by the organisations, for this survey to active on.
---
Deployed to integration:
with the link as `https://gdsuserresearch.optimalworkshop.com/treejack/82p1e0a6-0-0-1-0-0?c=/browse/visas-immigration&gcl=1059145684.1518009280`

Add CTTUK tree test survey

---

app/assets/javascripts/surveys.js

We are still falling short of survey completions, so in our last attempt
to reach our target we have incresed the frequency of this survey to
1-in-1 and for it to run until the end of Wednesday.

Increase frequency and extend by 1 day the CTTUK-Professionals survey

---

app/views/govuk_component/button.raw.html.erb
app/views/govuk_component/docs/button.yml
test/govuk_component/button_test.rb

Part of https://trello.com/c/3VwTvDrj/256-use-button-component-in-frontend-formats
Updates the button component to accept `extra_attrs`, primarily to support data attributes for tracking eg. https://github.com/alphagov/frontend/blob/master/app/views/transaction/show.html.erb#L22
This should allow us to use the component for Frontend app buttons.
I've refactored this to use Rails `link_to` and `button_tag` helpers as it seemed less noisy.

Add tracking attributes to button component

---

app/assets/javascripts/surveys.js

For https://trello.com/c/UDElK9LD/278-put-all-user-supergroup-subgroup-study-live-on-govuk
The Navigation team is running a "Supergroup/Subgroup study" survey from 20th
February to 23rd February at a 1 in 6 frequency.

Add Supergroup Subgroup study survey

---

app/assets/javascripts/browser-check.js

To encourage people using browsers that don't support TLS1.2, we're going to start showing the upgrade banner in those cases. For now we'll use the same generic messaging until we've got something better / more specific.
Also pings a new browser-check/prompt-shown-tls GA event to allow us to see how many people we're showing this to who wouldn't have seen it otherwise.

Show the browser-upgrade banner for old TLS versions

---

Dockerfile
Procfile
app.json
config/environments/production.rb

Wider context: https://github.com/alphagov/publishing-e2e-tests/pull/202
This PR adds foreman as a gem dependency of docker (as per [foreman instructions](https://github.com/ddollar/foreman#installation)) as the means to run the processes for this app.
It also changes the Procfile configuration to allow this app to be run using it outside of a heroku context.

Foreman dockerfile

---

app/assets/javascripts/surveys.js

Initially this was one month, but it's actually going to last for 3 months, between Feb 14 to May 14 2018.
For: https://trello.com/c/Wz9ppQon/72-1-govuk-survey-hmrc-expires-march-16-2018

Extends the duration for HMRC surveys

---

app/assets/javascripts/surveys.js

The HMRC pensions survey has now expired so we should remove it.
We're also removing all the other expired surveys as part of this PR.
For:  https://trello.com/c/VHI37aMw/77-govuk-survey-hmrc-pensions-ending-28-feb-2018

Removes expired surveys

---

app/assets/stylesheets/govuk-component/_lead-paragraph.scss
app/views/govuk_component/docs/lead_paragraph.yml
app/views/govuk_component/lead_paragraph.raw.html.erb

We need to be able to display the lead paragraph component as white text on a blue background for the new taxonomy topic page designs.
[Component Guide link](https://govuk-static-pr-1318.herokuapp.com/component-guide/lead_paragraph)

Add inverse flag to lead paragraph component

---

doc/surveys.md

When talking about the survey in #1283 the original version contained ~3000
path comparisons.  We realised that this could be problematic for browsers
because we'd have to run all those regex comparisons on every request while
the survey was running.  We haven't done any benchmarking so it's not clear
when we need to worry about performance and what we can get away with, but
in general it makes sense to keep the number of comparisons low on a survey
if possible so we've added some notes about this to the documentation.

Add performance considerations to surveys documentation

---

app/assets/stylesheets/govuk-component/_breadcrumbs.scss
app/views/govuk_component/breadcrumbs.raw.html.erb
app/views/govuk_component/docs/breadcrumbs.yml
test/govuk_component/breadcrumbs_test.rb

This allows breadcrumbs to be rendered in white so they can be used on blue backgrounds in Topic pages. 
Component guide: https://govuk-static-pr-1322.herokuapp.com/component-guide/breadcrumbs

Add inverse flag to breadcrumbs component

---

app/assets/javascripts/surveys.js

https://trello.com/c/ueb80h78/305-put-two-govuk-banners-live-for-studies
* Remove navigation links survey for education and childcare taxonomy pages
* Add 2 content page design surveys which run for 1 in 3 users until the end of the month

Add content page design surveys

---

app/assets/javascripts/surveys.js

There are two GOV.UK Content Pages Design surveys that are currently
planned to show across the whole of GOV.UK until the end of March.
However, since releasing the CTTUK v10 survey, these three surveys will
potentially conflict with one another, especially given the frequency
and similarity of banner details.
After confirming with the user researchers on the Taxonomy team (Ariana)
and the Content Pages team (Imeh), we have decided to pause the two
Content Pages surveys until they require participants again.

Resolve conflicting surveys

---

Gemfile.lock
app/assets/javascripts/analytics/custom-dimensions.js
app/views/govuk_component/analytics_meta_tags.raw.html.erb

A page can be part of none, one or multiple step by step navigations.
The GA custom dimension 96 should include all step navs the current page is part of in order to be able to differentiate specific step nav elements which might appear in more than one step nav.
[Trello card](https://trello.com/c/QCdTZ8cg)

Add stepnavs to GA custom dimension 96

---

app/assets/javascripts/surveys.js

For: https://govuk.zendesk.com/agent/tickets/2616586
Trello: https://trello.com/c/K3RWmmXH/139-1-hmrc-banners
A. Adds three new HMRC surveys that start in March
1. Duty free survey
- paths:
```
'^/duty-free-goods/arrivals-from-outside-the-eu$',
'^/duty-free-goods/arrivals-from-eu-countries$'
```
- url: ```'https://signup.take-part-in-research.service.gov.uk/?utm_campaign=Passengers&utm_source=Other&utm_medium=gov.uk&t=HMRC&id=139'```
1. International post survey:
- path
```
'^/government/publications/notice-143-a-guide-for-international-post-users$'
```
- url: ```'https://signup.take-part-in-research.service.gov.uk/?utm_campaign=Parcels&utm_source=Other&utm_medium=gov.uk&t=HMRC&id=140'```
1. Overseas VAT survey
- path:
```
'^/guidance/vat-overseas-businesses-using-an-online-marketplace-to- …
```

Adds March HMRC surveys

---

app/views/govuk_component/previous_and_next_navigation.raw.html.erb

Uses the standard tracking module.
Can be tested here: https://govuk-static-pr-1359.herokuapp.com/component-guide/previous_and_next_navigation
Trello card: https://trello.com/c/y3aYUbL1/519-add-previous-next-tracking-to-mainstream-guide-content-click-events

Add tracking module to next/prev component

---

app/assets/javascripts/analytics/init.js.erb

Background:
> When the planforbritain website went live we implemented full dual tracking on both sites so that each site had visibility of complete use journeys across both sites.
> 
> At some point (not sure when) the planforbritain site was taken off line.
> I imagine that around the same time the extra tracking on GOV.UK was removed so that the page view and event hits were no longer duplicated to the planforbritain GA property.
But it looks as if the code to do the autolinking was left in place. We should tidy up by removing that as well.

Remove autolinker for planforbritain.gov.uk

---

app/views/govuk_component/analytics_meta_tags.raw.html.erb

This metatag is read by the google analytics here:
https://github.com/alphagov/static/blob/master/app/assets/javascripts/analytics/custom-dimensions.js
For more information see
https://govuk-static.herokuapp.com/component-guide/analytics_meta_tags
I noticed this was missing because certain formats (transaction, simple smart answer) don't include this tag. Before merging, I need to check other rendering apps besides frontend, because it seems that in some places we manually add this meta tag to the template and I don't want to duplicate it.

Add content ID to analytics component

---

app/assets/javascripts/analytics/init.js.erb
config/application.rb
config/environments/production.rb

If the env var `GA_UNIVERSAL_ID` is set, that is used for the Google Analytics ID.  If it's not set, the ID defaults to `UA-26179049-1` in production, and `UA-UNSET` in development and test.
---
This will let us use a different Google Analytics ID in staging and integration: https://trello.com/c/uLUgPcvI/50-stop-sending-staging-and-integration-data-to-same-ga-property-as-live-site-2

Add an optional environment variable for the Google Analytics ID

---

Gemfile
Gemfile.lock

Reverts alphagov/static#1381
We've spotted a bug with version 0.23.1 of govuk_template - reverting this update for now to prevent it being released if static is deployed to prod.

Revert "Bump govuk_template from 0.23.0 to 0.23.1"

---

Gemfile
Gemfile.lock

We previously had to revert the bump to 0.23.1 as it contained a breaking change (https://github.com/alphagov/static/pull/1382)
This has now been fixed, so we can update straight from 0.23.0 to 0.23.2

Bump govuk_template to 0.23.2

---

app/assets/stylesheets/govuk-component/_button.scss
app/assets/stylesheets/govuk-component/_component.scss
app/assets/stylesheets/govuk-component/govspeak/_button.scss
app/views/govuk_component/button.raw.html.erb
app/views/govuk_component/docs/button.yml
test/govuk_component/button_test.rb

The button is still used in email-alert-frontend (https://sentry.io/govuk/app-email-alert-frontend/issues/541825168/?query=is:unresolved).
Reverts alphagov/static#1384

Revert "Remove button component"

---

app/views/govuk_component/docs/organisation_logo.yml
app/views/govuk_component/organisation_logo.raw.html.erb
app/views/govuk_component/organisation_logo_section.raw.html.erb
test/govuk_component/organisation_logo_test.rb

Trello: https://trello.com/c/xYWhPOMg
* Split the organisation image into a separate partial template to allow us to use it as part of a link or by itself.
* Added `data-module=track-click` when `data_attributes` are passed in so that no further configuration is required in views to get the tracking to work.

Add tracking to organisation logos

---

app/assets/javascripts/surveys.js

Removed HMRC surveys which expired recently.
There was another one not in the ticket which also expired, so I removed that too.
https://trello.com/c/Wz9ppQon/43-1-february-hmrc-surveys-expire-may-14-2018
Tested to make sure the remaining surveys still work:

Remove HMRC surveys for February

---

app/assets/javascripts/surveys.js

We're now using the breadcrumbs component everywhere, which is a different class name.
https://govuk-publishing-components.herokuapp.com/component-guide/breadcrumbs
Supersedes https://github.com/alphagov/static/pull/1412.
https://trello.com/c/XLuzv0pB

Fix feature to scope surveys by breadcrumb

---

app/views/govuk_component/previous_and_next_navigation.raw.html.erb
test/govuk_component/previous_and_next_navigation_test.rb

This will encourage search engines to index the first page of a paginated set of pages meaning users should always end up at the first page.
[Trello Card](https://trello.com/c/PHjO8hP2/139-noindex-pagination-from-external-search-2)

Add a meta noindex tag to any page which isn't first

---

app/views/govuk_component/docs/alpha_label.yml
app/views/govuk_component/docs/beta_label.yml
app/views/govuk_component/docs/government_navigation.yml
app/views/govuk_component/docs/govspeak.yml
app/views/govuk_component/docs/govspeak_html_publication.yml
app/views/govuk_component/docs/lead_paragraph.yml
app/views/govuk_component/docs/previous_and_next_navigation.yml
app/views/govuk_component/docs/title.yml

We've moved these components to the gem so temporarily their used from both places. This warning intends to prevent confusion.
https://trello.com/c/pU7YINt1

Mark moved components as deprecated in docs

---

app/views/govuk_component/previous_and_next_navigation.raw.html.erb
test/govuk_component/previous_and_next_navigation_test.rb

This reverts commit 6dbf470a23e3bc6052f3cb1dc3704d030633055d.
Some pages use this component to move between different parts and we don't want to noindex those pages. In particular this is the case for mainstream and travel advice.

Revert "Add a meta noindex tag to any page which isn't first"

---

Gemfile
Gemfile.lock

This commit updates the version of `govuk_template` to pull a change to the crown copyright URL in the template footer.

Update govuk_template gem

---

Gemfile
Gemfile.lock
spec/javascripts/analytics/static-analytics-spec.js

This commit upgrades `govuk_frontend_toolkit` to 7.6.0 and makes a consequent change to the analytics test.
Trello: https://trello.com/c/jKitCyZI/311-remove-emails-from-ga-events-on-email-alert-frontend-pages-reprise

Upgrade govuk_frontend_toolkit

---

app/assets/javascripts/analytics/custom-dimensions.js

There is a GA custom dimension called "rendering-application" so it makes sense
to call this metatag "publishing-application", as suggested by @thomasleese 
https://trello.com/c/vhfMGngX/239-investigate-and-correct-smart-answer-google-analytics-tracking

Rename publishing-app custom dimension

---

app/assets/javascripts/surveys.js

This PR introduces a new survey that will be displayed:
- on all `environment` sections
- to one every six users
- not on mobile
The actual url to the survey needs to be added (it's not ready yet).

Add environment tree test survey

---

app/assets/javascripts/surveys.js

This PR increases the frequency of the appearance of the environment survey banner to 1 every 2. This is to get enough data in the time span set.

Increase environment survey frequency

---

app/views/root/_base.html.erb

This is because `Policies` are soon to be retired and so the navigation
to the polcies finder needs to be removed.
Trello:
https://trello.com/c/WyjKeXS4/210-remove-policies-link-from-grey-govuk-footer

Remove the link to `/government/policies` from the shared footer

---

Gemfile
Gemfile.lock
app/assets/javascripts/analytics/static-analytics.js

Enables cross domain event tracking features.

Update govuk frontend toolkit to 8.1.0

---

app/assets/javascripts/modules/cross-domain-tracking.js
spec/javascripts/modules/cross-domain-tracking.spec.js

Utilise the additional parameter for `addLinkerDomainTracker` to optionally omit sending a page view.
This is based on the presence of the data attribute `data-tracking-track-page-view` controlling whether we send a page view or a custom event.

Enable cross domain event tracking for govspeak buttons

---

app/assets/javascripts/modules/cross-domain-tracking.js
spec/javascripts/modules/cross-domain-tracking.spec.js

If we attempt to use cross domain tracking on more than one button
on a single page the linked trackers are added twice. eg.
https://www.gov.uk/check-state-pension/sign-in/create-account
This means that the underlying ga library throws a javascript error.
This commit appends the tracker names to an array to check for
repeat calls to the same tracker.
It also changes the name of the data attribute necessary for tracking an additional
event.

Only add linked trackers once

---

app/assets/javascripts/modules/cross-domain-tracking.js
spec/javascripts/modules/cross-domain-tracking.spec.js

[GOVUK.Modules initializes and starts a module for every element
with a data-module attribute](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/modules.js#L35-L37). 
This causes errors for cross-domain-tracking if two elements should send data to the same tracker because the underlying ga library raises  the error`Command ignored. Plugin "linker" has already been required on tracker "govspeakButtonTracker".`
The trackers are memoized by name at the Modules level so that new instances of CrossDomainTracking can be initialized and started without reconfiguring the same ga tracker.

Memoize linked trackers in the GOVUK.Modules namespace

---

app/assets/javascripts/modules/cross-domain-tracking.js
spec/javascripts/modules/cross-domain-tracking.spec.js

[The initial attempt at deduplicating tracker configuration didn't completely cover this](https://github.com/alphagov/static/pull/1556)
The cross domain tracking module can be applied to a block level element
containing matching elements or to an element suchas an anchor tag.
In the case of multiple start buttons GOVUK.Modules attempts to initialize
trackers on a per button basis, so it's important that both recursive and
explicit element contexts are covered.
This means moving the check for duplicate trackers into the addLinkedTrackerDomain
function as this is called for either element context lookup.

Deduplicate trackers regardless of context

---

Gemfile
Gemfile.lock

This commit updates the gem _govuk_template_ to version `0.25.0`, in order to serve the header with event tracking on the GOV.UK logo.
Solo: @karlbaker02

T117: Update govuk_template to 0.25.0

---

README.md

Gateway timeouts are common when developing static on the VM.
Usually this occurs when running static on the vm with another
frontend app. It's possible to circumvent the problem with an
nginx config update.

Document development VM timeouts

---

app/assets/javascripts/modules/global-bar.js
app/views/notifications/_global_bar.html.erb

In order to know how successful the banners are we want to know if users are getting to the right place (which may be an external link).

Add tracking event when link in banner is pressed

---

app/assets/stylesheets/helpers/_header.scss

https://trello.com/c/STyMu3Cp/97-fix-spacing-below-banner-on-header-ised-pages
This produces whitespace where a blue 'hero' header follows the generic banner, eg. homepage or topic pages.
There's no noticeable difference in spacing on pages without this header.

Remove unnecessary bottom margin

---

app/views/notifications/_global_bar.html.erb

Bug found via e2e test output: https://ci.integration.publishing.service.gov.uk/job/publishing-e2e-tests/job/test-against/17090/artifact/tmp/errors-verbose.log
2nd commit is to demonstrate the bug is fixed and will be removed as we don't want to enable this banner.
cc @nickcolley

Fix global bar dupe attribute definition

---

app/assets/javascripts/analytics/custom-dimensions.js
spec/javascripts/analytics/ecommerce.spec.js
spec/javascripts/analytics/static-analytics-spec.js

We're currently sending the value of two meta tags, `govuk:user-journey-stage` and `govuk:navigation-document-type` to Analytics. These supertypes are out of date and deprecated. They've been removed from the meta tags in https://github.com/alphagov/govuk_publishing_components/pull/709. This also removes the code to send them to analytics.
https://trello.com/c/hp5BJD2i

Remove outdated supertypes

---

app/assets/javascripts/surveys.js

This adds a new survey which will appear
* for 10% of users
* on these paths
```
'/topic/intellectual-property/trade-marks',
'/topic/intellectual-property/patents',
'/topic/intellectual-property/designs',
'/government/organisations/intellectual-property-office',
'/how-to-register-a-trade-mar',
'/apply-for-a-patent',
'/apply-register-design'
```
* between Feb 1st and Dec 31st 2019
[Trello](https://trello.com/c/PVdssIk0/715-intellectual-property-office-ipo-survey)

Add IPO user panel survey

---

app/assets/javascripts/surveys.js

A new survey to appear for all users visiting `/service-standard-reports`
between 07 Feb 2019 and 07 April 2019.

Add standards assurance survey at /service-standards-reports

---

app/views/root/_base.html.erb

https://trello.com/c/CvwsYUuD/341-replace-announcements-link-in-header-footer-and-on-homepage
This switches the link from `/government/announcements` to `/news-and-communications` in the **sitewide footer**.
This is a new finder replacing an old finder. View the new finder: https://www.gov.uk/news-and-communications.

Change link from Announcements to News and communications

---

app/assets/javascripts/govuk-component/govspeak-convert-html-pub-charts.js

Trello: https://trello.com/c/VDgVNurM/544-extract-govspeak-javascript-functionality-to-govukpublishingcomponents
This barchart initialisation is vulnerable to breaking a component if
the initialisation is called twice. As the code for this is moving to
govuk_publishing_components there is going to be a period of time where
this can quite easily occur while apps are being updated and deployed.
This updates this initialisation code to mark when a chart has been
initialised and be able to ignore being run on charts that have already
been initialised.

Make barchart govspeak enhancement resilient to re-initialisation

---

app/assets/javascripts/surveys.js
spec/javascripts/surveys-spec.js

GOV.UK should have a senible expiry date for all cookies.

Set Suvey seen cookie expiry to 2 years

---

lib/tasks/asset_compile.rake

This PR extends the `assets:precompile` Rake task to automatically generate non-digest versions of all JavaScript files, as an intermediary step to ensure that tests on our CI continue to pass until such time as all tests use fingerprinted versions of dependent JS files.
Influenced in large part by https://bibwild.wordpress.com/2014/10/02/non-digested-asset-names-in-rails-4-your-options (Rails 5 offers us no respite in this area either).

Auto-generate non-digest versions of JS assets

---

lib/tasks/asset_compile.rake

This PR adds a missing symbolic link which maps jquery-1.7.2 to jquery-1.12.4. This is a temporary fix until such time as we update the test wrapper to reference a fingerprinted version of jquery-1.12.4, and is necessary to ensure that all apps using Static continue to pass tests on CI.

Add symbolic link for jquery-1.7.2 in assets precompile

---

doc/surveys.md

Add `frontend` to the suggested `bowl` call as it is a common rendering app and
fix typo/mistake in the example link.

Update Testing surveys doc

---

app/views/root/_base.html.erb

This change updates the links in the footer to point to our new
supergroup finders.
Trello: https://trello.com/c/oNnbf7b8/512-add-5-supergroup-finders-to-govuk-footer-s

Update finder links in footer. 

---

app/views/root/_base.html.erb

The statistics finder isn't ready yet. Will enable in a later
PR

Temporarily disable the statistics finder link in the footer.

---

app/views/layouts/govuk_template.html.erb

This PR aims to update the cookie banner coming from govuk_template.
Limitations taken into consideration:
- govuk_template is deprecated (additional work should not be done in that repository) 
- there's no option to pass custom content to replace the cookie banner container
- there's no way to overwrite the cookie banner script because it's being shipped as an IIFE
In order to achieve that I:
- copied over the main layout file ([govuk_template.html.erb](https://github.com/alphagov/govuk_template/blob/f83f1de/source/views/layouts/govuk_template.html.erb)) from govuk_template
- updated the main layout file to replace the cookie banner with the component from govuk_publishing_components (~~[unreleased at this very moment](https://github.com/alphagov/govuk_publishing_components/pull/795); …

Update cookie banner

---

app/assets/javascripts/analytics/custom-dimensions.js

The new custom dimension is Relevant result shown (83). This should be set to 'Yes' if a  search in the finder search box results in a 'relevant result'. (The null label is 'No'.) 
https://trello.com/c/lwQK2Pi7/336-set-up-a-b-test-for-answer-boxes

Adds new custom dimension to track relevant result shown in finders

---

app/assets/javascripts/analytics.js
app/assets/javascripts/surveys.js

Explicitly add dependencies on cookie function (recently moved from govuk_template to govuk_publishing_components) for analytics and surveys.

Analytics and surveys depend on GOVUK.cookie

---

app/views/root/_base.html.erb

We've redirected site search to the all content finder (https://github.com/alphagov/finder-frontend/pull/1015). We should update links to ensure that we don't have to redirect unless
required.
We can keep the link on the 404 page as `/search` still provides a search box.

Point search box at the all content finder

---

app/assets/javascripts/surveys.js
spec/javascripts/surveys-spec.js

We were previously preventing the survey banner from being shown when any other banners were present, including the cookie banner. Now that the cookie banner is persistent, we want to allow both to show at the same time.

Allow survey banner to be shown with cookie banner

---

app/assets/stylesheets/helpers/_header.scss

Brings font size in line with body text font size. Removes the vertical space between the close button and survey title on mobile.
Requested by @markhurrell :

Tweak survey banner styling

---

app/views/root/_base.html.erb

This additional track-click would cause two events
to be fired when users clicked the links.
Trello: https://trello.com/c/z9DP4EMK/402

Remove track-click from footer

---

app/assets/javascripts/analytics/static-analytics.js
spec/javascripts/analytics/static-analytics-spec.js

We originally added a tracking solution within govuk_publishing_components which fired an event if the cookie banner was not shown on the page. However, this could build up and hit our Google Analytics limit.
Instead, we are adding an additional dimension to our existing pageview event, so we don't need an additional event. This is dimension100 which has been defined as "cookie banner shown". It is set to false if seen_cookie_message is true and set to true if seen_cookie_message is false (i.e: when the banner is shown).

Add cookie banner shown dimension to pageview

---

app/views/root/_base.html.erb

We should revisit this in finder-frontend for keyword searches, but I don't want to roll back to using the redirect.  Patching the input form will fix the issue from here, but we'll need to fix the source before we solve the other redirected search boxes.

Set default search order to relevance

---

app/views/root/_base.html.erb

We want to retain the behaviour where empty searches go to the search page
at `/search`.  By changing the action to go to `/search/all` we stopped this.
The `/search` page redirects searches with keywords to go to `/search/all`
and adds the `order=relevance` param.  We added the hidden input here to
replicate that behaviour, but if we're reverting then we no longer need it.
We also broke scoped searches from service manual sub-pages as per https://govuk.zendesk.com/agent/tickets/3693761
I've added a comment to remind future me to not assume that it's trivial.

Reverting change in search box action

---

app/views/root/_footer_support_links.html.erb

Add a direct link to the accessibility page from the GOV.UK footer _(the list Help | Cookies | Contact etc)_  (you currently have to navigate through the ‘Help’ section). 
It should be added between "Contact" and "Terms and conditions". 
This makes our accessibility link more prominent . Monitoring body advice is that the link should never be more than one click away from the user.
EU Accessibility Directive : _“A link to the accessibility statement should be prominently placed on the homepage of the website or made available on every web page, for example in a static header or footer.”_
This applies to new websites from September 2019. Strictly speaking, it doesn’t apply to existing websites until September 2020, but we’ve committed to making GOV.UK bit of an exemplar - so would be good …

Add a direct link to the accessibility page in the footer

---

Dockerfile

The build is failing since a change in Puppet that requires
this variable as part of asset compilation for production.

Add missing env var for Docker build

---

Gemfile
Gemfile.lock

Version 17.0 of govuk_publishing_components includes the code for
the new cookies consent mechanism.

Bump govuk_publishing_components to v17.0

---

spec/javascripts/surveys-spec.js

Stubbing `getCookie` will stub the return value for all calls to `getCookie`, which isn't what we want to do - we really only want to stub the value of TLS cookie.
**Note: these test failures are only present once the govuk_publishing_components has been versioned to include, so a passing build on CI now isn't representative of fixed tests until the Gemfile has also been updated. https://github.com/alphagov/govuk_publishing_components/pull/916**

Set the TLS cookie rather than stubbing getCookie

---

app/assets/javascripts/analytics/init.js.erb
app/assets/javascripts/analytics/static-analytics.js
spec/javascripts/analytics/static-analytics-spec.js
spec/javascripts/surveys-spec.js

**The build is failing because it relies on some fixes from version 17 of govuk_publishing_components and some test fixes in static around TLS cookies, and this hasn't been updated yet.**
If a user doesn't give consent to usage cookies, we need to disable GA tracking. This involves:
- Setting a flag which turns off tracking
- Not automatically setting the value of the GA cookies. This allows us to set the value of the cookies to null on the `govuk_publishing_components` side and not have the cookies be automatically re-created each time we try to do this.

Handle GA cookies when usage cookies are denied

---

Gemfile
Gemfile.lock
app/views/layouts/govuk_template.html.erb

Removes `new_cookie_banner` flag on the cookie banner component.
Following [the change to remove old cookie banner code](https://github.com/alphagov/govuk_publishing_components/pull/959) this flag is no longer required to render the new cookie banner.
**Note: this needs to be deployed only after all frontend apps have been deployed. This is so the new CSS and JS is in place before the `.gem-c-cookie-banner--new` is removed from the HTML via this change.**

Remove new_cookie_banner flag

---

lib/tasks/jasmine.rake

Expands the default task (`bundle exec rake`) to include `spec:javascript`.
At the moment, Javascript tests aren't run when you run `bundle exec rake` - they are only run when running `bundle exec rake spec:javascript`. This means failing tests can go unnoticed until you push to Github and the build fails on CI.
**Note: the Jenkins build remains unchanged, as it already runs `test` and `spec:javascript` separately**

Run Javascript tests on default bundle exec rake

---

app/views/root/_base.html.erb

Change in name from EU Exit to Brexit, requested from Content team.
Trello card: https://trello.com/c/2iQ09yYJ

Change EU Exit to Brexit in footer

---

app/assets/javascripts/analytics/ecommerce.js
spec/javascripts/analytics/ecommerce.spec.js

This lets us set a list title on a per-list basis.
It will allow us to use this tracking stuff on all lists, rather than site search.
This doesn't seem to be in use (https://github.com/search?q=org%3Aalphagov+%22GOVUK.Ecommerce%22&type=Code)
but it soon will be.
https://trello.com/c/YXkJcbBo/851

Allow overriding of list title on ecommerce tracking

---

app/assets/javascripts/analytics/init.js.erb

Previously we were not setting GOVUK.analytics
when the user had denied tracking cookie consent.
This is causing other apps to break as they call methods on this
directly, it always existed before.
This commit sets it to a dummy object (kinda like null object pattern)
with empty functions.
I'm not at all familiar with the how the FE stuff fits together, if there's
a more elegant way to do this, let me know.
I've tried it on integration and it does fix the problem.
Trello: https://trello.com/c/t2LSpLSc/1139-cookie-policy-setting-breaks-js-functions-across-govuk-frontend

Add a dummy GOVUK.analytics when no cookie consent

---

app/views/root/_base.html.erb

It looks like this was already added, but commented out.
Trello: https://trello.com/c/5IMeeSQH/907-add-the-research-statistics-finder-in-the-footer

Add Research and Statistics to site footer

---

app/assets/javascripts/analytics/ecommerce.js

Ecommerce tracking requires GA, but GA is undefined if a cookie policy setting is chosen. This guards against that.

Guard against GA not being defined

---

app/assets/javascripts/analytics/ecommerce.js
spec/javascripts/analytics/ecommerce.spec.js

This adds support for multiple lists to be tracked with Google Analytics enhanced ecommerce as separate lists.
Trello: https://trello.com/c/wfi5IVf1/109-add-ecommerce-tracking

Permit multiple ecommerce lists per page

---

README.md
app/assets/javascripts/analytics.js
app/assets/javascripts/analytics_toolkit/analytics.js
app/assets/javascripts/analytics_toolkit/download-link-tracker.js
app/assets/javascripts/analytics_toolkit/error-tracking.js
app/assets/javascripts/analytics_toolkit/external-link-tracker.js
app/assets/javascripts/analytics_toolkit/google-analytics-universal-tracker.js
app/assets/javascripts/analytics_toolkit/govuk-tracker.js
app/assets/javascripts/analytics_toolkit/mailto-link-tracker.js
app/assets/javascripts/analytics_toolkit/print-intent.js
doc/analytics.md
spec/javascripts/analytics_toolkit/analytics.spec.js
spec/javascripts/analytics_toolkit/download-link-tracker.spec.js
spec/javascripts/analytics_toolkit/error-tracking.spec.js
spec/javascripts/analytics_toolkit/external-link-tracker.spec.js
spec/javascripts/analytics_toolkit/google-analytics-universal-tracker.spec.js
spec/javascripts/analytics_toolkit/govuk-tracker.spec.js
spec/javascripts/analytics_toolkit/mailto-link-tracker.spec.js
spec/javascripts/modules/cross-domain-tracking.spec.js
spec/javascripts/modules/track-click.spec.js

Migrate analytics code from `govuk_frontend_toolkit` into static.
We are trying to retire `govuk_frontend_toolkit` and many other applications depend upon these analytics scripts. Moving these scripts into static is the first step in the eventual plan to move them into `govuk_publishing_components`.
Todo:
- fix failing tests (failing tests are currently skipped). Currently this is only the error tracking tests.
Supersedes https://github.com/alphagov/static/pull/1777/

Add analytics from govuk_frontend_toolkit

---

app/assets/javascripts/analytics/init.js.erb
config/application.rb
config/environments/production.rb

Turn on `addLinkedTrackerDomain`, which allows tracking events to be sent to a secondary GA property. This property requires a unique name (the first property does not, if both do not have a name specified the second one is not fired as GA assumes it is a duplicate).
The third parameter is a domain or list of domains for (we believe) cross domain tracking, which (we also believe) has been enabled by this code change. Further work may be required.
See documentation: https://github.com/alphagov/static/blob/master/doc/analytics.md#tracking-across-domains

Testing the addLinkedTrackerDomain code

---

app/assets/javascripts/analytics/init.js.erb

- currently sending the ga parameter to every link that includes .gov.uk, need to be more specific

Update cross domain tracking

---

app/assets/javascripts/analytics/init.js.erb

- unnecessary to have our own site in there, seems to be causing duplication of page views

Remove www.gov.uk from cross domain tracking

---

app/assets/javascripts/analytics/init.js.erb

Building on the work from https://github.com/alphagov/static/pull/1832, adds more than one linked domain in the format we understand to be correct.

Add linked domains

---

app/assets/stylesheets/helpers/_header.scss

The dismiss button was 1px from the bottom (rather than 0), and it would overlap below 320px width.
Both links are aligned to the bottom:
No overlapping of links on smaller screen widths:

Tweak dismiss button

---

app/assets/javascripts/analytics.js
app/assets/javascripts/analytics/init.js.erb
app/assets/javascripts/analytics/pii.js
app/assets/javascripts/analytics/static-analytics.js
app/assets/javascripts/analytics_toolkit/analytics.js
spec/javascripts/analytics/ecommerce.spec.js
spec/javascripts/analytics/pii.spec.js
spec/javascripts/analytics/static-analytics-spec.js
spec/javascripts/analytics_toolkit/analytics.spec.js

Move the code that strips PII from `analytics.js` into a separate file and update the analytics code to call it. This is preparatory work ahead of some future changes. The result of this PR is that everything should work as it did before, but the code is slightly restructured.
The stripPII code at first glance looks fairly straightforward - a few functions that accept any variable and strip pii from that variable. However there is a complexity in the form of the `PIISafe` attribute of the code in `analytics.js`. I believe this is used when passing objects to the pii safe code - seems there are circumstances where we don't want to strip pii from objects and this mechanism is used to prevent that.
Not sure what the circumstances around this are, but my current theory is that some custom …

Separate out strip pii code

---

app/assets/javascripts/analytics_toolkit/google-analytics-universal-tracker.js
spec/javascripts/analytics/static-analytics-spec.js
spec/javascripts/analytics_toolkit/analytics.spec.js
spec/javascripts/analytics_toolkit/google-analytics-universal-tracker.spec.js

Revert "Call ga set location prior to page view in linker"

---

app/assets/javascripts/analytics_toolkit/google-analytics-universal-tracker.js

Set the redacted ga location parameter prior to sending a page view from the linker tracker code.

Set location prior to page view for linked tracker

---

app/assets/javascripts/error-page.js
app/assets/stylesheets/error-page.scss

The `error-page` template, used for rendering 4xx and 5xx pages, is currently missing the jQuery import (as flagged in #1862) and doesn't have the compatibility with `govuk_template` flag turned on - this is needed for the cookie banner and feedback component used on the pages.
Fixes #1862.

Fix error page template

---

doc/analytics.md

Adding some specific instructions on how to update the cross domain linker for gov.uk. This is documentation for ongoing work and may be subject to modification/removal once the work is completed.
Trello card: https://trello.com/c/GMQxr8kd/106-document-ga-code-on-govuk

Add cross domain linker update instructions

---

app/views/root/_footer_support_links.html.erb

The Accessibility Statement needs to be available from all pages on
the site. Will also replace the old page with a redirect in other
work.

Update footer link to Accessibility

---

app/assets/javascripts/analytics_toolkit/google-analytics-universal-tracker.js
spec/javascripts/analytics_toolkit/analytics.spec.js
spec/javascripts/analytics_toolkit/google-analytics-universal-tracker.spec.js

Sanitises title data for pageviews, specifically aimed at the search page.
Trello card: https://trello.com/c/ZGGRxLrk/153-redact-pii-from-page-titles

Redact PII from page titles

---

app/assets/stylesheets/helpers/_footer.scss

The focus state colours are not consistent across even the homepage,
which is a jarring experience. Explicitly setting the colours for
now until we can get the footer component in to Static.

Override govuk-template footer colours

---

app/views/root/_footer_support_links.html.erb

Added to site-wide footer to increase visibility
[Trello](https://trello.com/c/jK2Yj1Hr/1342-2-add-privacy-notice-link-to-sitewide-footer)

Add Privacy Notice link to site-wide footer

---

app/assets/javascripts/analytics_toolkit/google-analytics-universal-tracker.js
spec/javascripts/analytics_toolkit/analytics.spec.js
spec/javascripts/analytics_toolkit/google-analytics-universal-tracker.spec.js

- cross domain linking is initialised on both the standard tracker (our GA property) and also in addLinkedTrackerDomain, which is now called on a different GA property for the cross domain linking
- presumably the original code was written assuming there'd only be one GA property, hence the slightly odd duplication
- removing as unnecessary
- some other cross domain linking was in place before we activated addLinkedTrackerDomain in this way (e.g. /change-driving-test) but it appears this page inits its own cross domain linker, which is separate from all of this stuff
Trello card: https://trello.com/c/wC0wQGqA/162-remove-duplicate-cross-domain-linking-initialisation

Remove duplicate domain linking

---

app/assets/stylesheets/helpers/_header.scss
app/views/notifications/_global_bar.html.erb

Updates the global banner content to match the campaign. This includes:
- Making the banner more flexible so it can be displayed without the title or without the link if necessary
- Updates the link text
- A slight tweak to stop the link text and hide button overlapping on mobile

Update global banner content to match campaign

---

app/views/notifications/_global_bar.html.erb

Add new focus style to global banner

---

app/assets/javascripts/analytics_toolkit/google-analytics-universal-tracker.js
spec/javascripts/analytics_toolkit/analytics.spec.js
spec/javascripts/analytics_toolkit/google-analytics-universal-tracker.spec.js

- seems to be unnecessary for our purposes: `allowAdFeatures:false` is already being set
- according to https://developers.google.com/analytics/devguides/collection/analyticsjs/tasks displayFeaturesTask `Sends an additional hit if display features is enabled and a previous hit has not been sent within the timeout period set by the advertising features cookie (_gat).` and we're not using display features
Trello card: https://trello.com/c/41rsUlcT/157-implement-allowadfeaturesfalse-on-cross-domain-tracking-and-update-guidance

Remove displayFeaturesTask from GA code

---

app/assets/javascripts/modules/global-bar.js
app/views/notifications/_global_bar.html.erb

Changes the `global_bar_seen` cookie value to include the banner version, therefore adding a versioning mechanism to the banner.
The global banner currently disappears after it has been viewed 3 times or if a user manually dismisses it. This banner could be used in the future for other events, and we therefore may want to "reset" the banner so users who have previously seen it or manually dismissed it will be able to view it again.
Note: this PR does change some of the behaviour, but doesn't address the minified JS in the view. This isn't ideal, but we don't have the time/capacity to tidy it up now.
**This is currently on integration, if you want to test**

Add versioning mechanism to global banner

---

app/assets/javascripts/modules/global-bar.js

To fix Smokey test failures like this: https://deploy.publishing.service.gov.uk/job/smokey/11502/consoleFull
Some of our Smokey tests don't seem to include the global bar, and so the JS included in the global bar view is not executed, including setting a cookie if it doesn't yet exist.
This commit replicates that logic in the global-bar.js file too, so if the cookie is not set, it will set a basic one. The next time the user navigates, that cookie will be updated with the correct version etc.

Handle global_bar_seen cookie not being set

---

app/assets/javascripts/modules/global-bar.js

I missed a `JSON.parse` in the previous fix, so the conditional was always evaluating to true and the count/version were always being set to the default.
Tested on integration and this seems to fix the issue.

Add missing JSON.parse

---

Gemfile
Gemfile.lock
app/assets/stylesheets/helpers/_header.scss
app/views/notifications/_global_bar.html.erb

No longer needed now that it contains more than just a link.
This means we no longer need the `global-bar-link` class, so
that class has been removed too.

Remove bold link style on sitewide banner

---

app/views/root/403.html.erb

Trello: https://trello.com/c/sUjBwDG0/166-clean-up-factcheck
This is not a page not found scenario, I'm assuming the title here was done by mistake.

Fix 403 page title

---

app/assets/javascripts/analytics/ecommerce.js
spec/javascripts/analytics/ecommerce.spec.js

We use ecommerce tracking to know what people click on in search, and
where in the results list that is: when sorting by relevancy, we want
higher up results to match what the users expect.  But relevancy isn't
the only way to sort search results, in which case we wouldn't
necessarily want or expect clicks to be clustered at the top.
So we can see how sort order affects clicks, and to avoid lumping
different use-cases together, we're going to use the selected sort
option as a product variant.
---
[Trello card](https://trello.com/c/CCMNeJl4/972-modify-ecommerce-tracking-to-track-sort-order)

Track ecommerce variant if set

---

app/assets/javascripts/analytics/ecommerce.js
spec/javascripts/analytics/ecommerce.spec.js

At the moment all instances of tracking click events in GA are sent with an eventLabel of 'Results' as shown below.
and this is hardcoded in [ecommerce.js](https://github.com/alphagov/static/blob/6a0d8a619e56063c81c193458bff92618f163306/app/assets/javascripts/analytics/ecommerce.js#L49)
This is sufficient when you're only tracking one set of link clicks with ecommerce.
Ability to track items on separate lists [was added ](https://github.com/alphagov/static/pull/1810) but the clicks always have the hardcoded `eventLabel` as shown above.
For upcoming [spelling suggestion work](https://github.com/alphagov/finder-frontend/pull/1643) we have a requirement to track those links with a different label.
This PR to provide the option to specify the event label sent to GA when clicking a link in a …

Ability to track click events with a custom event label

---

test/test_helper.rb

Resolves:
> Mocha deprecation warning at /home/build/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in
> `require': `require 'mocha/mini_test'` has been deprecated. Please use
> `require 'mocha/minitest' instead.

Resolve mocha deprecation warning

---

app/assets/javascripts/analytics/custom-dimensions.js
spec/javascripts/analytics/static-analytics-spec.js

Add custom meta tag to the dimensionsMap
We'd like to track spelling suggestions on page view. Previously, we set the value via javascript, but it was too late as the pageview object payload was already sent.
Adding this custom meta tag to the allowed map, will enable us
to track if suggestion are displayed on page view.
[Trello ticket](https://trello.com/c/7eVLdKvd/1110-fix-spelling-suggestion-tracking)

Add a custom meta tag dimension for spelling suggestions

---

app/assets/javascripts/modules/base-target.js
app/assets/javascripts/start-modules.js
app/views/root/_javascript.html.erb
config/initializers/assets.rb
spec/javascripts/modules/base-target.spec.js

Add a script to determine whether or not the current page sits within an <iframe>. If it does we change the base target to be blank so that all links will open in a new window (outside the iframe).
To allow people to check links (especially when they point to an non-secure (http) location) while previewing pages in Content Publisher.
[Trello card](https://trello.com/c/JMWWsYBT)

Add base target blank when rendered in iframes

---

app/assets/stylesheets/helpers/_header.scss
app/views/notifications/_global_bar.html.erb

Trello: https://trello.com/c/Lu2x8C4G/236-add-register-to-vote-banner
- Updates global banner content to point to Register to Vote page
- Adds logic to support an automatic turn off date and time
- Sets automatic turn off datetime to 11:59pm on 26th November 2019

Add register to vote banner

---

app/assets/stylesheets/helpers/_header.scss
app/views/notifications/_global_bar.html.erb

We want the register to vote link to be on the banner title rather than the descriptive text.

Switch banner link to title

---

app/views/notifications/_global_bar.html.erb

Removes the unnecessary `govuk-link` class - this will otherwise add hover and focus states to non-link text.

Remove unnecessary govuk-link class

---

.rubocop.yml
Gemfile
Gemfile.lock

- See commits for more detail.
https://trello.com/c/CdBFg6yw/1521-replace-govuk-lint-with-rubocop-govuk

Replace govuk-lint and fix offenses in the Gemfile

---

app/assets/javascripts/analytics/init.js.erb

Missed one from yesterday.
Adding some more service domains to the cross domain linking configuration, now that they've turned on cross domain tracking.
See https://github.com/alphagov/static/blob/master/doc/analytics.md#adding-more-domains-to-govuks-cross-domain-linker

Add linked domain

---

app/assets/javascripts/analytics/ecommerce.js
spec/javascripts/analytics/ecommerce.spec.js

Trello: https://trello.com/c/2iCWKnNV/274-adjust-existing-ecommerce-tracking-logic-to-handle-passing-page-path-as-name
Adds a `name` parameter which can send a page path to GA, instead of `id`.
The current ecommerce tracking logic supports passing in a page content-id or page path as the `id` param. This was originally implemented to stop the payload sent to GA from being too large. However, it makes the GA dashboard take a lot longer to create because they need to do separate lookups against each content id. It would be simpler to just be able to send the page path directly.
To make reporting quicker to load for performance analysts
So we can support ecommerce tracking on the Brexit checker results page
**Note: this is a backwards compatible change. Once this is deployed, existing …

Support page path as name in ecommerce tracking

---

app/views/notifications/_global_bar.html.erb

Its not being shown any more, so we can set it to false.

Remove vote banner

---

app/assets/javascripts/analytics_toolkit/google-analytics-universal-tracker.js
spec/javascripts/analytics_toolkit/google-analytics-universal-tracker.spec.js

- extends trackPageView function to accept a trackerName parameter in the options object, allowing pageviews to be sent to a tracker other than our default GA property
- this functionality was already in the trackEvent function following it, basically copying it from there
- defaults to no tracker name, so will not effect existing calls
We want to get all pageviews into the shared GA property, which will include those sent when pages are updated dynamically, for example in search, when users choose different search filters and the page and URL are updated without a page reload. This will allow us to call the trackPageView function and pass it the name of the tracker to use.
Trello card: https://trello.com/c/FYntaHmw/92-send-virtual-pageviews-for-ajax-page-updates-on-search-finders-and-main …

Allow pageview function to be passed a tracker name

---

app/views/notifications/_global_bar.html.erb

We previously added logic in https://github.com/alphagov/static/pull/1934 to automatically take down the banner at a specified close date.
However, this didn't work as expected due to templates being cached when they are requested by Slimmer. Bypassing this caching would be more challenging and as there isn't an immediate use case for this work (we can manually remove the banner instead) we're going to remove this logic for now.
If this feature is requested in the future, we now know that this is more difficult to implement than we first thought and can scope accordingly.

Remove close date logic from banner

---

app/assets/javascripts/modules/global-bar.js
app/views/notifications/_global_bar.html.erb

The default behaviour of the banner is to show for 3 pageviews, and then automatically hide. It can also be manually dismissed by the user.
We want the ability to have the banner be permanent, i.e: it will always show, regardless of the number of pageviews. This won't affect the user's ability to manually dismiss the banner.
How it works: if `always_on` is set to `true`, the view count for the global bar cookie is never updated which means the banner won't automatically hide as the count will never reach 3.

Add ability to make global banner permanent

---

app/assets/javascripts/analytics/scroll-tracker.js

Trello: https://trello.com/c/7aaD7Xkt/333-add-scroll-tracking-for-brexit-insights-team
Add page URLs and headings to be tracked using scroll tracking.
The performance analysts on the Insights team have asked us to add scroll tracking to these pages.

Add scroll tracking to pages

---

app/assets/stylesheets/header-footer-only.scss
app/assets/stylesheets/helpers/_footer.scss

Part of https://trello.com/c/fxfRx7dQ/95-remove-govukfrontendtoolkit-from-static
This PR
- imports govuk_publishing_component Sass files into header_footer
- replaces toolkit variables and mixins with publishing components

Update footer partial to not use frontend_toolkit

---

app/assets/javascripts/analytics.js
app/assets/javascripts/analytics/init.js.erb
spec/javascripts/analytics/ecommerce.spec.js

Don't load in GA script if consent cookie is null
We previously assumed that if the consent cookie was null, we could load in the GA script. We can't do this now we've changed to opt-in.
**Note: tested on integration. GA cookies are no longer being set on page load, unless consent has been given.**

Stop setting GA if consent is null

---

app/assets/javascripts/surveys.js

The IPO survey finished in December 2019, so can be removed.
[Trello](https://trello.com/c/9I0GBFqa/1654-remove-ipo-small-survey)

Removes small survey that completed on 31/12/19

---

app/assets/stylesheets/core-layout-ie6.scss
app/assets/stylesheets/core-layout-ie7.scss
app/assets/stylesheets/header-footer-only-ie6.scss
app/assets/stylesheets/header-footer-only-ie7.scss
app/assets/stylesheets/helpers/_buttons.scss
app/assets/stylesheets/helpers/_core.scss
app/assets/stylesheets/helpers/_header.scss
app/assets/stylesheets/helpers/_multi-step.scss
app/assets/stylesheets/helpers/_publisher.scss
app/assets/stylesheets/helpers/_text.scss
app/assets/stylesheets/static-ie6.scss
app/assets/stylesheets/static-ie7.scss
app/views/layouts/govuk_template.html.erb
app/views/root/_stylesheet.html.erb

Removing the IE6 and IE7 specific stylesheets from static because we no longer support these browsers and this will speed up the compile time fractionally, which will be useful for future work.
Will address IE8 in a future PR - it feels like supporting that might be more controversial, so I'm trying to make this PR simple. I've left several 'less than or equal to IE8' statements in place.
I don't know where these styles are used so the way I've done this is to reproduce the markup for the elements that will change temporarily (in frontend's homepage) and taken screenshots to show the changes. My aim is to document these changes and ensure that nothing causes a dramatically bad thing to happen - we don't have to support these browsers, but we can still be kind.
The search box at the start …

Remove IE6/7 specific styles from static

---

app/assets/stylesheets/header-footer-only.scss
app/assets/stylesheets/helpers/_core.scss
app/assets/stylesheets/helpers/_wrapper.scss

- the #wrapper styling was recently restructured, but government-frontend had a problem with it
- looks like all apps pull in static's static.css, but gf pulls in core-layout, which is a bit different and thanks to the recent changes no longer included the #wrapper styling
- this all needs to be fixed and replaced properly at some point in every app, by using govuk-site-container (or whatever it is) in place of styling an ID and nesting everything underneath that 
This PR is a little bit unclear, so here's some more detail.
The two files we're concerned with are `static.scss` and `core-layout.scss`. They both import `header-footer-only` so I've modified that to pull in the new file, `wrapper`, which itself pulls in the mixin for `site-width-container` and creates the `#wrapper` styling …

Fix layout for government-frontend

---

app/assets/javascripts/analytics/scroll-tracker.js
app/assets/javascripts/global-bar-init.js

Trello: https://trello.com/c/DsPNCfTV/429-update-global-banner-logic-to-stop-it-appearing-on-transition
Stops transition banner showing on:
- /transition
- /transition-check (the newly re-slugged brexit checker)
Also update scroll tracking config to monitor the new /transition path.

Update global banner path blacklist (Transition pages)

---

app/assets/javascripts/modules/global-bar.js

Trello: https://trello.com/c/eSgqMYLV/438-fix-global-banner-following-cookie-change
Wraps some of the global bar logic in a check for cookie consent.
**Note: this introduces a bit of tech debt in that it assumes in the code that the global_bar_seen cookie is categorised under "settings". Ideally, we'd have a method in the govuk_publishing_components gem that takes a cookie name and returns the category, but that doesn't exist yet and we're under time pressure to fix this bug. I'll make a note to address this soon.**
The global bar relies on having a `global_bar_seen` cookie set with version and view count. If cookies are not allowed, this cookie isn't present and you get a Javascript error which also prevents things like the "Hide message" button working.
This is something we missed when …

Handle cookie consent in global bar

---

app/views/layouts/govuk_template.html.erb
app/views/notifications/_global_bar.html.erb
app/views/root/_javascript.html.erb
app/views/root/_stylesheet.html.erb
app/views/root/print.html.erb

Change to remove SRI on the JavaScript / CSS and remove the `crossorigin` attribute.
This change is part of [RFC-115](https://github.com/alphagov/govuk-rfcs/pull/115).
Changes have been tested on integration, [seen here](https://github.com/alphagov/static/pull/1993#issuecomment-580287175)

Remove crossorigin and SRI from our static assets (CSS/JS)

---

Gemfile
Gemfile.lock
app/assets/javascripts/modules/global-bar.js

Trello: https://trello.com/c/3rncf9Pt/439-tech-debt-global-bar-logic-assumes-cookie-category
The global_bar_seen cookie is in the "settings" category. For a quick fix, we previously hardcoded this assumption into Static, which is bad if we decided to change the category in the govuk_publishing_components gem.
We now have a function in the gem where we can provide a cookie name and the category is returned. This commit replaces our hardcoded 'settings' category with that method.

Use getCookieCategory rather than assuming category

---

app/assets/stylesheets/header-footer-only.scss
app/assets/stylesheets/helpers/_core-print.scss
app/assets/stylesheets/helpers/_core.scss
app/assets/stylesheets/helpers/_footer.scss
app/assets/stylesheets/helpers/_govuk-emergency-banner.scss
app/assets/stylesheets/helpers/_header.scss
app/assets/stylesheets/helpers/_organisations.scss
app/assets/stylesheets/helpers/_print-base.scss
app/assets/stylesheets/helpers/_selectable.scss
app/assets/stylesheets/settings/_measurements.scss
app/assets/stylesheets/static.scss

Moved the spacing function (`govuk-spacing(𝖷)`) into static so it can be used without importing all of the publishing components gem.
Replaced the all of the `$gutter` variables and hardcoded variables that could be directly replaced with a spacing function without impacting the layout. So `30px` and `$gutter` were replaced with `govuk-spacing(6)`, but any magic numbers like`48px` were left alone.
The Sass functions and variables are useful. But if we import publishing components we'll inflate the amount of CSS in static dramatically - so we need to add just the functions and variables on their own. This is a quick way of doing it until the publishing components gem allows only importing specific parts on their own.
None

Move measurement into static from toolkit

---

app/assets/stylesheets/static.scss

The spacing functions were being imported after the footer and header stylesheet - this meant that the spacing functions weren't being processed, which broke the spacings. This changes the order of imports to fix that.
The footer looked broken.
Before:
After:
Live:

Fix spacing regression in footer

---

app/assets/stylesheets/header-footer-only.scss

Different applications import different layouts - it looks like one layout imports the measurements scss, but one wasn't, which meant certain components (e.g: global and survey banners) were rendering without spacing.

Reinstate spacing for core layout imports

---

app/assets/javascripts/global-bar-init.js

Trello: https://trello.com/c/hA65u9qV/460-global-banner-setting-two-cookies-on-some-pages
Use cookie helper functions in the global bar init logic, to match the rest of the global bar logic.
The global banner was setting two cookies on some pages, one with a path of '/' and one with the path of the page. This had the side effect of the banner not being able to be dismissed (it also didn't disappear after 3 page views). This looked like it was happening because some of the global bar functions set the cookie manually without specifying a path, whereas other functions use the cookie helper function which always set the path to '/'.
**Example page to check:**
[www.gov.uk/government/organisations/companies-house](www.gov.uk/government/organisations/companies-house)

Fix global bar multiple cookies

---

app/assets/stylesheets/helpers/_header.scss

Set the global banner border to custom light blue
This got replaced when we moved to using colours from GOVUK Frontend. However, this is actually a one off and it should use the custom blue rather than govuk brand colour.

Set the global banner border to custom blue

---

app/views/root/_base.html.erb

Add govuk-link class to transition period footer link

---

app/assets/stylesheets/helpers/_footer.scss
app/assets/stylesheets/helpers/_header.scss
app/assets/stylesheets/helpers/_multi-step.scss
app/assets/stylesheets/helpers/_text.scss
app/assets/stylesheets/static.scss
app/views/root/_base.html.erb

Removing the shims that static loads in from toolkit.
There were two shims mixing coming in from toolkit. 
One was for `display: inline-block` which wasn't being used, so hasn't been moved across. 
The other was for elements that contain floated elements - a clearfix. Where possible, this has been replaced with the `govuk-clearfix` class on the element. In two places, the styles weren't affecting anything in the templates in static - so the class couldn't be added in static. In those places I've imported the shim specifically into those stylesheets rather than into the base stylesheet. 
A step along the road towards the complete removal of toolkit from static - and turning off of the compatibility mode.
None

Remove govuk_toolkit shims

---

app/assets/javascripts/global-bar-init.js

We had a bug which meant that the global_bar_seen cookie was sometimes set more than once.
This bug has now been fixed (https://github.com/alphagov/static/pull/2026), but some users will be left with these duplicate cookies and therefore will continue to see the issue.
This commit introduces a function that checks for these duplicate cookies and deletes them if they're present.

Remove duplicate global_bar_seen cookies

---

app/assets/javascripts/analytics/custom-dimensions.js
spec/javascripts/analytics/static-analytics-spec.js

We will be looking to track whether displayed search results were as a result of users selecting a suggestion from the title autocomplete or whether they just used the keyword search.
Dimension 21 was chosen in https://trello.com/c/FbRA8Wf1/1337-define-tracking-on-title-suggest-autocomplete and agreed with the Performance analyst community as per below
> Dimension 21 has been changed on Google analytics GOV.UK main profile.
> This was previously "search position" but was no longer being used.
> It has been renamed to "Search autocomplete status".
> The name can be changed at a later date.
[Trello ticket](https://trello.com/c/ddyRrx5k/1381-create-a-analytics-meta-tag-in-alphagov-static)

Add a custom meta tag for dimension 21

---

Gemfile
Gemfile.lock
app/assets/stylesheets/header-footer-only-print.scss
app/assets/stylesheets/header-footer-only.scss
app/assets/stylesheets/helpers/_core.scss
app/assets/stylesheets/helpers/_footer.scss
app/assets/stylesheets/helpers/_govuk-emergency-banner.scss
app/assets/stylesheets/helpers/_header.scss
app/assets/stylesheets/helpers/_mixins.scss
app/assets/stylesheets/helpers/_organisations.scss
app/assets/stylesheets/helpers/_publisher.scss
app/assets/stylesheets/helpers/_selectable.scss
app/assets/stylesheets/modules/_sticky-element-container.scss
app/assets/stylesheets/static-pages/error-pages.scss
app/assets/stylesheets/static.scss
app/assets/stylesheets/styleguide/_conditionals2.scss

Remove `govuk_frontend_toolkit` conditionals from static. This involves:
- an update to include a new version of the components gem that allows static to import `govuk-frontend` mixins and variables (but no actual CSS weight)
- copying the IE conditional from toolkit
- updating all the media queries to use govuk-frontend, not toolkit
- pulling in the sass file from the gem for the cookie banner and feedback components(see below)
Just another step along the road to removing toolkit from the gem.
In this new world of using specific sass for only the components an app is using from the gem, we need to import the sass for the cookie banner and feedback components into static, because static renders them, not the apps. At the moment this all works because all apps include all the components …

Remove toolkit conditionals

---

app/views/notifications/_global_bar.html.erb

Hide the global banner
The fact we've left the EU is known, and transition information is well signposted around GOV.UK.

Hide the global banner

---

app/assets/stylesheets/helpers/_header.scss

Vertically align the title in the global bar 'component'.
Update: There are a few variations for the global bar. Updated so that it copes with all.
<table>
<tr><td>
</td></tr>
</table>

Centre global bar title vertically

---

app/assets/javascripts/global-bar-init.js

Replace hardcoded blacklisted paths with the path of the page the call to action link points to.
Follow up on #2057 and #2059.

Hide global bar on the referred page

---

app/views/notifications/_global_bar.html.erb

Because the init runs right away (without awaiting the page to load) it's not able to query the markup elements (as they aren't loaded yet). [See this issue in integration](https://www.integration.publishing.service.gov.uk/government/topical-events/coronavirus-covid-19-uk-government-response).
Follow up on #2060.

Move global-bar-init in body_end

---

app/assets/stylesheets/error-page-print.scss
app/assets/stylesheets/error-page.scss
app/assets/stylesheets/header-footer-only-print.scss
app/assets/stylesheets/header-footer-only.scss
app/assets/stylesheets/static.scss
app/views/root/404.html.erb
app/views/root/406.html.erb
app/views/root/410.html.erb
app/views/root/_error_page.html.erb
config/initializers/assets.rb

- Remove imports of feedback component CSS in general static stylesheets (e.g: static, core, header-and-footer-only). Instead, only import the feedback component where it's used in the error-page.css.
- Don't import all components in the error pages - we don't need everything
- Don't import error page css in the general css file. The error page template supplies a stylesheet tag for the error-page.css
- Add govuk-link class to error page content for consistent focus states
The feedback component is only shown on error pages within Static. In other cases, the frontend applications themselves are pulling in the feedback component HTML and CSS.
The existing behaviour meant we had duplicated CSS for the feedback component as it was being imported once by static and once by the frontend app. …

Only import feedback component CSS on error pages

---

app/assets/stylesheets/helpers/_header.scss
app/views/notifications/_global_bar.html.erb

Update to the banner message copy and styles - the red warning layout is toggled with `warning ||= true` in the partial.
Design from @stephenjoe1
Before:
After:
Warning:
<table>
<tr>
<th>Before</th>
<th>After</th>
<th>Warning</th>
</tr>
</td><td>
</td><td>
</td>
</tr></table>

Update banner message and styles

---

app/assets/javascripts/analytics/ecommerce.js
spec/javascripts/analytics/ecommerce.spec.js

trello: https://trello.com/c/wyHXRVll/138-add-ecommerce-tracking-to-mainstream-browse
Depends on: https://github.com/alphagov/static/pull/2072
Adds an optional `list-subheading` attribute that will be sent to google analytics as dimension 94. If the tracked element has an attribute `ecommerce-subtitle` the value will be sent, otherwise dimension94 will not be included in the playload to GA.
We are adding ecommerce tracking to many of our browse pages. Some lists have subheadings that internally group rows. It is a requirement that we are able to track these too.
This work in an effort to build better baseline data around the browse experience on GOV.UK ahead of considering changes.

Add list subheading as optional attribute to ecommerce tracking

---

app/assets/stylesheets/helpers/_header.scss

The focus state for the link in the banner was white when visited, instead of black.
Fixed to meet the contrast criteria to make the link readable and accessible.
Before:
After:

Fix :visited :focus state for link in banner

---

app/assets/stylesheets/helpers/_header.scss
app/views/notifications/_global_bar.html.erb

The global link styles from static / govuk_template were clashing with `govuk-link` - so the link styles for the warning banner layout have been updated to not use that class.
The focus state styles comes from the GOV.UK Frontend mixin.

Refactor banner link focus states

---

app/assets/stylesheets/helpers/_header.scss

Corrected the scss indentation.
This was noted on [PR#2084](https://github.com/alphagov/static/pull/2084#pullrequestreview-373902860) but a deploy was needed more than fixing the indentations. So it's now being fixed.
None

Fix stylesheet indentation

---

Gemfile
Gemfile.lock

Update to (temporarily) use a branch of the frontend toolkit gem, which uses the branch `add-tracking-see-where-js-is-being-used` of govuk_frontend_toolkit.
If a user has given permission, this will fire a GA event to let us know which JavaScript is being used and where. 
We can then see if / where these JavaScripts are being used and know where to provide a suitable replacement.

Add tracking to see where the JS is being used

---

Gemfile
Gemfile.lock

This used up a lot - a lot! - of events, so is being reverted to prevent the quota from being exhausted. 
The gem has been commented out rather than deleted, since we will need to use it again to check again where the JavaScript is being initialised in the near future.

Remove the tracking that fires when old JS is initialised

---

app/views/root/_base.html.erb

Trello link:
https://trello.com/c/gWEwtJXq/21-coronavirus-link-updates-for-footer-and-popular-links

Adds coronavirus section to footer

---

app/assets/javascripts/global-bar-init.js

Stop the coronavirus global banner from appearing on the coronavirus page itself.
Trello card: https://trello.com/c/3kzzbqME/43-update-the-banner-to-not-show-on-coronavirus

Hide coronavirus banner on coronavirus page

---

app/views/notifications/_global_bar.html.erb
app/views/root/_base.html.erb

Because /coronavirus currently redirects to the topical event page, this
can be merged and deployed whenever we like.
The topical event page will be redirected back to the new landing page once it
it published.
https://trello.com/c/9EMnRGEh/38-update-the-banner-link

Update links for coronavirus landing page

---

app/assets/javascripts/global-bar-init.js

Previously it was checking for segments so if we had `/coranavirus` blocked, `/guidance/coronavirus-covid-19-information-for-the-public` would be blocked too as it has `/coronavirus` in the middle.
This change now forces the regex to check exact match so it would only match if the path is `/coronavirus` not `/guidance/coronavirus-covid-19-information-for-the-public`.
Trello: https://trello.com/c/a83JfZDG/60-check-why-the-banner-doesnt-appear-on-certain-pages

Now matches the exact path for url blocking

---

app/views/root/_base.html.erb
test/integration/templates/error_4xx_test.rb
test/integration/templates/error_5xx_test.rb
test/integration/templates/header_footer_only_test.rb
test/integration/templates/homepage_test.rb
test/integration/templates/wrapper_test.rb

This is because we want to prevent load on our search service.

Remove (temporarily) the search box from header

---

app/assets/javascripts/surveys.js
spec/javascripts/surveys.spec.js

Or on /coronavirus. I believe the concern here is regarding screen
space on these pages.

Stop surveys appearing when the global bar is visible

---

app/assets/javascripts/analytics/ecommerce.js
spec/javascripts/analytics/ecommerce.spec.js

We're going to use this on search results pages to track displaying
subpages (eg, parts of guides).  These are going to be tracked as
multiple results in the same position, but with different links.
---
[Trello card](https://trello.com/c/9EfcgjHZ/1415-add-ecommerce-tracking-for-parts-in-results)

Allow using data-ecommerce-index to override implicit index

---

app/views/notifications/_emergency_banner.html.erb
app/views/notifications/_global_bar.html.erb

Similar to https://github.com/alphagov/govuk_publishing_components/pull/1185
Banners don't hold content specific to each page, so shouldn't be shown in
search results.
https://developers.google.com/search/reference/robots_meta_tag#data-nosnippet-attr

Don't show banner content in google snippets

---

app/assets/javascripts/global-bar-init.js

We'll show a breadcrumb back to the coronavirus page.
We don't need to include it in the "auto-hide the banner if you've seen this page" logic because the banner duplicates /coronavirus content and not /coronavirus/business-support logic
We can remove the explicit coronavirus link here too, as it's picked up by the call to action code below the exclusion list
https://trello.com/c/CXuwza3f/136-hide-the-coronavirus-banner-on-the-business-landing-page

Exclude business page from the coronavirus banner

---

app/assets/stylesheets/helpers/_header.scss

Trello: https://trello.com/c/YT0f0FDN/133-update-theme-from-lime-to-lemon
Update border-top colour for banner from green to yellow
To match the new branding colours for Public Health England

Update colours from lime to lemon

---

app/assets/stylesheets/helpers/_header.scss
app/views/notifications/_global_bar.html.erb

Wraps part of the global banner text in a non-whitespace-wrapping span, so that the text wraps nicer on smaller screens. No change on desktop.
Before:
After:

Enforce line break on global banner text

---

app/views/root/_base.html.erb

https://trello.com/c/N5PXmpHC/123-change-transition-period-section-of-govuk-footer
This is not about 'coronavirus transition (of out lockdown)'. Our
analytics shows users are confused about this particular link.

Clarify transition footer text

---

app/assets/javascripts/global-bar-init.js

We expect these to be hub pages which have a hefty breadcrumb linking back to the coronavirus landing page.
Example pages:
https://www.gov.uk/coronavirus/business-support
https://www.gov.uk/coronavirus/education-and-childcare

Suppress banner for sub-pages of /coronavirus

---

app/assets/javascripts/analytics/scroll-tracker.js

Analysts want to be able to see any patterns of scrolling on specific
pages.
Trello card: https://trello.com/c/dOsIkYZi/1957-add-scroll-tracking-to-some-coronavirus-pages

Add scroll tracking to some coronavirus pages

---

app/views/notifications/_global_bar.html.erb

Update site wide banner text as per slack conversation with @samdub

Update copy in site wide banner

---

app/views/notifications/_global_bar.html.erb

Provide a toggle to switch off the emergency banner message area (the bit in the red box in the screenshot). The main darker emergency banner section with the arrow link should remain.
We no longer need a holding message as guidance has been updated.
https://trello.com/c/u4L3Xoet/278-waiting-on-confirmation-switch-off-the-emergency-banner-message-area

Toggles additional banner

---

app/assets/stylesheets/error-page-print.scss
app/assets/stylesheets/error-page.scss
app/views/root/400.html.erb
app/views/root/401.html.erb
app/views/root/403.html.erb
app/views/root/404.html.erb
app/views/root/405.html.erb
app/views/root/406.html.erb
app/views/root/410.html.erb
app/views/root/429.html.erb
app/views/root/500.html.erb
app/views/root/501.html.erb
app/views/root/503.html.erb
app/views/root/504.html.erb
app/views/root/_error_page.html.erb
test/integration/templates/error_4xx_test.rb
test/integration/templates/error_5xx_test.rb

https://trello.com/c/Uzpw1bDA/243-document-how-error-pages-work-on-govuk
Related to: https://github.com/alphagov/slimmer/pull/245
Previously the use of Slimmer meant that all unexpected responses
were treated as '500 Internal Server Error', which is incorrect and
misleading, since the fault is often with the client. This adds new
error pages to cover all public error responses in the last 30 days.
Please see the commits for more details.

Add missing pages for known errors

---

app/views/notifications/_global_bar.html.erb

This is a follow up PR on the work done by @DilwoarH here #2170
We have been given the go-ahead to switch the dismissible banner off for good.
This toggles the banner off by setting the `show_additional_banner` flag to `false`
https://trello.com/c/u4L3Xoet

Switch dismissable banner off

---

app/assets/javascripts/analytics/scroll-tracker.js

Adding the tracking to the new guidance/answers-to-the-most-common-topics-asked-about-by-the-public-for-the-coronavirus-press-conference page
Added at the end of the config variable and set to percentage of scrolling in 20% increments
This PR replaces: https://github.com/alphagov/static/pull/2175 (I fixed a minor comma error)

Adding google analytics scroll depth tracking

---

app/assets/javascripts/global-bar-init.js

Since the additional banner message was removed this has been erroring
and the banner cookie is not being set properly.

Add conditional for removing additional banner message

---

app/assets/javascripts/start-modules.js

Use the modules script from [`govuk_publishing_components`](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/javascripts/govuk_publishing_components/modules.js) instead of [`govuk_frontend_toolkit`](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/modules.js).
We recently [updated the `modules.js`](https://github.com/alphagov/govuk_publishing_components/pull/1472) in `govuk_publishing_components` without realising that `static` is still using the `modules.js` from `govuk_frontend_toolkit`.

Update modules script

---

app/assets/stylesheets/header-footer-only.scss

Static has the Sass for the action link component because we're using it in the global banner on every page of GOV.UK. Collections is also using the action link component. Rather than duplicate the CSS, collections is relying on the copy in static. 
This PR adds a comment to the Sass to explain that to prevent someone from removing the Sass from static without putting it into collections first.
Should have been part of https://github.com/alphagov/static/pull/2192. See also https://github.com/alphagov/collections/pull/1754

Add comment to sass

---

app/assets/stylesheets/error-page-print.scss
app/assets/stylesheets/error-page.scss
app/views/root/400.html.erb
app/views/root/401.html.erb
app/views/root/403.html.erb
app/views/root/404.html.erb
app/views/root/405.html.erb
app/views/root/406.html.erb
app/views/root/410.html.erb
app/views/root/422.html.erb
app/views/root/429.html.erb
app/views/root/500.html.erb
app/views/root/501.html.erb
app/views/root/503.html.erb
app/views/root/504.html.erb
app/views/root/_error_page.html.erb
test/integration/templates/error_4xx_test.rb
test/integration/templates/error_5xx_test.rb

https://trello.com/c/gl0JJDev/296-iterate-copy-and-design-for-the-fallback-govuk-error-pages
This updates the copy on the most of the error pages, following a
content review. We also make a few other changes:
- Move and re-style the "Status code" message
- Synchronise the browser title with the page heading
Previously we had a mixture of browser titles being in-sync (or not)
with the page heading, for no apparent reason. The convention on
GOV.UK is generally to use the same text for both.

Iterate design and copy for error pages

---

config/application.rb
config/environments/development.rb
config/environments/production.rb
lib/tasks/asset_compile.rake
test/integration/icon_redirects_test.rb
test/integration/templates/chromeless_test.rb
test/integration/templates/error_4xx_test.rb
test/integration/templates/error_5xx_test.rb
test/integration/templates/header_footer_only_test.rb
test/integration/templates/homepage_test.rb
test/integration/templates/wrapper_test.rb
test/integration/templates/wrapper_with_js_last.rb

Trello: https://trello.com/c/oNEtjIVp/99-serve-static-assets-from-www-hostname
This is marked as a draft until the following PR's are merged (and in puppets case, deployed):
As part of the work to enable RFC 115 [1] we intend to switch static
from serving assets on the asset hostname to instead use the regular www
hostname. Static, unlike other GOV.UK applications, requires a host name
to be set so that the live version of static can be used in development
environments and heroku preview environments.
Both environment variables are in use in these changes so that static
can continue to operate under both configurations.
[1]: https://github.com/alphagov/govuk-rfcs/blob/45e09c088bfde6c1d4dfb68f9bc1c635f63c9a39/rfc-115-enabling-http2-on-govuk.md

Specify asset host with ASSET_HOST env var over GOVUK_ASSET_ROOT

---

app/assets/javascripts/start-modules.js

Calls the cookie banner component JS wherever the JS in static references the related JS in the gem's lib dir.

Call cookie banner component JS

---

app/assets/javascripts/analytics.js
app/assets/javascripts/analytics_toolkit/auto-track-event.js
spec/javascripts/analytics_toolkit/auto-track-event.spec.js

After [migrating `frontend` from `wrapper` to `core_layout`](https://github.com/alphagov/frontend/pull/2154) we ended up in a position where `auto-track-event` was missing from our analytics bundle in `static`, causing [a gap in our GA data](https://govuk.zendesk.com/agent/tickets/4096617).
To fix this I migrated the `auto-track-event` from `govuk_frontend_toolkit` to `static`, as this was [planned work in the GOV.UK Frontend and Accessibility backlog](https://trello.com/c/TMYS2FKT/222-migrate-javascript-from-toolkit-into-static) anyway, and added it to the common analytics bundle in static making it available to `frontend` again.
You can test this by checking for `GOVUK.Modules.AutoTrackEvent` in the browser console in `frontend`.

Migrate auto track event from toolkit

---

app/views/notifications/_global_bar.html.erb

We should switch off the message area in the Coronavirus emergency banner (the dark grey banner), leaving the main bit (the black banner) in place.
Guidance has been updated so we no longer need to direct people to the PM's speech.
https://trello.com/c/eAlNwog6

Switch off additional banner

---

app/assets/javascripts/global-bar-init.js

We don't want to see the coronavirus banner on:
- /transition
- /transition.cy
- /transition-check/questions
- /transition-check/results (or any other checker URLs that appear)
https://trello.com/c/sIFjKsm9/306-stop-covid-banner-from-appearing-on-transition-pages

Stop covid banner on transition pages

---

app/views/root/scheduled_maintenance.html.erb

- We moved away from updating the GOV.UK blog a while ago. If any users got to this page during scheduled maintenance and clicked through, they would have then had to click another link to get to the reason for the maintenance.

scheduled_maintenance: Link to StatusPage, not the old GOV.UK blog

---

app/assets/javascripts/global-bar-init.js

The banner code was trying to manipulate a cookie that doesn't
yet exist. This sets the default if none is present and removes
a redundant if statement.
The bug can be seen by going in an incognito window (so no cookies are set for the site) to http://www.gov.uk/help/cookies - the js crashes and makes it impossible to set cookie preferences which is the purpose of that page. This probably only affects this page as elsewhere the cookie defaults are set in the cookie banner that is excluded from appearing here.

Fix crash on cookie setting

---

app/assets/javascripts/global-bar-init.js

A new DIT landing page is being developed at the moment. Once it's live, it should not display the emergency coronavirus banner.
Trello: https://trello.com/c/BWoZhE3E/369-build-dit-campaign-page

Hide the coronavirus banner from the DIT landing page.

---

app/views/root/_base.html.erb

- this relates to some changes in finder-frontend to do with roles and aria-labels
- you can have more than one role="search" on a page but they need distinguishing labels
- this adds an aria-label so that the purpose of the search in the header can be distinguished from other search elements on a page e.g. in finders such as /search/news-and-communications
Related PR: https://github.com/alphagov/finder-frontend/pull/2192
Example:
Trello card: https://trello.com/c/pv1P0xgu/362-search-results-wrong-use-of-search-aria-role

Add aria-label of "Sitewide" to main header search

---

public/humans.txt

Firstly, clarify that GDS is not just London now - we've got offices in Bristol and Manchester
Secondly, wrap text at 100 characters, so it's not so difficult to read.

Small updates to www.gov.uk/humans.txt

---

public/humans.txt

From http://humanstxt.org/ -
> humans.txt is an initiative for knowing the people behind a website.
> It's a TXT file that contains information about the different people who
> have contributed to building the website.
> The internet is for humans...
> We are always saying that, but the only file we generate is one full
> of additional information for the searchbots: robots.txt. Then why not
> doing one for ourselves?
My proposal here is to:
* Update www.gov.uk/humans.txt with a short message saying goodbye and
thank you
* Leave it up for about a day
* Revert this PR to set it back to the old version
I think this is a nice thing to do, and well within the intended purpose of
the humans.txt file - it's not going to affect any users of GOV.UK who
aren't looking for humans.
Thanks Issy - …

Say goodbye to Issy

---

app/views/layouts/govuk_template.html.erb

GOV.UK Frontend updated the crown SVG in the header component to use `aria-hidden="true"` instead of `role="presentation"` - see the commit https://github.com/alphagov/govuk-frontend/commit/7278efe3d085fab1b637c509cf9262e4d51a4b5d for more information.
This updates the header in static to do the same thing - `role="presentation"` has been removed and `aria-hidden="true"` has been added.

Crown in header updated to use aria-hidden="true"

---

public/humans.txt

We temporarily updated www.gov.uk/humans.txt to say goodbye to Issy. It shouldn't be a permanent feature though, otherwise it looks like a bit of an overreaction.
This reverts the commits that added the message, but leaves the one that removes the trailing full stop from the first sentence (as that's a small visual improvement we can keep).

Reset humans.txt

---

app/assets/stylesheets/helpers/_header.scss
app/views/root/_base.html.erb

Modify search toggle button to use button markup instead of an anchor tag, to more closely match the presentation and intended function of the element.
This is dependent on Javascript from `govuk_publishing_components`. The JS assumes that this button is an anchor tag and will throw an error if it cannot find a `href`. Therefore [this PR](https://github.com/alphagov/govuk_publishing_components/pull/1682) needs to go out first.

Mobile search toggle button

---

app/assets/javascripts/analytics/scroll-tracker.js

We need to know how many people view the "Additional help and support" section of the[ DIT landing page](https://www.gov.uk/eubusiness), and to do this we'll need some GA event tracking for scrolling on the page.
trello: https://trello.com/c/7BVy9uRt/433-dit-google-analytics-event-scroll-tracking

Add scroll-tracking to the DIT landing page

---

app/assets/stylesheets/helpers/_header.scss
app/views/root/proposition_menu.html.erb

- was formerly a link, which failed accessibility requirements because it behaved like a button
- uses existing JS for this (header-navigation.js, in govuk_publishing_components for reference, fact fans)
- copied and modified the styling from govuk-template (as it no longer applies) in order to preserve the look of the element exactly, CSS may therefore not be as nice as it could be, but this should all be replaced by the proper header at some point anyway
Should be no visual changes.
Trello card: https://trello.com/c/2bL11sIv/414-mobile-menu-button-looks-like-a-link
---
Interesting note - this code for the menu toggle is in `static` (obviously). The JS that controls it (and also the search toggle for mobile, just above it) is in `govuk_publishing_components`. The menu that appears when …

Make mobile menu toggle a button

---

app/assets/javascripts/analytics/init.js.erb

So that we can track journeys through the service.
[Trello card](https://trello.com/c/rnnkIpT5/55-shielded-vulnerable-people-service-start-page)

Add coronavirus-shielding-support.service.gov.uk

---

Rakefile
lib/tasks/testing.rake

Trello: https://trello.com/c/5Gob6WUL/147-for-everyone-ensure-that-rubocop-runs-as-part-of-bundle-exec-rake-as-one-of-the-default-tasks
We had expected that all apps were linting with the default rake task
and removed the linting step from the Jenkins library [1]. However it
seems this app was missed.
[1]: https://github.com/alphagov/govuk-jenkinslib/pull/74

Lint as part of the default rake task

---

app/assets/stylesheets/helpers/_header.scss
app/views/notifications/_global_bar.html.erb

Update the global bar to add the transition link and adjust design.
Requires https://github.com/alphagov/govuk_publishing_components/pull/1739 to be merged and static to be updated.
Required by design as per [Trello card](https://trello.com/c/vNG432Ms)
<table>
<tr><th>Before</th></tr>
<tr><td><img width="1439" alt="Screenshot 2020-10-16 at 15 53 12" src="https://user-images.githubusercontent.com/788096/96273944-d74d2d80-0fc7-11eb-9044-e579c155d951.png"></td></tr>
<tr><th>After</th></tr>
<tr><td><img width="1439" alt="Screenshot 2020-10-16 at 15 47 23" src="https://user-images.githubusercontent.com/788096/96273954-da481e00-0fc7-11eb-8602-897f60533601.png"></td></tr>
</table>
<table>
</td></tr>
</table>

Update global bar to add transition link

---

app/assets/stylesheets/header-footer-only.scss
app/assets/stylesheets/helpers/_header.scss
app/views/root/_base.html.erb

Use [existing search component](https://components.publishing.service.gov.uk/component-guide/search) to replace the hard coded site search in the header.
This is a step towards eliminating dependency on old styles and towards the "componentisation" of our frontend apps.
Cleaned up a good amount of CSS that is no longer in use thanks to using the component.  
https://trello.com/c/RbD3om74

Replace hard coded site search with search component

---

app/assets/javascripts/header-footer-only.js
app/assets/stylesheets/header-footer-only.scss
app/views/root/_base.html.erb

This snappy change adds main navigation for accounts to be used via [slimmer config](See https://github.com/alphagov/slimmer/pull/255).
Note this menu is not compatible with the search input. The search needs to be disabled when navigation is enabled otherwise they will visually clash.
This was tested locally in `finder-frontend` – since this is the primary usage – and will work for both `core_layout` and `header_footer_only` templates in static.
<table>
<tr><th>Signed in</th><th>Signed out</th></tr>
</td></tr>
</td></tr>
</table>
[Trello card](https://trello.com/c/vdZrgBRy)

Add main navigation for accounts

---

app/views/root/_base.html.erb

Forgot to output the Plek results 🤦

Fix account related URLs

---

app/assets/stylesheets/helpers/_header.scss

Recent changes to the global search input in static seem to have introduced an alignment issue on mobile.
Before | After
------------ | -------------

Fix mobile search toggle button positioning

---

app/views/notifications/_global_bar.html.erb

To reflect the new national restrictions in England which come into
force on 5 November.

Update coronavirus subtext in global banner

---

app/views/root/_account_navigation.html.erb
app/views/root/_base.html.erb
app/views/root/_error_page.html.erb

We're using slimmer to remove accounts links from the header, but the
error pages come straight from static and so don't go through slimmer.

Hide accounts links on error pages

---

app/assets/javascripts/libs/lux/lux.js

SpeedCurve lux.js was updated 2020-11-03. Release notes for this version:
> We have released v208 of lux.js. This is a bug fix release:
> - User timing marks in SPAs are now measured since the last LUX.init call. Previously they were measured since the beginning of the initial page load, causing user timing values in subsequent pages to be much higher than expected.
> - Fixed a bug where JavaScript page labels only work when the variable is defined before LUX is loaded.
> - Fixed a bug where SPAs that didn't set a page label would always use the initial document.title value as the page label. Now the page label is updated whenever document.title changes.

Update to version 208 of the lux library

---

app/views/root/_account_navigation.html.erb

(hopefully) fixes the mobile menu for accounts in the header.
- the UL that is supposed to appear when the button is clicked should have an ID matching the aria-controls attribute of the button, for the JS to work
- I've used two different IDs just in case slimmer has a problem with duplicates, although some kind of magic seems to be occurring here to make only one chunk of this markup render at any one time
Trello card: https://trello.com/c/ICDC0esK/368-accounts-snag-list-%F0%9F%8C%AD

Fix mobile menu for accounts

---

app/assets/javascripts/analytics/pii.js
spec/javascripts/analytics/pii.spec.js

The data in google analytics was not properly redacting longer postcodes
and was incorrectly redacting the names of a form.
To redact longer postcodes we've added an optional extra letter to the
end of the regex for the postcode.
To check for the form name the word refund has been ignored in the regex.
Trello card: https://trello.com/c/NFJQdJg4/2201-3-adjust-google-analytics-pii-filtering

Strip longer postcodes in Google analytics

---

app/assets/javascripts/analytics/init.js.erb

So we get cross domain tracking if users have consented.

Add accounts domain to cross domain linker

---

Dockerfile

This Dockerfile is only used in RAILS_ENV=production environments and doesn't have the system dependencies installed for other environments (and shouldn't have these unless they're used and thus tested). This change reflects this by changing the default RAILS_ENV to production and installing only the production gems.

Update Dockerfile to reflect it should only run in RAILS_ENV=production

---

app/views/root/_base.html.erb

Following renaming of the transition taxon, and site wide changes to use the more SEO friendly term 'Brexit transition', we should make the footer consistent.
[Trello](https://trello.com/c/ynxEAip9/616-update-the-transition-wording-on-the-govuk-homepage-and-govuk-footer)

Replace EU transition with Brexit transition in the footer

---

README.md
docs/humans.md
public/humans.txt

This also adds documentation to clarify when and how we can update
gov.uk/humans.txt in future.
If the documentation is proving controversial, I can raise a separate
PR for it, so it's not blocking this one.

Add some words about Mark McLeod

---

app/assets/javascripts/libs/lux/lux.js

Update lux.js Release notes from SpeedCurve:
> LUX update: lux.js v209
> We have released v209 of lux.js. This is a bug fix release:
> Fixed a bug where JavaScript page labels were being ignored in some cases.

Added latest version of lux.js (v209)

---

app/assets/javascripts/analytics/scroll-tracker.js
app/assets/javascripts/global-bar-init.js

- **Update the global-bar blocklist**
Update the `eubusiness` regex in the `global-bar-init.js` regex blocklist to match translation URLs as we prepare to rollout alphagov/collections#2134. By doing this we prevent the global bar banner from appearing on translation pages of the `/eubusiness` page (for example `/eubusiness.es`)
- **Update eubusiness heading copy**
It seems like the `scroll-tracker.js` script looks for hardcoded content at the bottom of the `/eubusiness` page, content that we update in alphagov/collections#2134.
[Trello card](https://trello.com/c/ZfMI7LNc)

Prepare static for a multilingual eubusiness page

---

app/assets/javascripts/surveys.js

Improves the accessibility of these links and makes their style consistent with the rest of GOV.UK.
<table>
</td></tr>
</table>

Fix anchor styles in survey script

---

app/assets/javascripts/libs/lux/lux.js

> LUX update: lux.js v210
> We have released a new version of lux.js. This release includes minor changes to the self-updating mechanism within lux.js.
This change is relevant to us. When we include the script we want to enable the simple beacon mode:
```
LUX = window.LUX || {};
LUX.beaconMode = "simple";
// at the same time: async load the lux.js script
```

Update to lux version 210

---

app/views/root/_account_navigation.html.erb

These are links to www.gov.uk, but we need to decorate them with the
cross-domain _ga param, as they may redirect to the accounts
domain (the redirect will preserve the param).
---
[Trello card](https://trello.com/c/ISYymNsg/426-fix-cross-domain-tracking-on-redirects)

Add data attributes to accounts links we need to decorate

---

app/views/root/502.html.erb

A recent incident reveals that we do not have a 502 error page, which means an unsightly nginx 404 is served when this error occurs.

Add 502 page

---

app/assets/javascripts/analytics/pii.js
spec/javascripts/analytics/pii.spec.js

Trello: https://trello.com/c/LiAOrW5F/1000-remove-or-redact-values-at-the-end-of-postcode-look-up-string-that-dont-match-postcode-format
This adds a new meta tag approach to stripping PII data from being sent
to analytics. This allows for particular query string parameters to be
redacted and for an application to specify them.
To use this an application should create a meta element of:
```
<meta name="govuk:static-analytics:strip-query-string-parameters"
content="param-1, param-2">
```
Where param-1, param-2 is a comma separated list of parameter names.
Formatting for this is inspired by `<meta name=keywords>`
Then when analytics data is sent to GA the strings are looked for a
match of the query string parameter and any found are replaced. To illustrate:
were a url of …

Allow stripping query string parameters from Analytics

---

app/views/root/_base.html.erb

To keep it 'in sync' with the contextual sidebar https://github.com/alphagov/govuk_publishing_components/pull/1851
[Trello card](https://trello.com/c/vFkN8alA)

Update brexit link copy in footer

---

Gemfile.lock

Reverts alphagov/static#2379
It seems to have caused an issue with the build:
> NoMethodError: undefined method `hour' for 1:Integer

Revert "Bump govuk_publishing_components from 23.10.1 to 23.12.1"

---

app/assets/stylesheets/header-footer-only.scss

Fix to resolve visual issue on `government-frontend` app within search input, adding support file directly to static so the search component pulls in correct mixin to calculate the height for an input field.
There was an issue highlighted with search [on this page ](https://www.gov.uk/guidance/access-the-public-register-for-environmental-information)which was related to a [search PR](https://github.com/alphagov/govuk_publishing_components/pull/1793)
A [PR](https://github.com/alphagov/government-frontend/pull/1950) was raised to fix this issue directly on `government-frontend` however it was highlighted this isn't quite the correct fix.   This PR adds the relevant file directly to static so the header + search element has the sass that it needs.
Before
After
There was some conversation …

Adding relevant sass for search component

---

Gemfile.lock
config/application.rb

Second attempt at merging #2379, this time with a fix for the build issue,
which I've verified works locally.
We have to `require "active_support/time"` to define the helper methods
we use to set the Cache-Control header in the [test][] and [development][]
environments.
I don't know why bumping the govuk_publishing_components gem from
v23.10.1 to v23.12.1 has caused this issue in both [Static][]
and [Feedback][] (nor why the tests passed on the PR and only
subsequently failed after merge).
Looking at the Gemfile.lock changes in Static (in
7c79e8dcdd22e88189700dcf8a1d99129532b603), there's no obvious
culprit there. I tried reverting the versions of all dependencies
except govuk_publishing_components, but the issue remained.
Looking at the [diff between the govuk_publishing_components gem …

Upgrade govuk_publishing_components (with build fix)

---

app/assets/javascripts/libs/lux/lux.js

Release notes from SpeedCurve:
> We have released v211 of lux.js. This is a bug fix release:
> Calling LUX.init() no longer causes all user timing marks & measures to be cleared.

Update to lux version 211

---

app/assets/javascripts/header-footer-only.js

Update component references following this change to correct component file names: https://github.com/alphagov/govuk_publishing_components/pull/1848

Use correct component references

---

app/controllers/icon_redirects_controller.rb
config/routes.rb
lib/tasks/publishing_api.rake
test/integration/icon_redirects_test.rb

- Set `cache-control` on asset redirects
- Extend the asset redirects based on recent log analysis
Recent log analysis revealed that we have some uncached redirects and 404s on apple-touch-icons requests. This change aims to prevent such request from reaching our servers by setting a cache-control in the redirects header that will be picked up by our CDN.
[Trello card](https://trello.com/c/hNHb5JS8); [Related Trello card](https://trello.com/c/CN2bhhZi)

Set cache control on asset redirects

---

lib/tasks/publishing_api.rake

The PublishingApiV2 namespace has been removed. I also simplified the Publishing API call since we can use the GdsApi.publishing_api method to access the adapter.

Correct outdated Gds API Adapters usage

---

app/views/root/_base.html.erb

VoiceOver reads out the "Sitewide" `aria-label` on the search form in a strange way. It seems that writing it as "Site-wide" helps VoiceOver read it out more clearly.
https://user-images.githubusercontent.com/7116819/104621026-8eb91500-5687-11eb-800e-59d546c5e8f9.mov
https://user-images.githubusercontent.com/7116819/104621049-95478c80-5687-11eb-89aa-07d07e4afe08.mov

Hyphenate the word "sitewide" on search form aria-label

---

app/views/root/400.html.erb
app/views/root/401.html.erb
app/views/root/403.html.erb
app/views/root/404.html.erb
app/views/root/405.html.erb
app/views/root/406.html.erb
app/views/root/410.html.erb
app/views/root/422.html.erb
app/views/root/429.html.erb
app/views/root/500.html.erb
app/views/root/501.html.erb
app/views/root/502.html.erb
app/views/root/503.html.erb
app/views/root/504.html.erb
app/views/root/_error_page.html.erb

Update the error pages layout to more closely match the Design system [pattern for error pages](https://design-system.service.gov.uk/patterns/page-not-found-pages/default/index.html) and amend some spacing issues.
There is now more space between the page header and the content, which were previously too close together on mobile. Additionally, the content is now inside a `two-thirds` column instead of running full-width.
https://trello.com/c/Mmv4gF5o
Before | After
------------ | -------------

Error template markup adjustments

---

app/views/layouts/govuk_template.html.erb

This switches the order of the cookie banner and the skip link
This follows the Design System guidance "Position the cookie banner after the opening <body> tag and before the ‘skip to main content’ link." and makes it more likely that users of assistive tech will encounter the cookie information.

Move skip link to after cookie banner

---

app/assets/stylesheets/helpers/_header.scss

We've used separate font properties for other areas of GOV.UK. This PR updates to use the same method for consistency, and removed "GDS Transport" from the font stack since we aren't currently using v2 of the font on GOV.UK.

Split the font property into separate properties for consistency

---

app/views/notifications/_global_bar.html.erb

It's possible that we might want to show only one of the Brexit/Covid links that are on the global bar.
This PR allows this and makes the margin underneath the upper link dependent on whether there is anything below it.

Allow showing individual global bar links

---

app/views/root/_base.html.erb

The button text for the search button in the header has been changed from "Search" to the more specific "Search GOV.UK".
The default text for the button in the sarch component is "Search" - this means that multiple forms can have the same submit text. This can cause confusion when navigating out of context - for example, a screenreader will pull out all of the interactive elements on a page and list them without the surrounding information.

Update header search button text

---

README.md
app/assets/javascripts/application.js
app/assets/stylesheets/application-print.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/error-page-print.scss
app/assets/stylesheets/error-page.scss
app/controllers/root_controller.rb
app/views/root/400.html.erb
app/views/root/401.html.erb
app/views/root/403.html.erb
app/views/root/404.html.erb
app/views/root/405.html.erb
app/views/root/406.html.erb
app/views/root/410.html.erb
app/views/root/422.html.erb
app/views/root/429.html.erb
app/views/root/500.html.erb
app/views/root/501.html.erb
app/views/root/502.html.erb
app/views/root/503.html.erb
app/views/root/504.html.erb
app/views/root/_error_page.html.erb
app/views/root/scheduled_maintenance.html.erb
test/integration/templates/error_4xx_test.rb
test/integration/templates/error_5xx_test.rb

* The base error page template has been updated to use the public layout component
* Application stylesheet has been updated to include only the styles needed  for the public layout component, global bar, and emergency banner
* Application JavaScript has been updated to only include the modules needed for the public layout component
* Error page stylesheet has only the extra imports needed - in this case, only the the title component was needed
* Minor tweak to make the apostrophe in the "We're" on some of the error pages look nicer
* Fixes a minor bug where the heading styles weren't being included, so the `h1` on the error page was using the default browser font size for `h1`s.
Adding a template to static that uses the public layout component meant updating these error pages first, …

Update error pages to use public layout template

---

app/views/root/_base.html.erb

[A part of this trello ticket](https://trello.com/c/43FM4pwv/673-switch-to-the-new-sign-in-out-endpoints)
A part of the work to broaden the transition checker login prototype to
the whole of GOV.UK. As outlined in [RFC#134][1] we are moving sign in
and sign out paths from being nested in finder-frontend (which would be
strange for a GOV.UK-wide login!) onto their own paths.
See the RFC for more detail on these two paths:
- [Sign in][2]
- [Sign out][3]
[1]: https://github.com/alphagov/govuk-rfcs/pull/134
[2]: https://github.com/alphagov/govuk-rfcs/pull/134/files#diff-f5a6037308ea735f2a6e63b3080e78792499608bcad7386a49cf94799634d1beR224
[3]: https://github.com/alphagov/govuk-rfcs/pull/134/files#diff-f5a6037308ea735f2a6e63b3080e78792499608bcad7386a49cf94799634d1beR243

Change Sign in and Sign out paths

---

app/views/components/_global_bar.html.erb

We are adding a new global banner.
This hides the Brexit link to reduce the size of the global banner.
https://docs.publishing.service.gov.uk/manual/emergency-publishing.html#2-hide-the-brexit-link-from-the-global-bar

Hide Brexit global bar

---

app/assets/stylesheets/components/_emergency-banner.scss
app/views/components/_emergency_banner.html.erb

This code was recently moved and had two CSS classes added which cause the link and summary of the banner to appear black and blue. Removing these classes makes the text appear white, which is the required behaviour.

Change CSS on sitewide banner

---

app/views/components/_emergency_banner.html.erb

Stop the emergency banner from appearing when a page is being printed.
Note - whilst the `dont-print` class works and is fine, the preferred `govuk-!-display-none-print` class from GOV.UK Frontend doesn't work because it's imported into a stylesheet with the media set to screen.
The other banners - cookie, Brexit, and COVID - don't appear when printed. This brings consistency to the behaviour of the banners on the site.
| Print preview before | Print preview after |
| -- | -- |
| ![Screenshot 2021-04-15 at 13 57 54](https://user-images.githubusercontent.com/1732331/114872954-b63c8c80-9df2-11eb-9043-f786d943a690.png) | ![image](https://user-images.githubusercontent.com/1732331/114872892-a58c1680-9df2-11eb-8263-c29ade2c3bf0.png) |

Hide the emergency banner when a page is printed

---

app/assets/stylesheets/header-footer-only.scss
app/assets/stylesheets/helpers/_header.scss

These temporary overrides don't have any effect now, so we can remove them. All these declarations end up overridden in production because of additional style added to the layout_header in govuk_publishing_components.

Remove header overrides

---

app/assets/javascripts/libs/lux/lux.js

Thu 29 Apr
We have released v213 of lux.js. This release contains bug fixes and other improvements:
- Long tasks are now buffered, enabling LUX to instrument long tasks that occurred before the snippet.
- User interaction times in a SPA are now relative to the most recent LUX.init call, rather than relative to navigationStart.
- Element identifiers for user interaction (click, keypress) have been improved. Buttons and links that don't have an id attribute will use their text content as the identifier.

Added v213 of lux.js

---

app/assets/javascripts/global-bar-init.js
app/views/components/_global_bar.html.erb
app/views/root/_base.html.erb

www.gov.uk/transition is now www.gov.uk/brexit
https://trello.com/c/wxR5o06H/1539-implement-brexit-landing-page-url-change

Rename /transition to /brexit

---

app/views/layouts/govuk_template.html.erb

This is causing some users issues when using "Find in page" due to [a bug in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1192487&q=gov.uk&can=1).

Move Martha

---

app/views/root/_error_page.html.erb
app/views/root/_gem_base.html.erb

Update the `gem_layout` to be able to set the header logo link depending on the what's been set in the environment.
So that the `gem_layout` template has feature parity with the `core_layout` template.
None.

Update header logo link

---

app/views/root/_base.html.erb
app/views/root/_gem_base.html.erb

Update the Account sign in / sign out / account links in the header section of the `gem_layout` template to match the links in `core_layout` template.
The links weren't updated when `core_layout` was updated.
None.

Update Account links in the `gem_layout` template

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_survey.scss
docs/slimmer_templates.md

Adds to the `gem_layout` template, as the styles were missing but the ability to show surveys was not.
The survey banner was being shown without any styles and looked quite broken.
Before:
After:

Add and update survey styles to gem layout template

---

app/assets/stylesheets/application.scss

Apply's the feature flag for new link styles from the latest release of GOV.UK Frontend
For the new gem layout, the component styles in static are overriding a few things across govuk apps. This has meant that apps that are currently set to use the new link styles and the gem layout are using mixed link styles. This ensure that we are using the new link styles everywhere.

Add feature flag for new link styles

---

app/views/root/_base.html.erb

Adds data attributes for analytics tracking the search button on the govuk_template based header.
Depends on https://github.com/alphagov/govuk_publishing_components/pull/2110
As part of gathering some baseline data ahead of updating the header design.
None
[Trello](https://trello.com/c/CwPwNE60/321-implement-analytics-tracking-on-the-existing-headers)

Add data attributes for click event to track search submit

---

app/assets/javascripts/global-bar-init.js

The Accounts team are moving the account homepage to the `frontend` app, with the plan of transitioning other parts of the account manager to be rendered by `frontend`, as we retire the `govuk-account-manager-prototype` app. 
Seeing as the `frontend` app uses `static`, the global bar (currently Coronavirus bar) is automatically added to the new `/account/home` page. The design for the account manager excludes this additional bar currently.
This adds paths beginning with `/account/` (assuming that any future account-related pages will live under `/account`) to the `urlBlockList` in the global bar script.
------
https://trello.com/c/lIDQNATi/813-implement-the-govuk-account-home-page

Add account pages to global bar BlockList

---

app/views/root/_gem_base.html.erb

Adds in the emergency banner helper into the `gem_layout` template
So that the emergency banner can be deployed successfully to frontend applications that are using the `gem_layout` template
Homepage (frontend) before:
Homepage (frontend) after:
Browse (collections) before:
Browse (collections after:

Add emergency banner helper to gem_layout

---

app/assets/javascripts/surveys.js

Set a "govuk-width-container" to make sure the content of the banner doesn't go full-width.
The change was tested with both `core_layout` (see `smart-answer` example below) and `gem_layout` (with [`collections`](https://github.com/alphagov/collections/pull/2446))
<table>
</td></tr>
</table>
[Trello card](https://trello.com/c/qQ5Je6n4)

Fix survey banner layout

---

app/controllers/root_controller.rb
app/views/root/_gem_base.html.erb
app/views/root/gem_layout_account.html.erb
docs/slimmer_templates.md

The Accounts team are [in the process of](https://github.com/alphagov/frontend/compare/msw/account-home-page) moving over some of the account pages to the `frontend` app. 
Since `frontend` app uses `static`, and certain aspects of the account manager template differ greatly from the default `gem_layout`, this warrants the introduction of a new template for use on accounts related pages (thanks @injms for suggesting this approach).
Some main differences are:
- the Account home link in the header should link to the account homepage (as opposed to linking to the GOVUK homepage)
- the Account product name should be present in the header
- there should be an account nav in the header
- the feedback component at the bottom of the page should be hidden as the account has its own version of a …

Add gem layout template variation for accounts

---

app/views/layouts/_header.html.erb
app/views/root/_base.html.erb
app/views/root/_gem_base.html.erb
app/views/root/core_layout_explore_header.html.erb
app/views/root/gem_layout_explore_header.html.erb
app/views/root/header_footer_only_explore_header.html.erb

This will allow us to switch between the current header menu and the newer design that we want to AB test with. This means that frontend apps using the AB Test gem can request a different template via Slimmer.
See https://github.com/alphagov/government-frontend/pull/2156 for example
Trello https://trello.com/c/LUhrajXF/323-prepare-the-new-menu-a-b-test-for-sections-of-govuk

Add explore_header templates

---

app/assets/javascripts/surveys.js
spec/javascripts/surveys.spec.js

Disable the survey prompt for pages under `/account`. 
One reason for this is that there are already other prompts for feedback on all account pages. Having yet another one adds unnecessary noise. 
Another reason is to keep `gov.uk/account/home` (rendered by `frontend`) consistent with the other account pages which are currently still rendered with the `govuk-account-manager-prototype` app, and do not use the user satisfaction survey.

Add account pages to global survey blocklist

---

app/views/root/_base.html.erb
app/views/root/_gem_base.html.erb
app/views/root/gem_layout_account.html.erb

We are moving the account homepage to `gov.uk/account/home`. 
This updates the `href` for the header nav links which used to point to `account.publishing.service.gov.uk`, to now point to `gov.uk/account/home` instead.

Update header links href to new account manager home

---

app/views/components/_global_bar.html.erb

Trello: https://trello.com/c/R2SasXMA/503-govuk-sitewide-banner-text-change
Not to be deployed until the government guidance changes on the 19th July
Before:
After:

Coronavirus banner to no longer reference "rules"

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/controllers/root_controller.rb
app/views/root/gem_layout_full_width_explore_header.html.erb

For the apps that are on the gem based public_layout template (currently Frontend and Collections) we need to be able to specify which header we want to show the user. Accompanying PR here for the Explore Super Menu being added to the gem is https://github.com/alphagov/govuk_publishing_components/pull/2179/
Trello https://trello.com/c/fYNA3mnu/390-prep-ab-test-for-frontend-and-collections

Add explore header templates for public_layout in gem

---

app/assets/stylesheets/application-print.scss

There was some refactoring to remove `display: none` rules from component stylesheets in favour of using the `govuk-!-display-none-print` class instead: https://github.com/alphagov/govuk_publishing_components/pull/1561
As a consequence of this, some of the component print stylesheets which previously used to contain CSS are now empty files. This removes references to these files from the application print stylesheet.
Relevant issue: https://github.com/alphagov/govuk_publishing_components/issues/2065

Remove import of empty stylesheets

---

app/assets/stylesheets/header-footer-only.scss

The search component use to make use of this mixin, but it was [later updated to use `govuk-em()`](https://github.com/alphagov/govuk_publishing_components/pull/2034) via `govuk-frontend` so it's no longer needed by `static`.

Remove `em()` mixin import

---

app/views/root/gem_layout_no_feedback_form.html.erb
app/views/root/gem_layout_no_footer_navigation.html.erb

- Add `gem_layout_no_feedback_form` template [for `feedback` to use the new layout](alphagov/feedback#1266)
- Add `gem_layout_no_footer_navigation` template [for `service-manual-frontend` to use the new layout](https://github.com/alphagov/service-manual-frontend/pull/960) (in a subsequent PR `without_footer_links` template will be removed)
This PR currently fails tests as it awaits for https://github.com/alphagov/govuk_publishing_components/pull/2218 to be released.

Add `gem_layout` variations

---

app/views/root/_base.html.erb

Convert the search button seen on menu's with navigation on gov.uk ([example](https://www.gov.uk/government/publications/school-inspections-a-guide-for-parents)) to an `a` tag by default.
Currently, when js is turned off for pages with this menu, the search button doesn't do anything. This ensures that it's default state is a link, making it interactable regardless of js.
Cannot be merged until https://github.com/alphagov/govuk_publishing_components/pull/2235 has been merged and deployed.
No visual changes
[Card](https://trello.com/c/8unZtntm/341-fix-the-search-link-in-the-no-js-mobile-version-of-the-old-menu-bar)

Convert the search button to be a link by default

---

app/assets/javascripts/application.js

Remove redundant `govuk_publishing_components/lib/header-navigation` import
`header-navigation` is already required and executed by all public-facing applications as part of `govuk_publishing_components/lib`. Given `header-navigation` is not an actual module, but a IIFE relict from `govuk_template`, this duplication results in two toggle-like events being attached to the same button, which causes the search button to open and close itself in one click
Note

Remove redundant JavaScript import

---

app/controllers/root_controller.rb
app/views/root/_gem_base.html.erb
app/views/root/gem_layout_account_manager.html.erb
docs/slimmer_templates.md

This adds a new account-related template, intended to be used on pages that should have the account layout, while not being rendered by the `govuk-account-manager-prototype` app.
An example of such a page is the `gov.uk/account/home` page which was relocated from the account manager app to the `frontend` app, which at that time meant that some of the content and page furniture was duplicated between those applications.
More recently, the accounts team are working towards the goal of single page notifications which will enable users who have linked their email notifications address and their GOVUK Account to manage their email subscriptions through their account.
Part of this work is making the email management pages (which live in `email-alert-frontend`) look the same as the account …

Add new layout template for account-like pages

---

app/views/root/_base.html.erb
app/views/root/proposition_menu.html.erb

The Search and Menu buttons in mobile view for the older "proposition" menu used in government-frontend for Whitehall style templates needs this attribute for tracking.
https://trello.com/c/2Jv5BrTu

Add data-toggle-name to old buttons

---

app/assets/stylesheets/application.scss
app/views/root/_gem_base.html.erb

A `draft` class is used to apply a watermark when previewing documents in publishing applications. A smokey test is currently failing as this class is missing in applications using the new `gem_layout`.
<table>
</td></tr>
</table>

Enable draft on public layout

---

app/controllers/root_controller.rb
app/views/root/gem_layout_account.html.erb
docs/slimmer_templates.md

The introduction of `gem_layout_account_manager` [here](https://github.com/alphagov/static/pull/2571) has rendered `gem_layout_account` redundant.
While `gem_layout_account` primarily just swapped the GOVUK layout header for the Account one, `gem_layout_account_manager` goes one step further and includes the account alpha banner, account nav and feedback footer, and other related account-y elements.
The reason `gem_layout_account` could not be deleted immediately was that it was still being used for the account home page on the frontend app.
Now since that page [has also been switched over to the `gem_layout_account_manager` template](https://github.com/alphagov/frontend/pull/2907), the older template can be removed.

Remove old `gem_layout_account` template

---

app/controllers/root_controller.rb
app/views/root/gem_layout_account_manager.html.erb
app/views/root/gem_layout_full_width_old_header.html.erb
app/views/root/gem_layout_old_header.html.erb
app/views/root/header_footer_only_old_header.html.erb

These are being added as an interim step before we set the Explore Super Menu Header to be the default. We need the old header to ensure we keep Account links in place.

Add templates with old style header

---

app/controllers/root_controller.rb
app/views/layouts/_header.html.erb
app/views/root/_gem_base.html.erb
app/views/root/core_layout.html.erb
app/views/root/core_layout_explore_header.html.erb
app/views/root/gem_layout_account_manager.html.erb
app/views/root/gem_layout_explore_header.html.erb
app/views/root/gem_layout_full_width.html.erb
app/views/root/gem_layout_full_width_explore_header.html.erb
app/views/root/gem_layout_old_header_full_width.html.erb
test/integration/templates/header_footer_only_test.rb

Updates both the gem layout and the core layout templates to use the new navigation header as the default.
Turns the navigation header off for the account manager template.
Adds a layout with the previous header.
Card: https://trello.com/c/3Vu0IPhG
...
Gem layout:
| Before | After |
| - | - |
| ![image](https://user-images.githubusercontent.com/1732331/133446231-86f6f23c-881d-4ff1-acad-2e7678737141.png) | ![image](https://user-images.githubusercontent.com/1732331/133445795-f2a1d4a9-13e2-42a8-8d87-886a34a0fc58.png) |
Layout with previous header:

Set the navigation header as default

---

app/views/layouts/_header.html.erb
app/views/root/_gem_base.html.erb
app/views/root/gem_layout_explore_header.html.erb
app/views/root/gem_layout_full_width_explore_header.html.erb
test/integration/templates/header_footer_only_test.rb

Temporarily turn the new menu bar header off (back to it's previous A/B configuration) as it was deployed ahead of schedule and broke a high profile page https://www.gov.uk/transition-check/questions

Temporarily turn super navigation off

---

app/views/layouts/_header.html.erb
app/views/root/_base.html.erb
app/views/root/_gem_base.html.erb
app/views/root/gem_layout_explore_header.html.erb
app/views/root/gem_layout_full_width_explore_header.html.erb
app/views/root/header_footer_only_old_header.html.erb
test/integration/templates/header_footer_only_test.rb

Turns the [navigation header][nh] on for all visitors; updates the logic so that pages that need the GOV.UK Accounts links won't see the navigation header ([gov.uk/brexit][1], [gov.uk/transition-check/questions][2]).
Also reverts alphagov/static#2598
Replaces https://github.com/alphagov/static/pull/2601
Dependent on:
- https://github.com/alphagov/government-frontend/pull/2231
- https://github.com/alphagov/whitehall/pull/6307
- https://github.com/alphagov/finder-frontend/pull/2641
- https://github.com/alphagov/govuk-search-relevance-tool/pull/87
The navigation header was A/B tested, and found to be an improvement on the existing headers - so it should be turned on for all users.
[1]: https://www.gov.uk/brexit
[2]: https://www.gov.uk/transition-check/questions
[nh]: …

Make navigation header the default header

---

app/assets/stylesheets/application-print.scss

Adds the print stylesheet for the navigation header
The navigation header has a print stylesheet, so it should be used. Currently  the print stylesheet stops the navigation header from being printed as it takes up too much space and isn't that useful.
| Browser | Before | After |
| - | ------ | ----- 
| Firefox | <img width="823" alt="" src="https://user-images.githubusercontent.com/1732331/141108960-b0737723-ebfc-4be6-b054-e493c7aae006.png"> | <img width="825" alt="" src="https://user-images.githubusercontent.com/1732331/141108957-310a36e1-f0b0-4db6-86a6-718789190eca.png"> |
| Chrome | <img width="582" alt="" src="https://user-images.githubusercontent.com/1732331/141109322-50a352e8-ba07-4e4f-bc16-c2f2610b034e.png"> | <img width="584" alt="" …

Add print stylesheet for navigation header

---

app/views/components/_global_bar.html.erb

This hasn't been visible for a long time, so it should be safe to remove.
Related: https://github.com/alphagov/govuk-developer-docs/pull/3293

Remove Brexit link from global banner

---

app/controllers/root_controller.rb
app/views/root/_account.html.erb
app/views/root/_gem_base.html.erb
app/views/root/gem_layout_account_manager_manage_your_account_active.html.erb
docs/slimmer_templates.md

When the account layout template renders with a nav, the "Your account" nav option is selected by default.
Some pages which use the account layout belong under "Manage your account" instead of "Your account".
This allows us the option to render the account layout with "Manage your account" selected/active in the account nav, instead of the default "Your account".
This also ensures the **Account** link in the site header nav appears with the correct **active** blue colour (currently there is no visual difference between the **Account** link and the **Sign out** one)
------
https://trello.com/c/uDkZ90GE

Add support for "Manage your account" active in the account nav

---

app/controllers/root_controller.rb
app/views/root/gem_layout_full_width_old_header.html.erb
app/views/root/gem_layout_old_header.html.erb
app/views/root/gem_layout_old_header_full_width.html.erb

It seems that these templates were introduced solely for pages which
still used the old layout header while the explore nav was being rolled
out to the rest of the site.
There no longer are any references to these templates so I believe they
can safely be removed.
https://trello.com/c/buf41APG/24-tidy-up-layout-templates-in-static

Clean up: unused templates

---

app/views/root/gem_layout_no_footer_navigation.html.erb

As this is affecting Service Manual, which shouldn't be showing the Super Header.
(The Service Manual is the only app using the `gem_layout_no_footer_navigation` template)
[Trello card](https://trello.com/c/7xbAX1Uk/711-bug-fix-service-manual-header)
* https://github.com/alphagov/service-manual-frontend/pull/1021
* https://github.com/alphagov/govuk_publishing_components/pull/2521

Edit gem_layout_no_footer_navigation to not show Explore header

---

app/assets/stylesheets/application.scss

Missed in https://github.com/alphagov/static/pull/2680
<table>
</td></tr>
</table

Add missing textarea styles for the feedback component

---

app/assets/javascripts/modules/cross-domain-tracking.js
spec/javascripts/modules/cross-domain-tracking.spec.js

Removes jQuery from the cross domain tracking script, and updates the code to use the GOVUK Frontend standard for module structure i.e. from a `start` to an `init` structure.
We're removing jQuery from GOV.UK.
None.
Trello card: https://trello.com/c/SaxK0Gfc/523-remove-jquery-from-static

Remove jQuery from cross domain tracking

---

spec/javascripts/surveys.spec.js

Fix two intermittently failing tests and re-enable and fix two disabled (and also intermittently failing) tests.
Two of the survey JavaScript tests have been failing intermittently. This seems to have been caused by the state of the `surveyExpanded` attribute within the surveys code. This attribute is set correctly or incorrectly by other tests, so the failure would occur depending on the order the tests are run.
Specifically, this occurs in the `if` statement on line 244, where matching the `if` instead of the `else` can fire the wrong tracking event. The solution is to manually set this attribute to the expected value in the failing tests.
Issue noted in issue https://github.com/alphagov/govuk_publishing_components/issues/2524
Once enabled, these tests were also failing intermittently, …

Fix intermittent test failures in surveys

---

app/assets/javascripts/modules/global-bar.js
spec/javascripts/modules/global-bar.spec.js

Removes jQuery from the global bar script, and updates the code to use the GOVUK Frontend standard for module structure i.e. from a `start` to an `init` structure.
We're removing jQuery from GOV.UK.
None.
Trello card: https://trello.com/c/SaxK0Gfc/523-remove-jquery-from-static

Remove jQuery from globalbar

---

app/assets/javascripts/surveys.js
spec/javascripts/support/jasmine.yml
spec/javascripts/surveys.spec.js
spec/javascripts/vendor/mock-ajax.js

Remove jQuery from the JavaScript that creates and manages the surveys code.
This code is quite long and complex but there's some [good documentation](https://github.com/alphagov/static/blob/main/docs/surveys.md) available, which includes details of when surveys appear and how to test them. I've run this locally and it all seems to behave as it does on live, but I'm keen to get it on integration or staging to give it a proper look.
We're removing jQuery from GOV.UK.
None.
Trello card: https://trello.com/c/SaxK0Gfc/523-remove-jquery-from-static

Remove jQuery from surveys code

---

app/assets/javascripts/application.js

Fix the analytics pageviews not firing on GOV.UK's 404 page, by including the `trigger-event.js` script in `static`, from the components gem.
- this script is called by the cookie banner code in `setCookieConsent`, which is included in static as part of the cookies/analytics code for GOV.UK
- without it, cookie consent doesn't appear to be set correctly, resulting in a console error complaining about the trigger event script missing if you try to consent to cookies on the 404 page (which comes from static)
- oddly, once you have consented to cookies no further errors appear, but the analytics pageview for the 404 page doesn't appear to work
- adding the trigger event script like this should fix analytics on the 404 page, which are currently not working properly
Without the script, this is …

Include trigger event script from gem

---

app/assets/javascripts/global-bar-init.js

Checking for duplicated cookie is no longer needed as the old `global_bar_seen` cookie has expired. Fixes #2036

Revert #2034

---

Gemfile
Gemfile.lock
app/views/root/_gem_base.html.erb
test/integration/google_tag_manager_component_test.rb

We want to test out our configuration of GTM and implementation of Ga4 tracking. We are going to do this in integration only at this stage. The env vars required to render the GTM component have been made available to government frontend on integration only, see https://github.com/alphagov/govuk-puppet/pull/11550
Trello: https://trello.com/c/0yzp3M2T/785-ga4-conditionally-add-the-gtm-component-to-static-templates

Conditionally add the GTM component

---

app/assets/javascripts/application.js

Add `skip-link` script
`govuk_publishing_components` v28.6 (https://github.com/alphagov/static/pull/2712) brings in a `skip-link` script that needs to be imported by `static`
From [govuk-frontend v4.0.0 release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v4.0.0):
> We've added JavaScript for the skip link component to set focus to the linked element, for example, the main content on the page. This helps screen readers read the linked content when users use the skip link component.

Add `skip-link` script

---

app/views/root/_error_page.html.erb
test/integration/templates/error_4xx_test.rb
test/integration/templates/error_5xx_test.rb

Remove the Coronavirus link on all 4xx and 5xx error pages.
We are removing all signposting to Coronavirus across GOV.UK.
| Before | After |
|---|---|
|![Screenshot 2022-03-29 at 17 09 19](https://user-images.githubusercontent.com/44037625/160656978-a9863412-9ec5-4859-b401-73217e7c5c33.png)|![Screenshot 2022-03-29 at 17 08 51](https://user-images.githubusercontent.com/44037625/160657043-5667aae7-bce8-401c-a423-81c70c2cf8b3.png)|
[Trello](https://trello.com/c/jbSGY1lk/798-placeholder-remove-coronavirus-link-on-404-message-due-4th-april)

Remove all Coronavirus links on 4xx and 5xx error pages

---

test/integration/templates/error_4xx_test.rb
test/integration/templates/error_5xx_test.rb

What
Tests were introduced as part of [this PR](https://github.com/alphagov/static/pull/2736) to ensure the Covonavirus link had been removed from the 4xx and 5xx error pages.
These should be removed.
Why
Once the above PR is merged and we are happy that these links are fully removed, we should remove these tests as they no longer add value.
[Trello](https://trello.com/c/MnEEQiWI/835-placeholder-remove-coronavirus-error-page-tests)

Remove Coronavirus error page tests

---

app/controllers/root_controller.rb
app/views/root/gem_layout_full_width_no_footer_navigation.html.erb

Add a layout `gem_layout_full_width_no_footer_navigation ` to be used for both [The Service Manual](https://www.gov.uk/service-manual) and the [Service Toolkit](https://www.gov.uk/service-toolkit) pages.
A variation is needed to remove the blue border (`full_width: true`) but with the settings currently used for both The Service Manual and the Service Toolkit pages. No variation currently exists for the following configuration:
```
full_width: true,
omit_footer_navigation: true,
show_explore_header: false
```
https://github.com/alphagov/service-manual-frontend/pull/1080

Add template - "full_width" and "omit_footer_navigation"

---

app/views/root/_account.html.erb
app/views/root/_gem_base.html.erb

This change makes it so that by default user_satisfaction_survey is **not** enabled in gem_base. Request was made that the user satisfaction survey be disabled for now as it was clashing with intervention banner and some of our new templates. After some exploring, I found that it has been set to appear on gem_base.html.erb by default. As a several apps use gem_layout.html.erb which uses the gem_base partial, I thought the least disruptive way to implement this change would be to change the default behaviour from always on to always off.  It will likely return in a redesigned form at some point in the future at which point this default behaviour can be changed back (or if is desired it could be only enabled on specific frontend apps instead of all frontend apps).
[Relevant Trello Card With …

Change behaviour so that `user_satisfaction_survey` is disabled by default in `gem_base` template

---

app/assets/javascripts/analytics.js.erb

Include new Google Tag Manager code from the gem. Note that this PR will need a new version of the gem with [this change](https://github.com/alphagov/govuk_publishing_components/pull/2760).
- if the environment variables are set (should only be set on integration) then pull in the new Google Tag Manager code from the gem
- this will allow us to test click tracking on some elements
We want to start testing this.
None.
Trello card: https://trello.com/c/V0RFrSMK/43-test-technical-approach-to-tracking-on-tabs-and-accordions

Conditionally add GA4 code from gem

---

app/assets/javascripts/application.js
app/assets/stylesheets/application-print.scss
app/assets/stylesheets/application.scss

Adds some warnings to the main stylesheet, print stylesheet and JS file.
To use a component in an application, the application must import any assets the component needs (stylesheet, print stylesheet, JavaScript). Anything `static` has is also included, so we don't need to duplicate assets between `static` and an application.
For example, the feedback component is included by `static` and depends upon the input component, so `static` needs to have the assets for both feedback and input. This means that any applications that use the input component don't need to include the assets for input, because they're already included by `static`.
In the future, if for some reason we removed the feedback component, and took the assets for feedback and input out of `static` without realising that …

Add warnings

---

app/views/root/_error_page.html.erb

Make page views for the new analytics code work on the error pages (404, 500, etc.)
- error pages use a different template from the rest of the site, GTM code wasn't included here so wasn't working
- note that this will be a temporary measure for GTM init until we've integrated it into the cookie consent
Really important to know when people hit error pages.
None.
Trello card: https://trello.com/c/5forgWxL/338-page-views-dont-work-on-error-pages

Make GA4 analytics page views work on error pages

---

app/assets/stylesheets/application.scss

Removes the action link stylesheet.
Partner to https://github.com/alphagov/collections/pull/2847.
The action link is now only being used in the collections app - so can be removed from static. This will prevent some unnecessary CSS from being served to users, as Static serves a stylesheet on every page across GOV.UK
None.

Removes action link stylesheet

---

app/views/root/_gem_base.html.erb

The account team are changing some details about how you navigate between the account and services, ahead of onboarding the LITE service.
**Don't merge this one yet** as it has to go out at the same time as some changes on DI AUTH side.
https://govukverify.atlassian.net/browse/GUA-224

GUA-222 Update text for the account link in the header

---

test/integration/templates/gem_layout_test.rb

[Trello card](https://trello.com/c/XDLC291t/2948-write-test-for-static-to-go-hand-in-hand-with-smokey-3)
This imports a test from Smokey[^1][^2] that confirms that the feedback component is present & functional.
The Smokey test does not currently meet the eligibility criteria for inclusion in the repository[^3], but by adding this test to Static we can meet the "Second critical functional check" criterion.
n.b. I'm new to GDS, so please do look over it critically and let me know if I've made any mistakes 🙏
[^1]: https://github.com/alphagov/smokey/blob/main/features/apps/static.feature
[^2]: https://github.com/alphagov/smokey/blob/main/features/step_definitions/feedback_steps.rb
[^3]: https://github.com/alphagov/smokey/blob/main/docs/writing-tests.md

Test that gem_layout renders feedback component

---

app/controllers/icon_redirects_controller.rb

In rails 7 redirects to other hosts are no longer permitted by default
and ActionController::Redirecting::UnsafeRedirectError was raised.
However in all those cases we are redirect to other GOV.UK domains such as
assets.gov.uk
Tested in staging

Explicitly allow redirects to other hosts within gov.uk domain

---

Dockerfile

Updating base image to use a new base and builder image. 
New Images are based on Ruby built from source on top of [Minideb](https://github.com/bitnami/minideb)
Base image repo, for more info:
https://github.com/alphagov/govuk-ruby-images
Further details:
https://trello.com/c/Zy0fd25w/970-use-base-builder-images-in-all-the-app-dockerfiles

Update to use new Minideb Ruby base image

---

app/views/root/gem_layout_account_manager.html.erb
app/views/root/gem_layout_account_manager_no_nav.html.erb

https://github.com/alphagov/static/pull/2808 accidentally reintroduced the left hand side account nav on Manage your GOVUK email subscriptions 🤦🏻‍♀️

"Omit account navigation" should be true on the account layout templates

---

config/environments/development.rb
config/environments/production.rb

This environment env var isn't being used in our infrastructure to set asset host as ASSET_HOST is always set and takes precedence. Neither is it used in our Heroku preview apps nor for local development (govuk-docker and ./startup.sh). This cleans up the codebase and removes confusion around which environment variables should be set.

Prevent GOVUK_ASSET_HOST from setting the asset host

---

app/views/components/_emergency_banner.html.erb

Currently, `govuk-grid-column-two-thirds` knocks the 'II' onto a second line for the Queens death emergency banner. Using three thirds keeps all the text on a single line for larger screens.

Use a wider div to wrap banner text

---

app/views/components/_emergency_banner.html.erb

The top banner also has role=banner, so we're
marking this one with an aria-labelled-by attribute instead
and using `section`, which has the same semantics as `<div role="region">`

Avoid 2 banner roles on the same page

---

app/controllers/root_controller.rb
app/views/root/_gem_base.html.erb
app/views/root/gem_layout_no_emergency_banner.html.erb

A new template which does not display the emergency banner, even when it is active.
For the Queen topical page, it was requested that the emergency be removed as it creates a circular journey and pushes content down. This is because the emergency banner has a link to the page that it appears on. The addition of this template will prevent this happening in the future.

New Template with No Emergency Banner

---

app/assets/javascripts/analytics.js.erb

Allow the use of Google Tag in place of Google Tag Manager.
- modify the GA4 code to check for the existence of a gtag environment variable alongside the existing code to check for a GTM env var
- if the gtag env var is found, this will be used in preference to GTM by the code called in the components gem from window.GOVUK.analyticsGA4.init()
- otherwise will default back to GTM for all environments, or simply do nothing if no GTM or gtag env vars are found
We want to test Gtag on integration and this allows us to do it without breaking things on other environments. Related to: https://github.com/alphagov/govuk_publishing_components/pull/2979
None.
Trello card: https://trello.com/c/Oo0T8ZCa/178-spike-into-back-out-plan-from-gtm-to-gtag

Look for gtag env var

---

app/assets/javascripts/analytics.js.erb

Get the version of the components gem and store it in the `window.GOVUK.analyticsGA4.vars` object, for later reference in the analytics code in the components gem.
- needed for the GA4 analytics code
- this was being created in the components gem, but that meant including a .js.erb file there, which we're trying to move away from
- instead, include it here, so we reduce the number of .js.erb files and deal with this later
Related change: https://github.com/alphagov/govuk_publishing_components/pull/2984
Using `.js.erb` files is apparently deprecated, so we're trying to avoid using them. This removes the `.js.erb` file in the gem (well, renames it back to `.js`) and moves the code here, so at least it's all in one place and we can come up with a single solution to this later.
None.
Trello …

Get components gem version

---

Gemfile.lock

Capybara 3.38.0
This allows us to move to the latest version of Puma [1].
[1]: https://github.com/teamcapybara/capybara/pull/2530

Update to latest Capybara

---

config/application.rb

This is required as we're using read-only filesystems in replatforming and by default rails attempts to write cached pages to a read-only part of the filesystem

Add option to use a temporary directory for page cache

---

Gemfile
Gemfile.lock

This was added way back in 2015 for developers to compress images locally. There are other ways of doing that locally and this adds an unnecessary dependency to the app.

Remove image_optim gem

---

Dockerfile

GOOGLE_TAG_MANAGER_ID is set to ensure assets are precompiled with GTM module enabled. Value is set to the real GTM ID during deployment. This fixes an issue where assets for Static in the image differed from our old deployments of Static on EC2.
https://github.com/alphagov/static/blob/fb01c7415a419766b15c4e95b9ef0e0452e66ad6/app/assets/javascripts/analytics.js.erb#L3

Set GOOGLE_TAG_MANAGER_ID for image build

---

Dockerfile

GOOGLE_TAG_MANAGER_ID added with ID, this should  ensure assets are precompiled with correct `gtm_id`

Add GOOGLE_TAG_MANAGER_ID

---

app/assets/javascripts/analytics.js.erb

Remove unused GTAG code from the GA4 analytics code.
No longer in use.
None.
Trello card: https://trello.com/c/gnixI84y/295-remove-gtag

Remove GTAG code

---

config/environments/development.rb
config/environments/production.rb

Trello: https://trello.com/c/lxxx5XLZ/178-govuk-has-a-half-implemented-content-security-policy-csp
Since the introduction of the [static proxy](https://github.com/alphagov/govuk_app_config/blob/7f060692720df50a27f6845f052b04eae2246226/lib/govuk_app_config/govuk_proxy/static_proxy.rb) there is no longer an essential need to use absolute asset URLs when using static and thus has become a niche feature.
As we don't use a host for static in production we can disallow the long list of allowed hostnames for assets in our Content Security Policy, which [we intend to do](https://github.com/alphagov/govuk_app_config/pull/274).
This PR removes the ability to configure the asset host, and pre-set defaults, so that developers won't fall into a situation where they configure it and then find it falls …

Remove configurable asset host

---

app/assets/stylesheets/components/_global-bar.scss
app/views/components/_global_bar.html.erb

Show the global bar with a message about upcoming Emergency Alerts test. Change the Emergency Bar background colour to light blue (so as not to confuse it with the black Emergency Banner). Inline the message text so the bar does not take two lines and push content to far down the page.
In advance of the Emergency Alerts test, we want to raise awareness of them happening. This will be removed after the Emergency Alerts test takes place.
[Relevant Trello Card](https://trello.com/c/WtRR3aGm/1775-urgent-emergency-alerts-site-wide-banner-m)

Deploy Global Banner for Emergency Alerts Test

---

lib/tasks/publishing_api.rake

New HTML verification files had been added but forgot to create the special routes.

Add special routes for google search console verification

---

app/views/components/_global_bar.html.erb

Removes banner added in https://github.com/alphagov/static/pull/3039
Leaves the updated styling, but hides the banner and resets the banner text.

Remove emergency alerts banner

---

lib/emergency_banner/deploy.rb
lib/tasks/emergency_banner.rake
test/tasks/emergency_banner_test.rb
test/unit/emergency_banner/deploy_test.rb

The rake task will now fail fast if:
- Too many arguments are provided
- The `campaign_class` argument has an unrecognised value
- The `link` argument is not a valid URI
Previously, inputting a typo would make Origin return 500 errors! By running the rake task with an unescaped comma in the input, as below:
```
kubectl -n apps exec deploy/static -- rake "emergency_banner:deploy['notable-death','Henry Fielding dies','English novelist and dramatist known for his earthy humour and satire dies, age 47','https://en.wikipedia.org/wiki/Henry_Fielding','More information']"
```
The bad use of comma would give the following incorrect entry in redis:
```
irb(main):001:0> Redis.new.hgetall("emergency_banner")
=>
{"short_description"=>
"'English novelist and dramatist known for his earthy humour and …
```

Make `emergency_banner` rake task more robust

---

lib/tasks/publishing_api.rake

- now handled by special-route-publisher (https://github.com/alphagov/special-route-publisher/pull/278)

Remove humans.txt from publishing_api task

---

app/controllers/root_controller.rb
app/views/root/_gem_base.html.erb
app/views/root/gem_layout_full_width_browse_header.html.erb

Add a new template for Browse page headers on the collection application. Update the gem_base with new attributes that have been added to the public_layout.
There are instances of pages on collections that have a coloured background in the heading section. This meant that the the blue bar (which is rendered in the public_layout) had to be rendered by collections otherwise it would result in a gap between the blue bar and coloured section. This solution seemed fine until we had a recent deployment of the global bar. As the global bar includes a blue bar, it meant that the Browse pages had two blue bars. They therefore needed to be removed while the global bar was present and then added back again when the global bar was removed. 
To avoid this needing to happen the next time the bar is …

Add gem_layout_full_width_browse_header template

---

app/assets/javascripts/surveys.js
spec/javascripts/surveys.spec.js

- Adds GA4 tracking to the survey banner. More specifically, it adds a `data-ga4-auto` to send the presence of the banner, `data-ga4-event` for the 'Close' button, and `data-ga4-link` for the survey link.
- As the survey is inserted into the DOM after the modules.js code runs, we can't simply add data-module= to the elements. Instead we manually initialise the GA4 tracking on each element. As JavaScript inserts the banner HTML, we only need to add the tracking attributes here and not in any HTML templates.
- The survey banner is inserted after the GA4 pageview runs, which is why we are using `data-ga4-auto` instead.
https://trello.com/c/udF07C9O/662-banners-survey-banner-element-visibility-navigation-close-user-interaction-and-form-events
- Run a local version of static with this branch …

Add GA4 tracking to survey banner

---

app/assets/javascripts/surveys.js
spec/javascripts/surveys.spec.js

- Adds the `section` value to the GA4 object for the survey banner events, with the value of `section` being the survey's heading text.
- Adds the GA4 form tracker to the email survey banner to track submitting the form.
- Adds a `form_complete` event using `Ga4AutoTracker` when the survey is sent to the user. This adds a `<span>` to the DOM with GA4 auto on it, rather than adding GA4 code to `surveys.js`. I thought this would be better as it prevents us adding a bunch of GA4 code in static which checks if GA4 modules exists, if cookie consent exists, and then more code to push the event. Instead we add a `<span>` with the auto tracker on it, then run `window.GOVUK.Modules.start()`.
- I missed out some tracking requirements in https://trello.com/c/udF07C9O/662-banners-survey-banner-element …

Add GA4 form tracker and section value to survey banner

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/root/_gem_base.html.erb
app/views/root/gem_layout_account_manager.html.erb

https://trello.com/c/9o9pvE3a/2146-implement-one-login-cross-service-header-on-the-email-subscriptions-service
> - To help us here in One Login improve the component
> - To provide email subscriptions service users with the navigation improvements we’re already confident about following our testing
- https://github.com/alphagov/email-alert-frontend/pull/1634
- https://github.com/alphagov/govuk_publishing_components/pull/3659

Implement One Login "cross service header"

---

.gitignore
Gemfile
Gemfile.lock
app/assets/config/manifest.js
app/assets/stylesheets/helpers/_draft.scss
config/environments/production.rb
config/initializers/dartsass.rb

Migrate to Dart Sass from LibSass.
- LibSass is now [deprecated](https://sass-lang.com/blog/libsass-is-deprecated/)
- Making changes ahead of Design System team dropping support for LibSass https://github.com/alphagov/govuk-frontend/discussions/2632.
None.
- run `yarn jasmine:prepare` (or run `bundle exec rake app:assets:clobber app:assets:precompile`)
- what should happen? The Sass files should be compiled. Keep an eye on the command line for warnings indicating the compilation process using Dart Sass
```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div(300%, 4) or calc(300% / 4)
More info and automated migrator: https://sass-lang.com/d/slash-div
│
26 │   three-quarters: (300% / 4),
│ …
```

Migrate to Dart Sass from LibSass

---

Procfile.dev
bin/dev
config/environments/development.rb

- Adds code to support `dartsass` compilation in `govuk-docker`, based off of https://github.com/alphagov/whitehall/pull/8812
- One thing to mention is docker didn't like the execution of `bin/dev` so I had to run `chmod +x bin/dev` on my machine. Not sure if this will be an issue for others?
- `static` has not been updating its SASS/CSS properly when `govuk_publishing_components` is updated. This is due to the migration to dartsass.
- Checkout this branch
- Change your `govuk-docker/static/docker-compose.yml` to use `command: bin/dev` instead of `command: bin/rails s --restart` (or just checkout this branch of `govuk-docker`: https://github.com/alphagov/govuk-docker/pull/721)
- Change `static` to use your local `govuk_publishing_components` then `make static` / run static
- When you …

Configure static to work with dartsass in govuk-docker

---

.github/workflows/ci.yml

Permissions have changed due to integration with Code scanning.

Update Snyk permissions

---

Gemfile
Gemfile.lock
config/environments/production.rb

Use Terser instead of Uglifier to compile JavaScript.
This change is preparation for upgrading to V5 of govuk-frontend in the govuk-publishing-components gem.
govuk-frontend v5 now targets browsers that support ES6. This means that the UMD modules used in govuk_publsihing_components from govuk-frontend use features of ES6 and so it means that Uglifier can't be used anymore because it only supports ES5.
[Trello card](https://trello.com/c/lnPFryyC/2562-prep-for-51-move-fe-applications-from-uglifier-to-terser-l)
| minifier | file | minified JS | minified JS (gzip) |
| --- | --- | --- | --- |
| uglifer |  static/application.js | 81.2KB | 16.6KB |
| terser | static/application.js | 81.3KB | 16.6KB |
I've tested the changes on Integration using the browsers below, functionality works as …

Use Terser instead of Uglifier

---

app/views/components/_global_bar.html.erb

- Adds basic GA4 tracking to the global bar
- This tracking was missed in our GA4 team implementation work, most likely because this banner isn't documented in our component guide lists
- If you're unfamiliar with GA4:
- We add a `data-ga4-link` JSON to links we want to track with some data we want tracked
- We also initialise a `ga4-link-tracker` JavaScript module on these links
- When the link is clicked, the `ga4-link-tracker` JS will use the JSON values, as well as create it's own values, which are then sent to GA4. Therefore we only need to add a small amount of templating data to get these links tracked.
- We also add a `data-ga4-global-bar` attribute, which can be used in a future `govuk_publishing_components` gem release to track every time the banner is rendered
- Trello card: …

Add GA4 tracking to global bar

---

app/assets/stylesheets/components/_global-bar.scss

- Removes the 1px bottom from our non-emergency global bar
- https://trello.com/c/T4tonmaz/166-global-bar-border-issues

Remove 1px border bottom from global bar

---

config/application.rb

This setting has been available for 7 years.
See commit in government-frontend:
https://github.com/alphagov/government-frontend/commit/737211f87e9a9dbf4bcbb3b518a91fec317df50a

Set the timezone to London

---

app/views/components/_global_bar.html.erb

We added the time checks so that the global banner wouldn't have to be manually deployed at midnight. Those checks are no longer needed.

[DO NOT MERGE] Remove time checks from global banner

---

Gemfile
Gemfile.lock
app/helpers/timed_update_helper.rb
app/views/components/_global_bar.html.erb
config/environments/test.rb
test/unit/helpers/timed_update_helper_test.rb

https://trello.com/c/upXxaeBR
Add in a helper method (before_update_time?) which can be used to make banner (or other layout) changes at a fixed time. Using this method rather than rolling a new one each time we have to make timed updates will prevent problems related to time zone settings (such as comparing a Time object - which does support time zones - with a Date object - which does not - causing an update to be an hour out during BST)
Currently all deployments in banner text (non-emergency and perhaps emergency too) are manually triggered using GitHub Actions. Attempts to schedule banner updates using Ruby date functions (by merging the changes early), have caused issues with time-sensitive features due to server time differences from UK time (GMT/BST). A unique banner text …

Timed updates

---

app/assets/javascripts/global-bar-init.js
app/views/components/_global_bar.html.erb
spec/javascripts/global-bar-init.spec.js
spec/javascripts/helpers/GlobalBarHelper.js

When the user is on the same page that the global bar links to, the global bar is hidden via CSS. For example, if the global bar links to `/how-to-vote`, the global bar will not display itself on the `/how-to-vote` page itself.  However the HTML still exists when the banner is hidden, so our `data-ga4-global-bar` attribute was still in the DOM, even though the global bar was not visible. This led to incorrect tracking on the page that the global bar was linking to, as the global bar was tracked as being shown to the user on that page when it was not.
The fix is to add the GA4 attribute using JavaScript, in the same bit of code that controls visibility of the global bar.
https://trello.com/c/ITfYEHT2/832-fix-global-bar-being-tracked-as-visible-on-the-page-it-links-to-even-though-it-is-not-v …

Improve data-ga4-global-bar attribute inclusion

---

Gemfile.lock
app/assets/config/manifest.js
app/assets/javascripts/application.js
app/assets/javascripts/es6-components.js
app/assets/stylesheets/application.scss
config/initializers/govuk_publishing_components.rb

- Move components that rely on govuk-frontend modules to separate `es6-components.js` file
- Removed $govuk-new-link-styles
In the event that a browser below the target for `govuk-frontend` loads a page with JS on it, attempting to parse the JS from `govuk-frontend` will cause an error. To avoid this from happening, JS that contains `govuk-frontend` JS has been moved to seperate file which will be loaded in a script tag with `type="module"`. This will prevent the JS from being parsed and so prevent the error
Removed $govuk-new-link-styles as the default value from v5 of govuk-frontend is true
The intention is for the PR to include the upgrade to the version of the publishing_components_gem as well, once released. This will also fix the failing test which relies on a new config option. …

Migrate to govuk frontend 5.1

---

Gemfile.lock
app/assets/stylesheets/helpers/_old-ie.scss
app/views/root/_javascript.html.erb

- Use type=module for this application's JS file...though I'm not sure what this file is used for, since the gem loads the `application.js` for static in the header layout.
- To coincide with https://github.com/alphagov/govuk_publishing_components/pull/4111
- Has [DO NOT MERGE] as we want the above PR live on `static` first before this is merged.
- To accurately test this you will need to checkout a local version the `govuk_publishing_components` branch linked above
- We will combine `es6-components.js` again as a separate task unless you disagree with this
- Trello card: https://trello.com/c/Hoa45SMD/141-turn-off-javascript-in-legacy-browsers

Drop support for legacy browsers

---

app/controllers/root_controller.rb
app/views/root/_gem_base.html.erb
app/views/root/chromeless.html.erb
app/views/root/gem_layout_explore_header.html.erb
app/views/root/gem_layout_full_width_explore_header.html.erb
app/views/root/gem_layout_no_emergency_banner.html.erb
test/integration/templates_test.rb

- remove four unused layouts: chromeless, gem_layout_explore_header, gem_layout_full_width_explore_header, gem_layout_no_emergency_banner.
- remove omit_emergency_banner code only used by no_emergency_banner layout.
- update test with removal of chromeless
Note: I've confirmed there are no mentions of these layouts in alphagov, and no requests for their templates in the logs in the last 14 days (last 5 days for gem_layout_no_emergency_banner, because that was when I [removed the hack in collections](https://github.com/alphagov/collections/pull/3743) that asked for it).

Remove unused layouts

---

lib/tasks/publishing_api.rake
public/google6db9c061ce178960.html
public/google991dec8b62e37cfb.html
public/googlef35857dca8b812e7.html

- these three verification tokens are out of date and don't need to be served any more
- add link to wiki detailing current users' verification tokens

Remove unused google verification files, 

---

lib/tasks/publishing_api.rake
public/BingSiteAuth.xml
public/googlea6393a390aadfbaa.html
public/googlec908b3bc32386239.html

Move the publishing/handling of routes for Google and Bing authorisation tokens out of Static. The handling of these tokens is moved from static to nginx as of: https://github.com/alphagov/govuk-helm-charts/pull/2357
Static shouldn't really be handling any outside routes. This is the first thing to move over - then we'll move the favicon/apple touch icons into frontend.
When deploying, the change to govuk-helm-charts should go first. Then we restart router to pick up the new config. Then this change to static which removes its ability to serve the routes. Finally, we can delete the old route/content records in router-api and content-store.
https://trello.com/c/o55zYQeB/317-tidy-verification-paths-in-static

Remove verification tokens (these are to be handled by Frontend)

---

lib/emergency_banner/display.rb

This brings the Redis connection retry strategy in line with the configuration specified in [`govuk_sidekiq`](https://github.com/alphagov/govuk_sidekiq/blob/32def77d86d929ca7eb48f35f08401fedeb8407d/lib/govuk_sidekiq/sidekiq_initializer.rb#L10-L12) and [Whitehall](https://github.com/alphagov/whitehall/pull/9430).
By making this change, the application will be able to cope with short periods of Redis instance downtime.
Note: this application uses [version 5.3 of the `redis` gem](https://github.com/alphagov/static/blob/116a981a8428823875eb0610f075710adbdf9307/Gemfile.lock#L490), so we need to use the syntax for 5.x instead of the 4.8 syntax that was used in Whitehall and `govuk_sidekiq`.
[Trello card](https://trello.com/c/YJULijF6)

Set Redis retry strategy for emergency banner

---

lib/tasks/publishing_api.rake

Temp rake task to un-publish apple_touch_icons 
Follow up work to https://github.com/alphagov/static/pull/3428
[trello](https://trello.com/c/vU3MYqzJ/2835-remove-legacy-apple-touch-icon-routes-and-redirect-code-placeholder)

Temp rake task to unpublish apple_touch_icons 

---

lib/tasks/publishing_api.rake

This task has now been run eg [https://www.gov.uk/apple-touch-icon.png?cachebust=1234](https://www.gov.uk/apple-touch-icon.png?cachebust=1234 ) now 404's instead of redirecting.
Reverts alphagov/static#3434
[Trello](https://trello.com/c/kZdg5u2R/2867-unpublish-legacy-apple-touch-icons-placeholder)

Revert "Temp rake task to unpublish apple_touch_icons "

---

app/views/root/_error_page.html.erb
app/views/root/_gem_base.html.erb

- Currently does nothing, but the component will be updated to only return the wrapper block (as per current behaviour) if this parameter is present.
https://trello.com/c/COQYfYgn/347-allow-layoutforpublic-to-work-like-a-normal-layout

Add for_static: true to all calls to layout_for_public component

---

lib/emergency_banner/display.rb
test/unit/emergency_banner/display_test.rb

[Trello card](https://trello.com/c/zkDNXi7x/1400-create-new-redis-instance-for-whitehall-admin-integration)
In https://github.com/alphagov/govuk-helm-charts/pull/2598/commits/501163523cee534667548ab9b288060d2f595ae4 we added a new `EMERGENCY_BANNER_REDIS_URL` environment variable to Static on Integration pointing to Whitehall Admin's newly-provisioned Redis instance's database (`/1`).
Here we access that value in the Emergency Banner's Redis client which shares this Redis instance.
For environments that don't have this variable set yet (i.e. Staging and Production) we fallback on the default `REDIS_URL`.
This is temporary - once we've moved all environments over to the new URL we can remove this default.
`mock_env` is shamelessly copied from …

Default to EMERGENCY_BANNER_REDIS_URL in Emergency Banner's Redis

---

lib/emergency_banner/display.rb
test/unit/emergency_banner/display_test.rb

In 9683ede220f184f188ff4b86e68461b2f09b2872, we allowed this application to use either `EMERGENCY_BANNER_REDIS_URL` or `REDIS_URL`, as different environments were in differet states.
That is no longer the case, so we can remove the code to default to one over the other.
[Trello card](https://trello.com/c/2RF94Axr)

Use only `EMERGENCY_BANNER_REDIS_URL` environment variable

---

Gemfile.lock

Updates Static to the version of govuk_publishing_components that actually uses the for_static: flag (note that static has been providing this flag for a while, so it's already set up to use the component correctly)
https://trello.com/c/COQYfYgn/377-allow-layoutforpublic-to-work-like-a-normal-layout

Update govuk-publishing-components to 45.2.0

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss

This adds in search-with-autocomplete to the global assets that static uses, this is added because the layout-super-navigation-header makes use of the search-with-autocomplete component.
The motivation for this change was to resolve a bug when we pushed search-with-autocomplete live and we discovered that the autocomplete only rendered and operated correctly on a few pages that already had the component embedded. The reason this was not operational was because the CSS and JavaScript were not available unless the autocomplete was already embedded.
There was a decision to make as to whether to add the dependency to the layout-super-navigation-header component or to add them separately here. I've gone with the separate approach as that was the precedent already used for the search nested …

Add search-with-autocomplete component as assets

---

Gemfile.lock

This PR is a substitute for https://github.com/alphagov/static/pull/3545 as that PR did not include bundler upgrade, which is [recommended by nokogiri](https://github.com/sparklemotion/nokogiri/blob/main/CHANGELOG.md#v1180--2024-12-25).
As a safer and more complete substitute for a dependabot PR which attempted to upgrade nokogiri.

Upgrade bundler and nokogiri

---

app/controllers/root_controller.rb
app/views/root/gem_layout_homepage_new.html.erb

Delete unneeded `gem_layout_homepage_new` homepage template.
https://trello.com/c/TZRRwu5e/3304-consolidate-gemlayouthomepage-templates-in-static
A step required to consolidate [gem_layout_homepage_new](https://github.com/alphagov/static/blob/38302ecf649ed7d375c43ee269a13a17772a7d6c/app/views/root/gem_layout_homepage_new.html.erb) into [gem_layout_homepage](https://github.com/alphagov/static/blob/38302ecf649ed7d375c43ee269a13a17772a7d6c/app/views/root/gem_layout_homepage.html.erb), and delete the `_new` template.
This pull request is one of a series of changes needed to consolidate homepage layouts. The correct release sequence is as follows
- https://github.com/alphagov/static/pull/3586
- https://github.com/alphagov/frontend/pull/4645
- https://github.com/alphagov/static/pull/3589

Delete unneeded homepage template

---

app/views/root/_gem_base.html.erb
app/views/root/gem_layout_homepage.html.erb

[To simplify the rollout of the homepage redesign work](https://github.com/alphagov/static/commit/3af25dff72646ba4f8fd6cc6b635f759afc48eff
), `homepage_blue_navbar` was set to `false` on the old homepage template. Whilst it was set to `true` on the new (currently live) homepage. 
This field is safe to remove - it no longer does anything

Remove unused homepage_blue_navbar

---

app/views/root/_gem_base.html.erb
app/views/root/gem_layout_account_manager.html.erb
app/views/root/gem_layout_full_width_no_footer_navigation.html.erb
app/views/root/gem_layout_no_footer_navigation.html.erb

Remove `show_explore_header` from view templates
[Trello](https://trello.com/c/qE79TFYj/3303-remove-legacy-header-variants-from-layoutforpublic)
Removed `show_explore_header` from the view templates as this option was removed from the `layout_for_public` component the `govuk_publishing_components` gem.
Depends on:
It is not possible to remove [layout-header.scss](https://github.com/alphagov/static/blob/main/app/assets/stylesheets/application.scss#L29) from static as the super navigation menu relies on the logo styles provided by the design system.
It may be possible to remove [layout-header.js](https://github.com/alphagov/static/blob/main/app/assets/javascripts/application.js#L20) from static, however this will likely require further testing to ensure it does not break anything, I will …

Remove `show_explore_header` from view templates

---

.github/workflows/ci.yml

Bump actions/checkout from 3 to 4
This resolves the CI error below:
> the runner of "actions/checkout@v3" action is too old to run on GitHub Actions. update the action's version to fix this issue
This version is consistent with other applications, frontend for example - https://github.com/alphagov/frontend/blob/main/.github/workflows/ci.yml#L54

Bump actions/checkout from 3 to 4

---

Gemfile.lock
config/routes.rb

static reaches into the emergency banner redis in another service, if that redis is not available then static will serve errors.
Previously a redis url misconfiguration caused us to deploy a broken static replica set, so we've introduced a new healthcheck type for anything which uses the emergency banner redis, which for the /healthcheck/ready endpoint only will ensure that the emergency banner redis is available. If we had this before the incident the new deployment would have failed, none of the failing pods would have been served traffic, and all the old pods would have still been alive correctly serving traffic.
We also need to configure the kubernetes startupProbe to use /healthcheck/ready instead of /healthcheck/live, but that will be a follow on task to this PR.
I ran up an …

Use new EmergencyBannerRedis healthcheck in /healthcheck/ready

---

app/views/root/_gem_base.html.erb
app/views/root/gem_layout_account_manager.html.erb

Remove `blue-bar` option from view templates
Using the `blue_bar` option in the layout_for_public component has no impact, the blue_bar functionality was removed as part of the brand update
Jira: https://gov-uk.atlassian.net/browse/NAV-18190

Remove `blue-bar` option from view templates
