alphagov/static

app/views/root/report_a_problem.raw.html.erb

https://www.agileplannerapp.com/boards/105200/cards/5814
Addresses line 26 of the spreadsheet of copy changes for that ticket. 
Part of a group of 4 pull requests for the same content:
- https://github.com/alphagov/spotlight/pull/880
- https://github.com/alphagov/feedback/pull/144
- https://github.com/alphagov/performanceplatform-selfserve/pull/1
- https://github.com/alphagov/static/pull/517

Personal information warning feedback copy change

---

app/views/root/_footer_support_links.html.erb

https://www.agileplannerapp.com/boards/105200/cards/8053

Change GDS link in the footer

---

app/views/root/_footer_support_links.html.erb

Better descriptor of the page the link takes users to.

Change Cymraeg link label

---

Gemfile
Gemfile.lock

to be able to use Google content experiment integration to run multivariate tests

bumped govuk_frontend_toolkit to 3.4.0

---

app/assets/javascripts/report-a-problem.js
spec/javascripts/report-a-problem-spec.js

This is in line with the style guide.
It's easier to see the changes using:
https://github.com/alphagov/static/compare/refactor-report-a-problem-js?expand=1&w=1

Make report-a-problem.js a module, make it strict

---

Gemfile
Gemfile.lock

to get bugfix that repairs multivariate tests and allows to track original cohort.
cc @benilovj @edds

bumped govuk_frontend_toolkit to 3.4.2

---

app/assets/javascripts/report-a-problem-form.js
app/assets/javascripts/report-a-problem.js
app/views/root/report_a_problem.raw.html.erb
spec/javascripts/report-a-problem-form-spec.js
spec/javascripts/report-a-problem-spec.js

This is a precursor to adding a second design for multivariate testing.

Tidy report-a-problem JS

---

Gemfile
Gemfile.lock
app/views/root/_base.html.erb

The PRs can be safely merged/deployed in any order, but this relies on:
* https://github.gds/gds/deployment/pull/587
* https://github.gds/gds/puppet/pull/2822

Good user experience in Draft GOV.UK

---

lib/tasks/router.rake

This has now been cleaned up everywhere.

Remove FIXME for /fonts route.

---

Gemfile
Gemfile.lock

This adds support for setting the page variable in Analytics.
https://github.com/alphagov/govuk_frontend_toolkit/pull/203

Bump govuk_frontend_toolkit to 4.1.0

---

config/application.rb

Add static-print.css to precompile list

---

Gemfile
Gemfile.lock

The current one has an escaped copyright logo.

Bump gouvk_template for new copyright

---

config/secrets.yml

This is in accordance with the [12 factor app principles](http://12factor.net/config)
of storing config in the environment.
/cc @alext @jamiecobbett

Take secret key base from environment

---

app/assets/javascripts/analytics/scroll-tracker.js

This link was pointing to a 404.

Fix scroll tracking link

---

app/helpers/survey_helper.rb
app/views/root/_base.html.erb
test/integration/survey_test_test.rb

Trello: https://trello.com/c/qZkEcMji
Displays a trial survey during the given period and the regular survey link any
other day.

Display test survey during the correct period

---

app/assets/javascripts/webchat-iframe.html.erb

The rest of the selectors also needed to be changed with the template
change at eGain's end.

Reflect eGain changes in the other selectors used

---

app/assets/javascripts/webchat-iframe.html.erb

As of Jan 12 3pm the endpoint for webchat will be updated and we are
changing it on this end.

Change HMRC webchat endpoint

---

app/assets/javascripts/user-satisfaction-survey.js
spec/javascripts/user-satisfaction-survey-spec.js

Trello: https://trello.com/c/DEStHomZ
The temporary survey will now run between these two dates.

Run survey between 2016/02/01 and 2016/05/01

---

app/assets/javascripts/analytics/scroll-tracker.js

Adding header tracking to /government/groups/common-technology-services-cts

Adding scroll tracking to CTS org page

---

app/views/govuk_component/docs/govspeak.yml

Include some specialist content with:
* lists containing long items
* lists containing short items
* headings with ids
* a few short paragraphs
* a few long paragraphs
* footnotes
* a call to action
* sup/sub tags
Based on www.gov.uk/drug-safety-update/bisphosphonates-very-rare-reports-of-osteonecrosis-of-the-external-auditory-canal

Add a govspeak fixture with more complete content

---

app/assets/javascripts/analytics/scroll-tracker.js

and remove scroll depth tracking from /tax-disc, aaib-reports and /business-finance-support-finder/search

Add scroll depth tracking to 3 dvla page 

---

app/assets/stylesheets/helpers/_organisations.scss

Desktop mode uses a function to generate the background image, mobile code is hardcoded. This moves the mobile code into the same function.

BAU: refactor organisation logo CSS

---

app/assets/javascripts/analytics/static-analytics.js

Update assets domain

---

app/assets/javascripts/surveys.js

This test survey is planned to run on Tuesday and Wednesday next week inclusive (26th and 27th).

Add three word test survey

---

doc/govuk-components.md

Try and explain the why behind components, as well as the how.
I'm looking for feedback on
- how understandable it is
- if it's helpful to someone new to GOV.UK Components
- phrasing
- spelling
(in that order)

Add documentation on the reasoning behind components

---

app/assets/javascripts/analytics/scroll-tracker.js

This adds scroll tracking to every `h2` on this page: https://www.gov.uk/government/publications/the-essential-trustee-what-you-need-to-know-cc3
[Trello card](https://trello.com/c/ldnU2GvB)

Add scroll tracking to CC3 guidance

---

app/assets/javascripts/surveys.js

[Trello card](https://trello.com/c/3X16Pf1W/9-gov-uk-survey-test-6th-test)
To run next Wednesday and Thursday.

Add September small survey

---

app/assets/javascripts/surveys.js

Trailing commas can cause issues in IE, so I hear.

Remove trailing commas in survey JS

---

app/assets/javascripts/analytics/scroll-tracker.js

This is the fixed version of #834 from @vp2015 .
Scroll tracking request for two universal credit pages
https://www.gov.uk/guidance/universal-credit-how-it-helps-you-into-work
https://www.gov.uk/openingupwork

Update scroll tracker to include two universal credit pages

---

app/assets/javascripts/surveys.js

This small surveymonkey-hosted survey runs for a short period of time and is shown to 1 in 10 users of content that is categorised as "international".
[Trello card](https://trello.com/c/VfiReuan/56-gov-uk-survey-test-8th-test)

International content survey

---

app/assets/javascripts/analytics/scroll-tracker.js

[Trello card](https://trello.com/c/TqQzzllk/412-add-scroll-tracking-to-new-pension-retirement-detailed-guidance-content)
This PR contains changes to headings and urls for the setup of DWP's scroll tracking campaign.
These changes have been made upon request by the performance analyst.
See this [1] Trello card for more details. These changes have been tested on [2] integration.
[1] https://trello.com/c/TqQzzllk/412-add-scroll-tracking-to-new-pension-retirement-detailed-guidance-content
[2] https://deploy.integration.publishing.service.gov.uk/job/Deploy_App/8092/
The following headings urls have been included:
- https://www.gov.uk/guidance/saving-for-retirement-if-youre-aged-16-to-50
- Keep track of your State Pension
- Consider ways to improve your State Pension
- Personal and stakeholder …

Add DWP's scroll tracking campaign

---

app/assets/javascripts/surveys.js
doc/surveys.md
spec/javascripts/surveys-spec.js

[Trello card](https://trello.com/c/MBMSt6k3/74-gov-uk-survey-1st-user-research-panel-sign-up)
Two week survey to test user research sign up on marriage abroad pages.
Marked as do-not-merge as the start date of this survey is currently set to a date that is too early so that we can test its appearance on integration more easily.
Before merge:

User research panel signup survey

---

app/assets/javascripts/surveys.js

4 new surveys that start on December 12th
Trello:
1. https://trello.com/c/v331EZLi/75-gov-uk-survey-2nd-user-research-panel-sign-up-1-of-2
2. https://trello.com/c/yVAzaUsY/76-gov-uk-survey-2nd-user-research-panel-sign-up-2-of-2
3. https://trello.com/c/q0lvlpxP/77-gov-uk-education-content-survey
4. https://trello.com/c/kvnN8tfW/79-gov-uk-survey-1st-family-in-uk

Add new batch of surveys for dec 12th onwards

---

app/assets/stylesheets/helpers/_publisher.scss

Fixes https://github.com/alphagov/static/issues/676
I made this change inline and was not able to run this locally, raising so this it's more likely to be picked up...

Fix inconsistent spacing in page navigation

---

app/assets/javascripts/surveys.js

Trello: https://trello.com/c/3nNrZHLA
Add user research survey on 5 different pages for 5 campaigns
This PR also updates default url survey template.

Add hmrc user research panel

---

app/views/govuk_component/docs/govspeak.yml

Fix unbalanced parentheses

---

app/views/root/_promo_banner.html.erb

Link to campaign site home page from promo banner

---

app/assets/javascripts/core.js

I simply fixed some inconsistencies in the core.js script.

Fixed some inconsistencies in the core.js script.

---

app/assets/javascripts/surveys.js

See individual commits for details.

Fix a couple of IE7 errors

---

doc/surveys.md

Bonus: Also fix a incorrectly formatted heading.

Document forcing a survey to display for testing

---

app/views/govuk_component/docs/metadata.yml

* Specialist document with lots of facets https://www.gov.uk/business-finance-support/techstart-ni-northern-ireland
* News article  with lots of countries https://www.gov.uk/government/news/foreign-secretary-statement-on-the-death-of-nelson-mandela
Added in preparation for making long lists of metadata usable
https://trello.com/c/wKCiyIRs/354-2-deployment-metadata-progressive-disclosure

Extensive examples for metadata component

---

app/assets/javascripts/surveys.js

HMRC trello: https://trello.com/c/t8HJ6lFM/190-govuk-survey-user-research-panel-invite-hmrc
DfE trello: https://trello.com/c/nHar0yr3/191-govuk-survey-user-research-panel-invite-dfe
Publisher Guidance trello: https://trello.com/c/nnB6luc7/189-publisher-guidance-survey-banner
This can be tested by changing the local clock on your machine to make sure the surveys start / end at the appropriate times.

Add hmrc, dfe, and publisher guidance surveys

---

app/assets/javascripts/surveys.js
doc/surveys.md
spec/javascripts/surveys-spec.js

For: https://trello.com/c/n8QbgGXK/169-make-general-improvements-to-surveys-js
This PR adds various improvements that did not make into the surveys during the development of this card: https://trello.com/c/8YSfHXc2. 
The work for the aforementioned card was ultimately not used, but some of the changes made there to surveys are still viable and have been extracted out in this PR.

[DO NOT MERGE] Survey improvements

---

app/assets/stylesheets/govuk-component/_previous-and-next-navigation.scss

- temporary fix to get around issue of HTML caching from slimmer
- will be removed

Add previous styles for previous next

---

doc/surveys.md

This commits add some extra information on how to test that the
surveys are working correctly. Hopefully this will be useful for future
devs.

Add to survey document about testing

---

app/assets/javascripts/surveys.js

For: https://trello.com/c/Asj5HLO6
Adds links to the four surveys on the pages requested, each with a frequency of 1 in 6, running from Aug 25 2017 to Oct 1 2017.

Add some more GDS user research panel surveys

---

app/assets/javascripts/surveys.js

For: https://trello.com/c/xcvqIxHr, https://trello.com/c/zXdSm7Ho
Adds 3 new surveys on the pages requested, running from Sept 13 2017
to Oct 14 2017.

Add more HMRC surveys

---

app/assets/javascripts/surveys.js

For: https://trello.com/c/8tBVbJf1/233-education-top-tasks-priority

Add education survey sept 2017

---

app/assets/stylesheets/govuk-component/govspeak/_attachment.scss
app/assets/stylesheets/govuk-component/govspeak/_call-to-action.scss
app/assets/stylesheets/govuk-component/govspeak/_charts.scss
app/assets/stylesheets/govuk-component/govspeak/_contact.scss
app/assets/stylesheets/govuk-component/govspeak/_example.scss
app/assets/stylesheets/govuk-component/govspeak/_footnotes.scss
app/assets/stylesheets/govuk-component/govspeak/_fraction.scss
app/assets/stylesheets/govuk-component/govspeak/_information-callout.scss
app/assets/stylesheets/govuk-component/govspeak/_legislative-list.scss
app/assets/stylesheets/govuk-component/govspeak/_media-player.scss
app/assets/stylesheets/govuk-component/govspeak/_stat-headline.scss
app/assets/stylesheets/govuk-component/govspeak/_tables.scss
app/assets/stylesheets/govuk-component/govspeak/_typography.scss
app/assets/stylesheets/govuk-component/govspeak/_warning-callout.scss
app/views/govuk_component/docs/button.yml

The component guide URL referred to in this repo has changed.

Update references to component guide

---

app/assets/javascripts/surveys.js

For:
* https://trello.com/c/cF77Wgj4/235-govuk-survey-hmrc-link-replacements
* https://trello.com/c/Gfly2bRd/236-govuk-survey-hmrc
* https://trello.com/c/Kr9alwwt/234-learning-to-drive-tasklist-survey
These surveys aren't straight forward so worth reviewing commit-by-commit to get the notes.

Change the survey urls for the hmrc jul 2017 surveys + add 2 more surveys

---

Gemfile
Gemfile.lock
app/assets/javascripts/webchat-iframe.html.erb
app/views/root/_javascript.html.erb
app/views/root/_stylesheet.html.erb
app/views/root/print.html.erb

For: https://trello.com/c/SVfWxYYs/205-enable-subresource-integrity-sri-on-static-s
Relies on https://github.com/alphagov/govuk_template/pull/327 at which point we'll tidy up the last commit to use a released version, not a git one.

Add sri again

---

app/assets/javascripts/surveys.js

For: https://trello.com/c/YvLlYsHX/264-govuk-survey-hmrc-import-export
Adds a new user research panel survey for hmrc around import/export and tidies up a couple of old surveys.

Hmrc import export user research survey

---

app/assets/javascripts/current-location.js
app/assets/javascripts/govuk-component/tasklist.js
app/assets/javascripts/history-support.js
app/assets/stylesheets/govuk-component/_task-list.scss
app/views/govuk_component/docs/task_list.yml
app/views/govuk_component/task_list.raw.html.erb
spec/javascripts/govuk-component/task-list-spec.js
test/govuk_component/task_list_test.rb

- fix issues with number vertical alignment and panel top spacing on mobile
- add click tracking for panel links
- code update to rename the parts of a task list, now contains groups each containing steps, instead of steps containing sections
Before:
After:
Component guide link: https://govuk-static-pr-1182.herokuapp.com/component-guide/task_list
Trello card: https://trello.com/c/hjuxqyuT/275-visual-and-code-tweaks-to-the-task-list
Tested on iphone 6s, Google Nexus 6, iphone 6, Samsung Galaxy s5, ipad air 2, Google nexus 7, Samsung galaxy tab 4, Google Pixel
IE8, IE9, IE10, FF 56, Opera 48, Chrome latest, Safari 5.1, Edge 16

Improve task list

---

app/assets/javascripts/current-location.js
app/assets/javascripts/govuk-component/tasklist.js
app/assets/javascripts/history-support.js
app/assets/stylesheets/govuk-component/_task-list.scss
app/views/govuk_component/docs/task_list.yml
app/views/govuk_component/task_list.raw.html.erb
spec/javascripts/govuk-component/task-list-spec.js
test/govuk_component/task_list_test.rb

Revert "Improve task list"

---

app/assets/javascripts/surveys.js

They're still short on responses so requested another months extension.

Extend HRMC child benefit and tax payments surveys by 1 month

---

app/assets/javascripts/current-location.js
app/assets/javascripts/govuk-component/tasklist.js
app/assets/javascripts/history-support.js
app/assets/stylesheets/govuk-component/_task-list.scss
app/views/govuk_component/docs/task_list.yml
app/views/govuk_component/task_list.raw.html.erb
spec/javascripts/govuk-component/task-list-spec.js
test/govuk_component/task_list_test.rb

Revert "Revert "Improve task list""

---

app/assets/javascripts/surveys.js
doc/surveys.md

For: https://trello.com/c/kjg67jpH/287-coming-to-the-uk-top-tasks-survey
A 1 in 20 survey which will run on pages which have the `Visas and immigration` breadcrumb.

Add "Coming to the UK" survey

---

app/assets/javascripts/surveys.js

For: 
* https://trello.com/c/iS6QjYK5/289-land-registry-user-research-panel
* https://trello.com/c/LPZQu6Ax/290-govuk-survey-hmrc-money-laundering
* https://trello.com/c/JI7wZ34q/291-govuk-survey-hmrc-guidance
See commits for more details

Add late nov 2017 surveys

---

app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss
app/views/govuk_component/docs/taxonomy_sidebar.yml
app/views/govuk_component/taxonomy_sidebar.raw.html.erb
config/locales/en.yml
test/govuk_component/taxonomy_sidebar_test.rb

Reverts alphagov/static#1200
Not ready to deploy yet until we have a deployment plan

Revert "Update design of taxonomy sidebar"

---

app/assets/javascripts/govuk-component/tasklist.js
app/assets/stylesheets/govuk-component/_task-list.scss
app/views/govuk_component/docs/task_list.yml
app/views/govuk_component/task_list.raw.html.erb
spec/javascripts/govuk-component/task-list-spec.js
test/govuk_component/task_list_test.rb

Reverts alphagov/static#1201
Reverting the changes to the task list component as this component is now being moved to the govuk_publishing_components gem.

Revert "New task list component design and features"

---

app/assets/javascripts/surveys.js

Some cleanup, a frequency change, and a new survey.
For: https://trello.com/c/V3gUp2Xg/316-taxonomy-tree-testing-invite-banner & https://trello.com/c/ttReKJgj/322-bump-hmrc-manuals-frequency-to-1-in-3

Festive survey changes

---

app/assets/javascripts/current-location.js
app/assets/javascripts/govuk-component/tasklist.js
app/assets/javascripts/header-footer-only.js
app/assets/javascripts/history-support.js
app/assets/javascripts/start-modules.js
app/assets/stylesheets/govuk-component/_component-print.scss
app/assets/stylesheets/govuk-component/_component.scss
app/assets/stylesheets/govuk-component/_task-list-header-print.scss
app/assets/stylesheets/govuk-component/_task-list-header.scss
app/assets/stylesheets/govuk-component/_task-list-print.scss
app/assets/stylesheets/govuk-component/_task-list-related.scss
app/assets/stylesheets/govuk-component/_task-list.scss
app/views/govuk_component/docs/task_list.yml
app/views/govuk_component/docs/task_list_header.yml
app/views/govuk_component/docs/task_list_related.yml
app/views/govuk_component/task_list.raw.html.erb
app/views/govuk_component/task_list_header.raw.html.erb
app/views/govuk_component/task_list_related.raw.html.erb
spec/javascripts/govuk-component/task-list-spec.js
test/govuk_component/task_list_header_test.rb
test/govuk_component/task_list_related_test.rb
test/govuk_component/task_list_test.rb

This is still used in manuals frontend
Reverts alphagov/static#1221

Revert "Remove task list components"

---

app/assets/javascripts/surveys.js

The number of questions currently asked in the survey has been updated from 2 to 3. We should reflect that in the survey banner text.

Changes banner text for tree survey

---

app/assets/javascripts/analytics/custom-dimensions.js
spec/javascripts/analytics/static-analytics-spec.js

Extracted from #1183 to make that PR easier to review.

Improvements and tidy ups to the JS specs

---

app/assets/javascripts/surveys.js

Based on the current rate of survey completions, we will not reach our
target goal by Saturday 10th.

Increase frequency and duration of CTTUK-Professionals survey

---

app/assets/javascripts/surveys.js

For: https://trello.com/c/Wz9ppQon/72-1-govuk-survey-hmrc
All surveys will have a 1-in-5 frequency and will run from 14 February 2018 to 16 March 2018.

Adds hmrc surveys for February

---

app/assets/javascripts/surveys.js

https://trello.com/c/z22WEjzo/277-put-specialist-user-supergroup-subgroup-study-live-on-govuk
This will display for 1 in 3 users on selected specialist
finder and document pages. It takes the user to an Optimal
Workshop task.

Add specialist user/super group survey

---

app/views/govuk_component/button.raw.html.erb
app/views/govuk_component/docs/button.yml
test/govuk_component/button_test.rb

Title is a default HTML attribute and we do make use of this attribute in completed transactions.

Add title attribute to button component

---

app/assets/javascripts/surveys.js

https://trello.com/c/CI3NujXJ/157-test-v8-of-cttuk-using-treejack-and-govuk-survey-banner

Add new taxonomy survey CTTUK_iteration 8

---

app/assets/javascripts/surveys.js

The survey is due to finish 00:00:00 on March 7th, but we only have ~60%
responses, so we need a little more time to try and get closer to 100%.

Extend CTTUK survey

---

app/assets/javascripts/surveys.js

https://trello.com/c/kmvGEn8u/299-put-link-groups-labels-study-live-on-govuk
Adds a survey linking to a research activity for 1 in 3 users on pages tagged to specific taxons.

Add groups and labels survey

---

app/assets/javascripts/surveys.js

https://trello.com/c/gRGR1lSO/184-put-up-a-survey-to-test-v4-of-the-transport-branch

Add Transport_iteration_4 survey

---

app/assets/javascripts/surveys.js

Surveys currently appear too frequently, this PR reduces that.

Reduce frequency of content pages design surveys

---

doc/slimmer_templates.md

Makes it clearer which layouts to use.

Update docs about templates

---

Gemfile
Gemfile.lock

Update govuk_template gem
See https://trello.com/c/504VZUfh/100-help-test-new-font-loading-strategy-2, https://github.com/alphagov/govuk_template/pull/341 for context.

Update govuk_template to 0.24.0

---

app/assets/javascripts/surveys.js

https://trello.com/c/YdkpOqZk/123-may-home-office-surveys-start-1-may-2018
Adds 3 home office surveys.

Add home office surveys

---

app/controllers/root_controller.rb

Following on from https://github.com/alphagov/static/pull/1406

Add button to removed templates

---

app/assets/javascripts/surveys.js

https://trello.com/c/SiYzGKOd/175-hmrc-digital-surveys
Adds 10 surveys to selected HMRC pages.

Add HMRC digital services surveys

---

app/assets/javascripts/surveys.js

https://trello.com/c/K3RWmmXH/44-1-march-hmrc-surveys-expire-june-1-2018
Remove 3 surveys which expire 01 June 2018, don't merge till then.

Remove surveys which expired on 01/06/2018

---

app/assets/javascripts/surveys.js

I've followed the previous survey for the Transport branch, amending
where appropriate.
https://trello.com/c/g7CW8ADC/182-run-a-tree-test-on-our-changes-to-the-business-branch

Add Business branch topic page survey

---

app/assets/javascripts/surveys.js

This survey didn't go live when scheduled, so update the start and end
times.

Update start and end time for Business_iteration_1

---

app/assets/javascripts/surveys.js

Managed by Content Pages and Navigation

Supergroup survey

---

app/assets/javascripts/surveys.js

Removes the Content Pages supergroup survey

Remove Content Pages supergroup survey

---

Gemfile
Gemfile.lock

https://trello.com/c/vhfMGngX/239-investigate-and-correct-smart-answer-google-analytics-tracking

Bump govuk-publishing-component to 9.12.1

---

app/assets/javascripts/surveys.js

To the end of Monday the 17th.

Extend EU Exit survey end time

---

app/views/root/_base.html.erb

Add EU Exit section footer links

---

app/assets/javascripts/surveys.js

IPO have requested we change the frequency of this survey to show to
1 in 5 of all visitors.

Change IPO survey frequency

---

app/assets/javascripts/surveys.js

Reverts alphagov/static#1623
We were given the wrong survey and don't have a replacement yet.
https://trello.com/c/8xsQEobh/774-remove-the-standards-assurance-survey

Revert "Add standards assurance survey at /service-standards-reports"

---

app/assets/javascripts/surveys.js

Do not merge until we've had confirmation on (new) start & end date.
https://trello.com/c/8oV0Lc9k/776-updated-with-new-link-replace-service-standard-report-survey-link

Update service standards survey

---

app/views/root/_base.html.erb

https://trello.com/c/LmbAtzmh/315-add-organisation-labels-to-pages-in-the-business-journey

Updates the content for the footer on the business finder

---

app/views/root/_base.html.erb

Revert "Point search box at the all content finder"

---

app/views/root/_base.html.erb

Trello: https://trello.com/c/z9DP4EMK/402-add-tracking-to-govuk-footer-links

Adds tracking attributes to footer links

---

app/assets/javascripts/surveys.js

https://trello.com/c/BxoRtI6B/969-govuk-survey-public-health-england

Add a survey for Public Health England & remove expired surveys

---

app/assets/javascripts/surveys.js

Removes the PHE Small Survey which has finished ahead of schedule.

Remove Public Health England small survey

---

app/views/root/404.html.erb
app/views/root/_base.html.erb

This allows faceted site search on GOV.UK
https://trello.com/c/V28EGkoW/452-redirect-site-search-to-all-content-finder-s

Point site search box to the all content finder

---

app/views/root/_base.html.erb

Erb comments don't start with a `#`.

Fix comment

---

app/views/layouts/govuk_template.html.erb

This PR will be deployed when we are ready to switch over to the new cookie banner.

Switch to new cookie banner

---

app/assets/javascripts/analytics/init.js.erb

Neglected to make this change as part of https://github.com/alphagov/static/pull/1832

Update call to linker code to match new syntax

---

app/assets/javascripts/analytics/init.js.erb

- also change format of the function call so it's more readable and updateable

Update linked domains

---

app/assets/javascripts/analytics/init.js.erb

Adding a set of new services to the cross-linker.

Add new linked domains

---

app/views/notifications/_global_bar.html.erb

Switches off the global banner so it no longer appears on the site.

Switch off banner

---

.rubocop.yml
app/controllers/icon_redirects_controller.rb
lib/emergency_banner/display.rb
lib/tasks/asset_compile.rake
lib/tasks/publishing_api.rake
test/integration/notifications_test.rb
test/integration/templates/chromeless_test.rb
test/integration/templates/non_layout_templates_test.rb
test/integration/templates_test.rb
test/test_helper.rb
test/unit/emergency_banner/display_test.rb

trello: https://trello.com/c/Lijki8aj/1584-3-enable-rails-rubocop-rules-via-rubocop-govuk-on-all-our-rails-apps

Enable rails-specific rules for rubocop-govuk

---

doc/global-banner.md

Trello: https://trello.com/c/xEOQ6G96/317-refactor-global-banner-component
The heading wasn't rendering properly

Fix docs heading style

---

app/assets/javascripts/analytics/scroll-tracker.js

Scroll tracking was not firing on these links.
- The first link was using a anchor link - removed this and it seems to work
- The other 2 links had incorrect headings

Fix scroll tracking headings

---

app/views/root/_base.html.erb

Trello: https://trello.com/c/ktTNSwAa/398-spike-how-to-update-taxons-so-brexit-becomes-transition
A part of performing tests for potential migrations. Content TBC.
**Before**
**After**

[DO NOT MERGE] Update footer to transition content

---

app/assets/stylesheets/helpers/_header.scss

**Note: this PR does not switch the banner on, it just updates the colour**
The banner will look like this:

Update global banner colours

---

app/assets/stylesheets/header-footer-only-print.scss
app/assets/stylesheets/header-footer-only.scss
app/assets/stylesheets/helpers/_footer.scss
app/assets/stylesheets/helpers/_header.scss
app/assets/stylesheets/settings/_colours.scss
app/assets/stylesheets/settings/_spacing.scss
app/views/layouts/govuk_template.html.erb
app/views/root/_base.html.erb
app/views/root/_footer_support_links.html.erb

Updating the colours in the header and footer so they match the currently updated apps.
Updated 'news and communications' in menu so it doesn't unnecessarily wrap on small screens.
So the colours are consistent and provide a more accessible experience.
<table><tr><td>
</td><td>
</td></tr></table>
<table>
<tr>
<td>
</td>
<td valign="top">
</td></tr></table>
<table>
<tr>
<td>
</td>
<td valign="top">
</td></tr></table>
<table>
<tr><td>
</td><td>
</td></tr></table>

Update colours in header and footer to use new palette

---

app/assets/javascripts/global-bar-init.js
app/assets/stylesheets/helpers/_header.scss
app/views/notifications/_global_bar.html.erb

This screenshot was taken from running this PR's branch on integration.

Add banner to point to COVID-19 page

---

Rakefile
script/copy_component_translations_from_whitehall
script/rails

This is depended on by https://github.com/alphagov/govuk-jenkinslib/pull/66.

Make entire repository pass Rubocop linting

---

doc/test-ecommerce-changes-to-static.md

Until we are able to get better ecommerce testing coverage, these are some assembled notes on how to do manual ecommerce testing after making a change to the `ecommerce.js` file here

Add notes on manual ecommerce testing in a doc

---

app/views/root/_base.html.erb

Trello:
- https://trello.com/c/aA1xgP2S/56-update-footer

Change cv 19 footer

---

app/views/root/404.html.erb
app/views/root/_error_page.html.erb

We're preparing for an increase in traffic.

Add links to coronavirus on error pages

---

app/views/root/_base.html.erb
test/integration/templates/error_4xx_test.rb
test/integration/templates/error_5xx_test.rb
test/integration/templates/header_footer_only_test.rb
test/integration/templates/homepage_test.rb
test/integration/templates/wrapper_test.rb

Reverts alphagov/static#2103
We don't want to deploy this yet.

Revert "Remove (temporarily) the search box from header"

---

app/views/root/_base.html.erb
test/integration/templates/error_4xx_test.rb
test/integration/templates/error_5xx_test.rb
test/integration/templates/header_footer_only_test.rb
test/integration/templates/homepage_test.rb
test/integration/templates/wrapper_test.rb

Revert "Revert "Remove (temporarily) the search box from header""

---

app/views/root/_base.html.erb
test/integration/templates/error_4xx_test.rb
test/integration/templates/error_5xx_test.rb
test/integration/templates/header_footer_only_test.rb
test/integration/templates/homepage_test.rb
test/integration/templates/wrapper_test.rb

Reinstate the search box in header

---

app/assets/stylesheets/helpers/_header.scss
app/views/notifications/_global_bar.html.erb

Trello: https://trello.com/c/CJe1slnS/91-sitewide-banner-design-tweaks
- Make border-top 10px to match the landing page
- Add 1px white border to the bottom of the banner to help differentiate it from the homepage content
- Update content

Banner tweaks

---

app/views/root/422.html.erb

https://trello.com/c/Uzpw1bDA/243-document-how-error-pages-work-on-govuk
Related to: https://github.com/alphagov/govuk-puppet/pull/10346
Extracted from: https://github.com/alphagov/email-alert-frontend/pull/743

Add new generic unprocessable entity page

---

app/assets/javascripts/global-bar-init.js

Increase BANNER_VERSION so that banner will always appear again

Increase BANNER_VERSION

---

public/humans.txt

Will change https://www.gov.uk/humans.txt

Change job link in humans.txt

---

app/assets/javascripts/global-bar-init.js
app/assets/stylesheets/helpers/_header.scss
app/views/notifications/_global_bar.html.erb

Changes have been announced that we want to publicise.
Mostly resurrected from https://github.com/alphagov/static/commit/f4f8b44ec4250d6fbbec8f6177ec24584443b25a#diff-e17896925164fa4471101aca24b30733

Reinstate additional global bar section

---

app/views/root/_base.html.erb
startup.sh

Updated wording as instructed by content team.
https://trello.com/c/UmO2gpPP/305-update-govuk-site-wide-footer

Amend transition footer text

---

app/views/root/_base.html.erb

https://trello.com/c/kfKMDlyt/343-change-get-ready-text-to-check-the-new-rules-on-the-landing-page-govuk-homepage-and-footer

Reword transition link

---

app/assets/javascripts/analytics/init.js.erb

[Trello card](https://trello.com/c/mF7Z1TqO/41-print-a-qr-code-poster-nhs)

Add create QR code service to x-domain

---

app/assets/stylesheets/helpers/_header.scss
app/views/root/_base.html.erb

Revert "Mobile search toggle button"

---

app/assets/stylesheets/helpers/_header.scss
app/views/root/_base.html.erb

Revert "Revert "Mobile search toggle button""

---

.gitignore
Gemfile
Gemfile.lock
test/test_helper.rb

https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
We should always be monitoring the amount of code that is exercised
when we run our tests.

Use SimpleCov to monitor test coverage

---

app/views/notifications/_global_bar.html.erb

To keep this aligned with the taxonomy
[Trello card](https://trello.com/c/0SiAOpAL)

Update transition link label in global bar

---

app/views/notifications/_global_bar.html.erb

Trello: https://trello.com/c/C5nZsytg

Update site-wide banner subtext

---

public/humans.txt

Thanks to Keith and Joe for writing such lovely words about our friend.

Bye bye Jon

---

public/humans.txt

Update recruitment URL

---

public/humans.txt

[This page](https://web.archive.org/web/20201127160746/https://www.gov.uk/humans.txt) has been archived in the wayback machine.

Jon's gone and it's time to let go.

---

app/views/notifications/_global_bar.html.erb

Trello: https://trello.com/c/NB9Pe1qq

Update Covid text on site-wide banner

---

app/views/notifications/_global_bar.html.erb
app/views/root/_base.html.erb

https://trello.com/c/bcGhcsn8/742-update-footer-content-5
https://trello.com/c/d9p8qjtJ/740-update-global-banner-content-1
Please see the commits for more details.

Update content for Brexit links

---

app/views/notifications/_global_bar.html.erb

Update covid banner text

---

app/views/notifications/_global_bar.html.erb
app/views/root/_base.html.erb

Update Brexit wording site-wide under global bar and footer.
[Trello card](https://trello.com/c/XmaPJL11/821-update-branded-brexit-sidebar-nav-placement-visual-and-logic#comment-6012e2b3ac338d8798c67f8f)

Update brexit wording

---

app/assets/stylesheets/core-layout-print.scss
app/assets/stylesheets/core-layout.scss

These don't bring any value and we'd like to change these assets' hashes for a test.

Remove comments

---

app/views/components/_global_bar.html.erb

Trello: https://trello.com/c/jDiQRvsX

[DO NOT MERGE] Update text on Coronavirus site-wide banner

---

README.md
startup.sh

Trello: https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh

Rewrite README to encourage use of govuk-docker

---

CONTRIBUTING.md
docs/humans.md

We renamed this to `main` some time ago.

Fix links to static master

---

app/controllers/root_controller.rb
app/views/root/_gem_base.html.erb
app/views/root/gem_layout_no_footer_navigation.html.erb

Missed in https://github.com/alphagov/static/pull/2554 😬

Add missing templates and order them

---

public/humans.txt

This reverts commit 5e739d663b7a813a16633dcb92cdb7305b00102c.

Revert humans.txt to normal

---

public/humans.txt

Because it's their birthday and they are lovely https://blog.nationalarchives.gov.uk/10-years-of-gov-uk-in-three-minutes/

Add birthday wish to National Archives

---

public/humans.txt

Restore standard humans.txt

---

app/assets/javascripts/analytics.js.erb

An incorrect URL was previously provided. This corrects it.

Fix URL to the wrong service

---

app/views/components/_global_bar.html.erb

Trello - https://trello.com/c/SeHSQTBu/482-booster-campaign-update-site-wide-banner-text

Update banner text in line with latest copy

---

app/assets/javascripts/surveys.js
spec/javascripts/support/jasmine.yml

Changes based on a review that was completed post-merge of https://github.com/alphagov/static/pull/2697 from @kevindew.
Comments marked with a 👍  have been resolved as suggested. Other comments inline in the original review.
None.

Review tweaks for surveys jQuery removal

---

public/humans.txt

We're waiving the usual 5 year rule because of Bill's exceptional impact here.

Bill's leaving today

---

Gemfile.lock

Update to the newest release of `govuk_publishing_components`.
We want to test some of the changes to the analytics code.
None.

Bump to latest components gem

---

Gemfile.lock

Bump to the latest version of the components gem.
We want to test some of the code on integration and I can't wait for dependabot.
None.

Update to the newest components gem

---

public/humans.txt

Today is Ben Thorner's last day at GDS. As per the documentation he very helpfully wrote [1] we'd like to make a special gesture to thank him for his exceptional positive impact to GDS.
[1]: https://github.com/alphagov/static/blob/577fd669535a8f5e44e26c2764e54a63ff51b793/docs/humans.md

Update humans.txt to mark Ben Thorner's departure

---

Gemfile.lock

Bump govuk_publishing_components from 29.12.0 to 29.13.0

Bump govuk_publishing_components from 29.12.0 to 29.13.0

---

Gemfile.lock

https://github.com/alphagov/govuk_publishing_components/releases/tag/v30.4.1

Bump govuk_publishing_components to 30.4.1

---

config/environments/development.rb

It's going to be deprecated https://github.com/alphagov/plek/pull/94

Replace Plek.current with Plek.new

---

public/humans.txt

Add thank you to Ian James

---

public/humans.txt

In keeping with [the humans.txt tradition](https://github.com/alphagov/static/blob/main/docs/humans.md), put a temporary message up saying thanks to Ed.
As usual, we'll revert this after ~1 day.

Say thank you to Ed Kerry

---

public/humans.txt

This reverts commit f4c051f5a733e99cd44480c730af29201d835e0e.

Revert "Say thank you to Ed Kerry"

---

app/views/root/_gem_base.html.erb

Update copy to reflect GOV.UK One Login name change in header.

---

public/humans.txt

Say goodbye to Kate in humans.txt

---

public/humans.txt

Reset humans.txt

---

public/humans.txt

Add leaving note for Dilwoar

---

public/googlea6393a390aadfbaa.html
public/googlec908b3bc32386239.html

HTML verification files are generated per user, so this adds multiple user's files.

Add Google Search Console verification for www.gov.uk

---

public/humans.txt

This reverts commit 8f81366e14512791b346cebbd06edcfb1a91eb31.

Revert "Add leaving note for Dilwoar"

---

yarn.lock

Bump hosted-git-info

---

app/controllers/root_controller.rb
app/views/root/_gem_base.html.erb
app/views/root/gem_layout_full_width_browse_header.html.erb

Reverts alphagov/static#3053
Introduces visual bug which was thought to be fixed.

Revert "Add gem_layout_full_width_browse_header template"

---

public/humans.txt

Add humans.txt message to Rosa Fox

---

public/humans.txt

Add Tim LB leaving message

---

public/humans.txt

This reverts commit a7eb6a88f96bebde7e5adfcda10afdb163899304.
[It's been scraped by the wayback machine](https://web.archive.org/web/20240314182657/https://www.gov.uk/humans.txt) and we have confirmation that he's seen it

Remove Tim LB leaving message

---

app/views/components/_global_bar.html.erb

- Displays the global banner with "Register to vote" information
- https://trello.com/c/4Izb8Z9e

Add register to vote banner

---

app/views/components/_global_bar.html.erb

- Update global bar messaging with photo ID guidance
- https://trello.com/c/4HovWiZO/172-update-wording-of-global-banner-to-go-live-19-june

Update global bar text with photo ID guidance

---

public/humans.txt

This reverts commit adc23f3d273b5d75abc94261e70c0ac22d7191d0.

Revert "Say goodbye to Chris Banks"

---

yarn.lock

Upgrade express and its dependencies
