alphagov/static

app/assets/javascripts/analytics.js, app/assets/javascripts/analytics/error-tracking.js
- We don't track frontend javascript errors at all at the moment, this should be remedied quickly.
- There are about a thousand ways to slice this issue, and there are lots of factors that complicate the way we deliver tracking (do we run our own error server? do we pay for a service? What about ajax events?) but a quick bootstrap solution would be to use google analytics, as we are already using it to track non-error events.
- Not sure what support < ie8 is like for error events, happy to take some advice here
=> Adds error tracking through analytics to static

app/views/root/406.html.erb, app/views/root/410.html.erb
The only search box on these pages is (now) above.
=> Fix references to a search box "below"

app/views/govuk_component/docs.yml
Follow up to https://github.com/alphagov/static/pull/488, adding a more complex/problematic example.
This was originally reported in https://github.com/alphagov/whitehall/issues/1839
It's a pretty reasonable example of content that requires more design
handling than some of the simpler examples here.
Longer term we'll start separating out demonstrative examples from
what are, effectivetely, visual regression examples. But in the mean
time we should continue capturing them
=> Add an example of many long footer metadata items

app/assets/stylesheets/govuk-component/_alpha-label.scss, app/assets/stylesheets/govuk-component/_component.scss, app/views/govuk_component/alpha_label.raw.html.erb, app/views/govuk_component/docs.yml
The same as the beta, but alpha. For things that are newer and haven't
yet proven their worth.
=> Add an alpha label component

app/assets/javascripts/core.js
Some GOV.UK pages, like Smart Answers, load content via JS, including
radio buttons or checkboxes. These will be added to the DOM after the
selector is run and the resulting elements are passed to SelectionButtons
SelectionButtons can also take a string selector and use document
events (https://github.com/alphagov/govuk_frontend_toolkit/pull/139/)
so use that and any JS loaded content  will get the behaviour too.
@robmckinnon spotted this in https://github.com/alphagov/smart-answers/pull/1419, but it's better to fix it in the app we're applying it (otherwise we'll run into versioning problems eventually)
=> Use SelectionButtons live selector, for JS/AJAX content

app/views/root/400.html.erb, app/views/root/404.html.erb, app/views/root/406.html.erb, app/views/root/410.html.erb, app/views/root/418.html.erb, app/views/root/_error_page.html.erb, app/views/root/_google_analytics.html.erb
For 4xx or 5xx responses, send the HTTP status code as a custom variable
to Google Analytics. This will be useful both for the /info pages
application and for search analytics.
Explicitly add status codes as local variable in 4xx responses, since
they weren't recorded before.
=> Send HTTP status codes back to Google Analytics.

app/assets/stylesheets/helpers/_core.scss, app/assets/stylesheets/helpers/_multi-step.scss, app/assets/stylesheets/helpers/_publisher.scss, app/assets/stylesheets/helpers/_report-a-problem.scss, app/assets/stylesheets/helpers/_text.scss, app/views/root/related.raw.html.erb
Originally the related sidebar was designed to scroll with the page. This was removed quite some time ago but the code was all left so that it would still be possible to re-enable it.
This cleans that up and removes the position absolute elements. It also uses the new grid-layout mixins to layout the `<main>` and `<div class="related">` elements.
I would like to get feedback on this approach and probably take over preview with this change for a bit before we merge as it is quite a large change to most pages on GOV.UK.
----
Dev review:
=> Make content and related float rather than using absolute positioning

app/views/root/418.html.erb
As I understand it, this was only ever intended for use while migrating content from Directgov and Business Link to GOV.UK: Redirector used this to indicate "content will be here by launch". We've now launched, [Bouncer](https://github.com/alphagov/bouncer) has replaced Redirector (and no longer supports the 418 status code), and our logs show nothing has served a 418 response in at least the last month.
A 418 code is only correct for Web servers that are teapots, in line with [RFC 2324](http://tools.ietf.org/html/rfc2324#section-2.3.2). I am confident GOV.UK has not been a teapot at any point since launch.
=> Remove the 418 error page

app/views/root/_google_analytics.html.erb
We track the HTTP status code using the GA custom variable
httpStatusCode for all 4xx and 5xx responses. However, it's
remarkably difficult to filter for "custom variable not set"
in GA [1], and actually we're usually interested in getting
all successful responses, rather than unsuccessful ones.
So, if this is not a 4xx or 5xx response, pass a default value
of 'unset' to GA, to simplify filtering.
[1] http://stackoverflow.com/questions/7972978/google-analytics-exclude-empty-custom-variable-in-a-custom-report
=> Pass default value to GA httpStatusCode variable.

app/assets/stylesheets/helpers/_report-a-problem.scss
Use the site width container for the report a problem rather than using
the older outer block mixin. This means it will consistently be in the
right place.
=> Indent report a problem link and form

app/views/govuk_component/docs.yml, app/views/govuk_component/option_select.raw.html.erb
In the future I'll be adding an `aria-controls={options-container-id}` to the `.container-head` of this component. `aria-controls` exposes the relationship between `.container-head` and `.options-container` to accessibility APIs.
For this reason it is important that the `.options-container` actually has an `#id` so I'm adding it here.
Adding a non-optional value like this to a component would normally be a breaking change, however there are no bits of GOV.UK using this component yet so it's fine.
=> Add an ID to the options-container

app/views/root/_google_analytics.html.erb
We already do this for old-style analytics, we need to ensure we do it for Universal Analytics as well.
Documentation: https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced#anonymizeip
Fulfils https://www.pivotaltracker.com/story/show/88175264
=> Ensure we anonymise the IP addresses in UA

app/assets/stylesheets/helpers/_core.scss
When we changed the default styling of text content to use an element
with a class of `content-block` rather than just using an article we
increased the specificity of the CSS selector. This means that the
standard list styling was overriding some of the styles which were being
added by the tab styles. This adds an extra selector to the tabs styles
so it now has a greater specificity than the standard list styling.
I have added an extra selector rather than just changing the selectors
because due to the way the JavaScript works it does checks on the styles
of the elements before it adds in the extra classes to work out if the
tabs should be shown as tabs or an accordion.
<table>
<tr>
<th>Before</th><th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Fix appearance of tabs within content-block

public/humans.txt
The previous URL was presumably the jobs page. This commit changes it to be the current one. 
I also have a bit of an issue with `developers and content designers` but thought I'd see how controversial that might be before changing it to something that reflects all the disciplines.
=> Change URL in humans.txt to one that doesn't 404

app/assets/javascripts/analytics/google-analytics-classic-tracker.js, app/assets/javascripts/analytics/google-analytics-universal-tracker.js, app/assets/javascripts/analytics/tracker.js, spec/javascripts/analytics/google-analytics-classic-tracker-spec.js, spec/javascripts/analytics/google-analytics-universal-tracker-spec.js, spec/javascripts/analytics/tracker-spec.js
* Add interface for classic and universal social media sharing. In universal the network, action and target are all required arguments.
* Create a specific public method on tracker for tracking social network shares (trackShare) which will be used by https://github.com/alphagov/whitehall/blob/master/app/assets/javascripts/application/document-share-links.js (see: https://github.com/alphagov/whitehall/compare/universal-social)
Social tracking docs:
https://developers.google.com/analytics/devguides/collection/gajs/methods/gaJSApiSocialTracking
https://developers.google.com/analytics/devguides/collection/analyticsjs/social-interactions
https://www.pivotaltracker.com/story/show/88174796
=> Track social media shares in Universal analytics

app/assets/javascripts/header-footer-only.js
The `analytics` code uses the `bind` polyfill so the polyfill must
come above it.
=> Move `bind` polyfill above `analytics`

app/views/root/_google_analytics.html.erb
In IE8 and below the minified inline javascript was inadvertently wiping out the GOVUK object, causing JS errors.
We aren’t sure exactly why it was wiping out the object, but by removing `var` and referring to window the error is eliminated.
Fix discovered by @edds after some excellent sleuthing.
=> Don't minify analytics initialisers in template

app/views/govuk_component/docs.yml, app/views/govuk_component/government_navigation.raw.html.erb
This commit adds a component for the government_navigation which contains only markup. This can be included anywhere on GOV.UK and will be lifted by Slimmer and placed into the header, appropriately styling it.
It can be passed a string assigned to active which will then mark the matching link as active. See the code for which strings are used.
This component is slightly odd as Slimmer will move it from the page the first instance it is included and it doesn't come with it's own CSS so the first example on the component view in the guide contains nothing and the second example contains an unstyled list.
Screenshot:
=> Add a component for /government navigation

app/assets/javascripts/analytics/static-tracker.js, app/views/root/_google_analytics.html.erb, spec/javascripts/analytics/static-tracker-spec.js
Related to https://github.com/alphagov/slimmer/pull/119
* Find `govuk:` namespaced meta tags and use the content of these tags to set dimensions
* Be explicit about what's being read and set
* Works with both old and new slimmer versions but can be simplified once apps are all on version 8.0.0 or greater
=> Set analytics custom dimensions from `govuk:` meta tags

app/assets/javascripts/analytics/static-tracker.js, spec/javascripts/analytics/static-tracker-spec.js
Documents in Whitehall that are political and published
by a previous government will be marked as historical.
This adds two new dimensions that will be used to track
content related to History mode, but they've been kept
a little more general, so they could be applied more
widely in the future.
The new dimensions are:
- PublishingGovernment, the government a document was
first published under (which may not be when it was
first published to GOV.UK)
- PoliticalStatus, whether a document is historic
(political and non current), political (political
and current) or apolitical
https://trello.com/c/fednKEAR/105-add-analytics-for-history-mode
Note: This re-orders the tests slightly, so the argument IDs and dimension IDs are both increasing. This feels a bit brittle, and generates noise in the …
=> Add Analytics dimensions for History Mode

app/assets/javascripts/analytics/static-tracker.js, spec/javascripts/analytics/static-tracker-spec.js, spec/javascripts/helpers/SpecHelper.js
* Based on an existing technique that sets a GOVUK cookie but which needed classic GA parameters to work
* Instead use `callOnNextPage` which sets a method to call on the `analytics` object with an array of parameters to pass to it
* Use JSON stringify and parse to save method name and parameters
* Call the requested method before the initial pageview, allowing for custom variables to be set from a prior page (as is the current use case)
Example of usage replacing old approach in frontend:
https://github.com/alphagov/frontend/compare/next-page-analytics
(Once the frontend change is merged and deployed, the remaining shims within static can be deleted)
=> Mechanism for making analytics calls on next page

app/views/root/_footer_support_links.html.erb
Reverts alphagov/static#562
Research was actually inconclusive - awaiting new link label.
=> Revert "Change Cymraeg link label"

app/assets/javascripts/govuk-component/option-select.js, spec/javascripts/govuk-component/option-select-spec.js
In research on the Digital Marketplace we have seen users not realise that the option-select has more options than those visible.
On certain combinations of browsers/operating system/number-of-lines-per-option it isn't clear that the component is scrollable. This is because the `max-height` of the container lines up with the bottom edge of the last visible option.
This pull request adds Javascript to adjust the height of the container so that the first line of the last visible option is always cut exactly in half horizontally.
Before | After
--- | ---
It also works when the options wrap to multiple lines:
I'd especially like to know:
- If there's a more thorough way to test this, without going as far as re-writing the logic from the component in the tests
- If you can understand what the …
=> Provide additional visual cue that option-select is scrollable

app/assets/javascripts/analytics/static-tracker.js, spec/javascripts/analytics/static-tracker-spec.js
__Do not merge until https://github.com/alphagov/frontend/pull/777 is deployed__
The technique for setting analytics calls for a following page was updated in https://github.com/alphagov/static/pull/560 and uses of the old technique updated in https://github.com/alphagov/frontend/pull/777.
* Remove shim
* Simplify tests
=> Remove custom variable in a cookie shim

spec/javascripts/govuk-component/option-select-spec.js
The Jasmine tests were failing on the command line with the following error:
```
GOVUK.OptionSelect setupHeight expands the checkbox-container just enough to cut the last visible item in half horizontally, if there are many items
Expected 29 to be greater than 100.
Error: Expected 29 to be greater than 100.
```
This test was, however, passing in the browser test runner.
The inconsistency is because of a difference between viewport sizes in the browser and command line test runners, which caused text to break onto a new line at different points. This pull request addresses this inconsistency by explicitly setting the height and width of the checkbox container in the failing test.
=> Fix failing test around option select

app/assets/javascripts/analytics/static-tracker.js, app/views/root/_google_analytics.html.erb, app/views/root/_javascript.html.erb, spec/javascripts/analytics/static-tracker-spec.js
Now slimmer uses meta tags to convey page metadata and all apps have been updated to the latest slimmer (and deployed), the inline `<script>` tag and shims for resetting the original `_gaq` queue can
be removed.
This also removes the last uses of the `GOVUK.Analytics` namespace.
cc @benilovj
=> Remove analytics slimmer shims

app/views/root/_footer_support_links.html.erb
- Research shows users think clicking the "Cymraeg" link will take
them to a translated version of the page they are on, rather than a
specific list of services GOV.UK has translated into Welsh. The
phrase "Rhestr o Wasanaethau Cymraeg" better describes the nature of
the page users are taken to.
Before:
After:
(The link text wraps "Built by the Government Digital Service" onto a new line, but according to the designers on our team, this is fine.)
=> Change the text of the "Cymraeg" link in the footer

Gemfile.lock
I was seeing the following error when running `bundle install`:
Unable to find a compiler officially supported by v8.
It is recommended to use GCC v4.4 or higher
Using compiler: g++
This then seems to have resulted in the following compilation error:
../src/cached-powers.cc:136:18: error: unused variable 'kCachedPowersLength' [-Werror,-Wunused-const-variable]
static const int kCachedPowersLength = ARRAY_SIZE(kCachedPowers);
^
I believe the problem was [fixed][1] between version 3.16.14.3 and version
3.16.14.7 of libv8 and a simple `bundle update libv8` seems to have done the
trick.
[1]: https://github.com/cowboyd/libv8/pull/124
=> Update libv8 to fix error on bundle install on OS X Yosemite

app/assets/javascripts/govuk-component/option-select.js, spec/javascripts/govuk-component/option-select-spec.js
Browsers maintain the scroll position of an option select even when they are closed. This confuses the code that tries to calculate the height of the container to cut off the last 'visible' item.
For some scroll positions this causes the container to get progressively shorter each time it is opened.
To fix this the option select should only have its height set once, the first time it is opened.
=> On option select, only set height one time

app/assets/javascripts/report-a-problem.js, app/assets/stylesheets/helpers/_report-a-problem.scss, app/views/root/report_a_problem.raw.html.erb, spec/javascripts/report-a-problem-spec.js
On specified pages, create a multivariate test showing a new report a problem design.
The design:
* collects quantitative data about the page's usefulness which gets sent to Google Analytics
* analytics also tracks opening and closing of original form on test pages, and successfully submitted feedback for both variants
* hides the yes/no links and asks for more details about problems
* forms are still submitted to the same endpoint, but the "what doing" field is pre-filled and hidden
cc @binaryberry @benilovj
=> AB test “Report a problem” design

app/assets/javascripts/report-a-problem.js
A code from an older experiment was being used by mistake.
/cc @fofr
=> Fix the experiment code in report-a-problem redesign test

app/assets/stylesheets/govuk-component/_previous-and-next-navigation.scss, app/views/govuk_component/previous_and_next_navigation.raw.html.erb
This fixes the mismatch between the 'title' and 'label' classes
and the interface of the component. The component interface stays
as before.
=> Fix style names for the previous/next component

Gemfile, Gemfile.lock, app/assets/javascripts/analytics/static-tracker.js
This adds the cross domain tracking functionality from https://github.com/alphagov/govuk_frontend_toolkit/pull/185 to static, making it globally available.
=> Add cross domain tracking

public/robots.txt
Content under /apply-for-a-licence/ should be blocked from robots,
because we want people to access it via the license start pages (eg, via
https://www.gov.uk/temporary-events-notice/westminster/apply for
https://www.gov.uk/apply-for-a-licence/temporary-event-notice/westminster/apply-1)
which have more explanatory content, and rank well in search.
However, robots.txt exclusions are prefixes, so this line was also
banning https://www.gov.uk/apply-for-a-licence-to-use-an-orphan-work
from being indexed.  In turn, this was causing search engines such as
Google and Bing to display a description for this page of "A description
for this result is not available because of this site's robots.txt".
Further, Bing was attempting to guess a title from the URL and other
off-page information, and was …
=> Fix robots blocking of /apply-for-a-licence

app/assets/stylesheets/govuk-component/_option-select.scss
The positioning isn't needed and it's very broken in ie6. I know we don't technically support ie6 anymore, but this is an easy fix that removes something that was added in error and takes the component from being unusable in ie6 to working.
Before
After
=> Remove absolute positioning from option-select

app/assets/javascripts/report-a-problem-form.js
This trailing comma is throwing errors in ie7 and 6 causing none of the
JavaScript to work in dev for those browsers. Luckily the minification
used on the live site strips the commas out anyway so this is only an
issue in development.
=> Remove trailing comma from JS

app/assets/javascripts/govuk-component/option-select.js, app/views/govuk_component/docs.yml, app/views/govuk_component/option_select.raw.html.erb, spec/javascripts/govuk-component/option-select-spec.js
So that clients of this component can specify if the option-select is
open or closed on load. This PR makes the default open, requiring
a parameter (`closed_on_load`) to be set to true if the component 
should be loaded as closed instead.
In http://github.com/alphagov/finder-frontend / http://gov.uk/cma-cases 
(which is the first client of this component) the first option-select on the 
page load is open with has the rest closed.
This PR:
- Adds a new optional parameter: `closed_on_load`.
- Adds a fixture to the docs for `closed_on_load`
- Changes the view to append a data-attribute `data-closed-on-load`
which is then read by the JavaScript and used to determine if the
option-select should call `.close()` on itself at the end of
initialisation
- Refactors the specs for `.open()` to handle …
=> Add close on load to govuk-option-select

app/assets/javascripts/report-a-problem.js, app/assets/stylesheets/helpers/_report-a-problem.scss, app/views/root/report_a_problem.raw.html.erb, spec/javascripts/report-a-problem-spec.js
The test has now run for several weeks and has generated more than enough data to allow us to judge the goodness of the new design.
This is a direct revert of the two PRs that added the new design.
/cc @fofr
=> Remove the multivariate test of the alternate "report-a-problem" design

app/assets/javascripts/analytics/static-tracker.js
The rendering application is being set in a meta-tag. Send this
information to Google so we can start segmenting data by it.
This makes use of this slimmer change: https://github.com/alphagov/slimmer/pull/126
=> Track rendering application

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
Need ID data isn’t being used. Allow dimension slot to be re-used for other data.
(The Need ID dimension was missed when we were deprecating unused dimensions back in February)
=> Stop tracking Need IDs as custom dimensions

Gemfile, Gemfile.lock
4.0.1 fixes the beta label to be multiline.
Related: https://github.com/alphagov/govuk_frontend_toolkit/pull/197
Trello: https://trello.com/c/H9UMp051/139-allow-topic-subtopics-to-be-labelled-as-beta
=> Upgrade govuk_frontend_toolkit gem

app/views/govuk_component/option_select.raw.html.erb, app/views/govuk_component/previous_and_next_navigation.raw.html.erb
This is a transitional change to switch components that expect
string key'd objects to handle symbol key'd objects only.
We should only use one style of keys for objects used in components,
to avoid reduce confusion when using components (I spent a while
trying to work out why the arguments I was passing to prev/next
weren't rendering). Consistency is good.
After discussion with @edds we agreed to use symbols consistently,
as this makes more sense in a ruby/rails environment.
The first step is to support both, as clients of those components
will still be sending string key;d objects and can't be updated
at the time as this app, so we have to;
1. Support both kinds of keys on components that expect strings
2. Update [clients sending string …
=> Support symbol and string keys for some components

app/views/govuk_component/option_select.raw.html.erb, app/views/govuk_component/previous_and_next_navigation.raw.html.erb
This removes transitional change that supported accessing by string
or symbol key.
Once clients calling components with string keys have been updated
to use symbol keys this can be merged.
Related:
- https://github.com/alphagov/finder-frontend/pull/217
- https://github.com/alphagov/manuals-frontend/pull/147
It's worth reading the discussion on the PR that added the transitional support for either kind of key, it outlines the reasoning there: https://github.com/alphagov/static/pull/601
=> Only support symbol keys in component arguments

app/views/root/_base.html.erb
The link in the footer on still goes to /visas-immigration
which redirects to /browse/visas-immigration.
This breaks the In-Page Analytics view in Google Analytics,
because the next page tracked doesn't match the link.
Updated to go directly to /browse/visas-immigration.
=> Update visa-immigration link

app/assets/stylesheets/govuk-component/_option-select.scss
Although the retina file is included in the project already, for some
reason I never actually added it. So, this commit uses the file.
Pivotal: https://www.pivotaltracker.com/story/show/97293160
Before:
After:
=> Fix retina bug for option-select arrows

doc/govuk-components.md
Some components templates in static were using symbol keys and 
others strings, which was inconsistent and confusing, by only using
symbols we avoid confusion.
Tools like the component guide have been updated so they will
obviously error when strings are used - previously it silently
corrected any string/key mismatch.
More here: https://github.com/alphagov/govuk-component-guide/pull/20
I just took some time cleaning things up to only use symbols, so it
seemed worth doc'ing somewhere. That said, i'm not sure this is a 
well phrased bit of documentation, would appreciate thoughts, 
especially from those who've made component changes, like 
@jackscotti or @alicebartlett.
=> Add doc note on keys vs string for objects

app/assets/stylesheets/govuk-component/_govspeak.scss
When writing content and converting to govspeak, the `.last-child` class isn’t automatically added to the last `<p>` tag in a `<blockquote>`. Only Whitehall currently does this
* Use the last-child pseudo selector to enable end quotes on all apps
A closing quote will not show on IE8 (no `:last-child` support), which currently represents 3.5% of pageviews.
https://trello.com/c/tTYHNfWt/7-closing-quotations-marks-should-show-in-manuals-small
cc @edds
=> Show closing quote on govspeak blockquotes

app/views/root/related.raw.html.erb
The aside element lets you mark content on the page which is
complementary to the page. This lets screen readers and other assistive
technology announce to the user that the content isn't part of the main
body of the page.
In user research we have seen users accidentally enter the related
sidebar without realising and assuming that they are still in the main
body of the page. This should help those users.
=> Wrap the related sidebar in an aside

lib/tasks/router.rake
Nothing uses this route. The fonts are actually embedded in the
stylesheets using data-uri's. The fonts for IE8 are served through the
assets vhost under the /static/fonts path. There's nothing in this
application that serves anything from the /fonts path.
Another note, some of the handling for this route was removed in
https://github.gds/gds/puppet/pull/1153
=> Remove registration of /fonts route.

app/views/root/_base.html.erb
This relies only on the DRAFT_ENVIRONMENT envvar
being set rather than being set to 'true'.
=> Trigger draft watermark differently.

app/assets/javascripts/report-a-problem-form.js, spec/javascripts/user-satisfaction-survey-spec.js
* Switch from `.live` to `.on` 
* Use `prop` over `attr` for disabling/enabling buttons
Identified in https://trello.com/c/wVQ2q3Mr/22-spike-how-can-we-upgrade-jquery-on-static-2-days
cc @edds
=> Switch away from deprecated jQuery methods

app/views/root/related.raw.html.erb
Having link text the same as the title makes reading the link out really
repetitive for a screen reader user as it will read the same text twice.
Remove the repeated text as you get all the content you need from the
link text.
=> Remove link titles

app/views/root/_base.html.erb
Adds the link to the new "Childcare and parenting" browse page in the footer.
Trello: https://trello.com/c/KRe96Tvd/236-add-links-to-childcare-and-parenting-to-homepage-and-footers
:no_entry_sign: Don't merge until this new page has been published (scheduled for today).
=> Add Childcare and parenting link in footer

app/views/govuk_component/option_select.raw.html.erb
If we have 2 option select components rendered on a page which have an
option in each with the same slug, these will be used as the id on the
input. This will then cause Nokogiri to throw an error in Slimmer and
not render the page.
This commit changes the option select component to prefix the option
value with the key (`key-slugified-value`).
=> Prefix option select option id attr with key

app/assets/stylesheets/helpers/_report-a-problem.scss
In Whitehall, link styles are wrapped in a #whitehall-wrapper class, so they have a higher specificity, meaning they are purple (there's no href, so the link is deemed visited) and not underlined (Whitehall link styles are currently inconsistent with the rest of GOV.UK – see https://github.com/alphagov/whitehall/pull/712)
* Make sure the link is always grey and always underlined, `!important` ensures this
=> Make report a problem link always underlined and grey

app/assets/stylesheets/helpers/_text.scss
Place information rendered from imminence on frontend
e.g. www.gov.uk/find-atf-dvsa-test-station lists email, website and phone
information for each found place. Labels and values for contact info is rendered
on separate lines (see example below).
With equal spaces between the lines it looks rather messy. I tried finding
design guidelines for cases like this but the only thing I found was mainstream
styleguides for contacts
https://github.com/alphagov/govspeak/wiki/Using-govspeak-on-GOV.UK#contacts.
As far as I can tell the CSS I have changed is only used in that one place I
intend to change. I also intend to remove Email and Website labels from the
frontend app to conform to these guidelines.
The commit that introduced the current style is e6f4153969473a1df870f47df810c3068598c3a6
Before: …
=> Improve contact information layout for place options

Gemfile, Gemfile.lock, app/assets/javascripts/analytics.js, app/assets/javascripts/analytics/static-analytics.js
Following on from https://github.com/alphagov/govuk_frontend_toolkit/pull/208
https://trello.com/c/ihxFfLWH/70-create-simplest-external-link-and-download-tracker-medium
> This is a minimum viable tracker. It will work as expected in Chrome and Firefox – browsers that support navigator.sendBeacon, about 30% of all users. On older browsers we will still send analytics events, and we'll receive some data, but not all events will make it to GA and the dataset will be incomplete. We will however be able to estimate what proportion of events we're missing based on the complete Chrome and Firefox datasets – those estimates can be used to prioritise and influence a more complex solutions.
>
>A fully-formed tracker would include, in older browsers, a means of preventing the page from loading until …
=> Add download and external link tracking

Gemfile, Gemfile.lock
Pick up changes to download link tracker from https://github.com/alphagov/govuk_frontend_toolkit/pull/214
> Events show a user intent, but are less likely to be interpreted incorrectly – it shows that a user clicked a link on a page, rather than the file was successfully downloaded and viewed.
>
> It should avoid inflating our pageview numbers, prevent an increase in our cardinality and leave open a more complete pageview tracking solution from logs (eg for direct downloads).
=> Track downloads with events not pageviews

Gemfile, Gemfile.lock, app/assets/stylesheets/guides-print.scss, app/assets/stylesheets/helpers/_core-print.scss, app/assets/stylesheets/print.scss
Tidy the core print styles, and bump the govuk_template gem to pull in print amends from there.
=> Print style review

app/assets/stylesheets/helpers/_reset.scss
Firefox now supports text-decoration with a dotted underline; consequently (and inline with W3’s recommended default stylesheet) Mozilla [updated Firefox’s default stylesheet](https://bugzilla.mozilla.org/show_bug.cgi?id=1157083) to style abbrs and acronyms with a dotted text-decoration instead of a dotted border. Our reset stylesheet removes borders from abbr and acronym elements, but doesn’t reset text decoration. The upshot of all this is that every abbr on gov.uk now has dots underneath it.
This patch simply adds a rule to remove text-decoration from abbr and acronym elements. If text-decoration is being deliberately set anywhere it’ll override this base rule.
=> Remove abbr underlines in Firefox

app/views/govuk_component/analytics_meta_tags.raw.html.erb, app/views/govuk_component/docs.yml
Create a component which takes a links hash object from a content-store
object and turns that into a collection of meta-tags which can then be
read by our analytics JavaScript. This information in then sent to
Google as a custom dimension.
The component doesn't actually render anything visual so doesn't have a
corresponding stylesheet.
Would appreciate @dsingleton's thoughts on this.
=> Add analytics meta tag component

app/assets/stylesheets/govuk-component/_option-select.scss
We’re upping the size of checkboxes generally across the site. Originally this code just used  a negative margin-left to pull the checkbox to the left, but this also pulls the following text regardless of padding. By floating it left the following text will respect the padding boundary set against the label.
Most browsers look good, IE9 is the odd one out. It looks OK but is slightly out of position and cramped. I’m assuming we’ll go down the same route as on https://github.com/alphagov/govuk_elements/pull/98 though.
Screenshots:
*Chrome (Android)*
*Safari (iOS)*
*Chrome (OS X)*
*Firefox (OS X)*
*Safari (OS X)*
*IE8 (Windows 7)*
*IE9 (Windows 7)*
*Chrome (Windows 10)*
*Edge (Windows 10)*
*Firefox (Windows 10)*
*IE11 (Windows 10)*
*Opera (Windows 10)*
=> Up the size of the checkbox on option selects

app/helpers/notification_helper.rb, config/initializers/notification_banner.rb, lib/notification_file_lookup.rb, lib/static.rb, test/integration/notifications_test.rb, test/test_helper.rb, test/unit/notification_file_lookup_test.rb, test/unit/notification_helper_test.rb
The original intention of this refactoring was to remove stubbing from the banner integration tests (which has [caused intermittent test failures on CI](https://ci-new.alphagov.co.uk/job/govuk_static_branches/602/console)), but it pays down some tech debt on the way.
The highlights:
- simplification of the `NotificationFileLookup` class
- `NotificationFileLookup` is no longer a singleton (instead, a module attribute `Static.banner` is introduced to store the global state)
- `NotificationFileLookup` can be optionally passed a path where the banner templates can be found
- fix some nesting and duplication issues in `NotificationsTest`
- `NotificationsTest` no longer uses stubbing, creating and deleting real test template files instead
/cc @binaryberry @jamiecobbett @boffbowsh
=> Notification banner refactorings and test clean-up

Gemfile, Gemfile.lock, config/initializers/airbrake.rb, config/initializers/exception_notification.rb
Errbit is the current approach in our stack for tracking errors.
Related PRs:
- https://github.gds/gds/puppet/pull/3390
- https://github.gds/gds/deployment/pull/706
- https://github.gds/gds/alphagov-deployment/pull/1053
=> Replace exception_notification integration with Errbit/Airbrake

config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb
ActionMailer is no longer required since [`exception_notification` was replaced
by Airbrake integration](https://github.com/alphagov/static/pull/652).
H/T to @tijmenb for [picking this up](https://github.com/alphagov/static/pull/652#issuecomment-140791194) on https://github.com/alphagov/static/pull/652.
=> Don't wire up ActionMailer

Gemfile, Gemfile.lock, config/environments/production.rb, jenkins.sh
This is to fix a couple of issues introduced during the recent Rails 4.X upgrades:
- JS asset compression stopped working
- silence an overlooked deprecation warning
/cc @boffbowsh
=> Post-upgrade fixes

app/assets/stylesheets/govuk-component/_govspeak.scss, app/views/govuk_component/docs.yml, app/views/govuk_component/govspeak.raw.html.erb
As we need to have bold on certain pages of GOV.UK (the Highway Code)
this commit updates the Govspeak component to have extra CSS set by a
flag of `rich_govspeak`. This can be set by the rendering App.
Additional CSS could be added to this rich mode if we wish.
This has been discussed with both Product Managers, Content and
Designers and the approach I've followed was agreed upon.
[Ticket](https://trello.com/c/eYyOkNRR/131-highway-code-manual-has-styled-strong-tags).
=> Rich Govspeak with bold

app/assets/stylesheets/helpers/_report-a-problem.scss
At a breakpoint below 1020 the report a problem link, and form, weren't aligned to the grid of the rest of the page, and were indented by an additional 30px on each side.
This was caused by `%site-width-container` being used on the report a problem containers, within `#wrapper`, which already extends `%site-width-container`, causing double margins.
As the report a problem elements already inside a page width container it's same to remove the use of `%site-width-container` for them.
| 🌟  | Before | After |
| --- | --- | --- |
| Closed | ![report-before](https://cloud.githubusercontent.com/assets/63201/10373870/fc2bca12-6de7-11e5-9b23-8b870641a378.png) | ![report-after](https://cloud.githubusercontent.com/assets/63201/10373873/fc2d4c0c-6de7-11e5-8a8f-1c03bd60daeb.png) |
| Open | …
=> Fix alignment of report-a-problem at certain widths

app/views/govuk_component/docs.yml
Statistic headlines are in govspeak since 3.5.0.
They are only styled as big numbers in HTML publications.
See https://github.com/alphagov/whitehall/pull/2356 and https://github.com/alphagov/govspeak/pull/60
=> Add fixture for statistic headlines

app/assets/stylesheets/helpers/_report-a-problem.scss
We're seeing problems with the position of the report a problem link on various pages including the homepage and on Whitehall.
Reverts commit 6fa1eb582bcd75737b8277f0efa751c953f355e9, reversing
changes made to 52a5f91cfd9194393f37c8a234a85385481118bd.
Reverts #660 
cc @dsingleton @benilovj
=> Revert "Merge pull request #660 from alphagov/fix-report-a-problem-alignment"

app/views/govuk_component/docs.yml
The component doc page was erroring as the default fixture doesn't
have enough data to actually render the component, and was [erroring](http://govuk-component-guide.herokuapp.com/components/analytics_meta_tags)
on `content_item["links"] || {}`.
Replace the empty default with the first, that has the required
data.
Note; this component is unusual, in that it's highly coupled to the
structure of Content Items, and uses non-mustache compataible ERB
features, both of which kind of go against the principles of
components, and i'm not sure it's quite right. Or at least, if we're
going to do it, we should do it everywhere and save some pain.
=> Fix analytics component fixtures

app/views/govuk_component/docs/analytics_meta_tags.yml
The component expects a content item, and a fixture with no arguments
will A) isn't meaningful, and B) causes an error in the component guide
=> Remove broken analytics component fixture

app/views/govuk_component/docs/alpha_label.yml, app/views/govuk_component/docs/analytics_meta_tags.yml, app/views/govuk_component/docs/beta_label.yml, app/views/govuk_component/docs/document_footer.yml, app/views/govuk_component/docs/government_navigation.yml, app/views/govuk_component/docs/govspeak.yml, app/views/govuk_component/docs/metadata.yml, app/views/govuk_component/docs/option_select.yml, app/views/govuk_component/docs/previous_and_next_navigation.yml, app/views/govuk_component/docs/title.yml, lib/generators/govuk_component/templates/component.yml
The generator was creating a single item array, rather than a hash, due to the `-` and indentation. I just ran into this while testing a new component, but missed it in the original PR.
Remove unnecessary '---' from component YML docs. Despite Tommy's prodding in the previous PR (#664) I messed this up, the `---` isn't required, and is only inserted if you programatically write the YML files, which I did to convert the single YML file to the many smaller ones.
It's not required, and the generator wasn't creating it anyway, so we can drop it from the doc files, for simplicity's sake.
=> Remove unnecessary '---' from component YML, and fix generator

app/views/govuk_component/analytics_meta_tags.raw.html.erb, app/views/govuk_component/docs/analytics_meta_tags.yml
Fixtures/the component guide generate an object with symbol keys,
as this is the convention of GOV.UK components, as we had confusion
between symbol and string keys, see:
https://github.com/alphagov/static/pull/602
Analytics Metadata is an exception, because it's passed ContentItem
object directly from the `content_store` API, which will always
have string keys.
This also changes the structure of link sub-hashes to match the
structure expected by the component template, specifically, it
expects a field called `analytics_identifier` for a link, not the
link to have that as it's value.
=> Fix Analytics Metadata component use with fixtures

app/views/govuk_component/analytics_meta_tags.raw.html.erb
Follow up to https://github.com/alphagov/static/pull/668/
With real Content Items, rather than fixtures, the object will be
a `GdsApi::Response` object, which doesn't support `with_indifferent_access`
and would break for an app passing that in.
Instead of trying to make the fixtures/content item both response to string
keys, which is an exception to the component style guide, ensure the
content item keys are all symbols, by casting to a hash.
For fixtures, this will be a no-op, for the API response it will switch to
a symbol-key'd hash, the rest of the template can then deal only with
symbol key'd hashes.
IMO this is a cleaner fix, as it also further removes the main bit of
component logic from the specific structure/object of a content item
=> Fix AnalyticsMetadata component in a better way

app/assets/stylesheets/helpers/_webchat.scss
We’d missed a hidden overflow in the original version, which was leaving the white text unnoticed on top of the main content. The links could then be clicked, which would result in a JS error.
=> Make the webchat unable to be interacted with, when closed

app/assets/javascripts/webchat.js.erb
The banner was being appended before the shouldOpen() check. This moves the insertion point calculation and banner appending to after that.
=> Only apply the web chat banner to pages it’s required on

app/views/govuk_component/analytics_meta_tags.raw.html.erb, test/govuk_component/analytics_meta_tags_test.rb
https://trello.com/c/2LJAtceC/156-new-world-analytics-component-medium
Allow format and Need IDs to be tracked to Google Analytics through the existing component.
Matches the format that "old world" frontends are using via Slimmer:
https://github.com/alphagov/slimmer/blob/master/lib/slimmer/processors/metadata_inserter.rb
cc @jamiecobbett @dsingleton
=> Add format and need-ids to analytics component

app/assets/javascripts/analytics/scroll-tracker.js
Scroll tracking is needed for the HTML content page rather than the splash page that hosts various formats (html, PDF, print etc) of content.
=> Update scroll-tracking URL for the autumn spending review statement

app/views/govuk_component/previous_and_next_navigation.raw.html.erb, test/govuk_component/beta_label_test.rb, test/govuk_component/document_footer_test.rb, test/govuk_component/government_navigation_test.rb, test/govuk_component/govspeak_test.rb, test/govuk_component/metadata_test.rb, test/govuk_component/option_select_test.rb, test/govuk_component/preview_and_next_navigation_test.rb, test/govuk_component_test_helper.rb
https://trello.com/c/NLkm3EDy/17-unit-test-components
Includes:
* Beta label
* Govspeak
* Pagination
* Government navigation
* Document footer
* Option select
* Metadata
Also adds some test helpers for making future component unit tests easier, eg
```ruby
def assert_link_with_text(link, text)
assert_select "a[href=\"#{link}\"]", text: text
end
```
cc @dsingleton @jamiecobbett
=> Add unit tests for all existing components

app/assets/javascripts/webchat-iframe.html.erb
Jonathan Charlton at kcom provided this new URL to load the script from. Checking in the network panel in-browser shows this URL returning a 200 and what looks like the necessary script.
I’m yet to see an offer appear, but this is likely due to lack of operators.
=> Update webchat URL to point at HMRC

app/assets/javascripts/webchat-iframe.html.erb
When the version of eGain changed it altered the selector that we need
to look for to see if the offer has been opened. This brings it in line
to what is in production.
=> Update offer selector to match new eGain version

public/robots.txt
I'd prefer to slow this bot down rather than blocking it completely but documentation for the bot doesn't indicate that it supports the crawl-delay property.
They describe themselves as a:
> site architecture analysis tool used by SEOs and web developers
Users won't be using this to find GOV.UK, so we can safely block it at the moment.
=> Block deepcrawl bot

app/views/govuk_component/docs/govspeak.yml
Youtube links in govspeak will be converted into an embedded video
player.
Add an example of this to the fixtures for the govspeak component.
**Screenshot from local copy of `govuk-component-guide`:**
=> Add YouTube embed example to Govspeak Component

doc/govuk-components.md, lib/generators/govuk_component/USAGE, lib/generators/govuk_component/govuk_component_generator.rb, lib/generators/govuk_component/templates/component_test.rb.erb
When generating a component include a unit test.
The basic unit test asserts that the component template renders with the expected `govuk-` class and that no errors are thrown when no parameters are passed in. It’s modelled on the alpha_label_test.
Includes documentation about component unit tests
https://trello.com/c/NLkm3EDy/17-unit-test-components
cc @dsingleton
=> Add component unit test to component generator

app/assets/javascripts/webchat-iframe.html.erb
The iframe was relying on finding an element with a specific id in the offer markup loaded from KCOM. At some point recently they have updated their markup with a new id, causing the offer to fail to load.
This changes the code such that it now just looks for the first div inside the body rather than relying on a specific id which appears likely to change in future.
=> Fix HMRC webchat offer

app/assets/javascripts/webchat-iframe.html.erb
The ids on the buttons have also changed. This changes the selectors to use an ends-with attribute selector which should be resilient if the id’s value changes again.
=> Fix webchat buttons

app/assets/javascripts/webchat-iframe.html.erb
The line in isOfferOpen was checking for whether the whole body
was hidden and not the chat invite div's visibility. Now it is checking
for the ribbonContainer's visibility and should return the correct value
for whether an offer is open.
=> Bug fix: "I'm not interested" button doesn't close banner

app/assets/javascripts/webchat.js.erb
As requested by HMRC, these two outcome pages from smart answers need
webchat assistance. The only change here is making the script load the
iframe on those two paths in addition to the self-assessment page.
=> Add two new paths where webchat is available

app/assets/javascripts/webchat.js.erb, spec/javascripts/hmrc-webchat-spec.js
Webchat has been working on 1 out of the 3 pages because only one has a
.beta-wrapper element. The headers also have different class names on
different pages so I decided to point the selector to a fairly
consistent #content element.
=> Change insertion point selector so webchat banner appears on new pages

app/assets/stylesheets/govuk-component/_breadcrumbs.scss, app/assets/stylesheets/govuk-component/_component.scss, app/views/govuk_component/breadcrumbs.raw.html.erb, app/views/govuk_component/docs/breadcrumbs.yml, test/govuk_component/breadcrumbs_test.rb
> __Navigational breadcrumbs, showing page hierarchy.__
> Accepts an array of breadcrumb objects. Each crumb must have a title and a URL.
Create a breadcrumbs component based on 20505dd, existing markup, and existing styles in `_header.scss`. Includes a couple of changes:
* Removes `strong` styles as those don’t appear in the markup
* Tweak the styles for better display in IE8 and below
https://trello.com/c/lNdlHrdq/235-component-creation-breadcrumbs-medium
cc @dsingleton @steventux
=> Create a breadcrumb component

app/assets/stylesheets/govuk-component/_component-print.scss, app/assets/stylesheets/govuk-component/_component.scss, app/assets/stylesheets/govuk-component/_related-items-print.scss, app/assets/stylesheets/govuk-component/_related-items.scss, app/views/govuk_component/docs/related_items.yml, app/views/govuk_component/related_items.raw.html.erb, lib/generators/govuk_component/templates/component.yml, test/govuk_component/related_items_test.rb
> __Headed sections of related items.__
> Accepts an array of sections. Each section can have a title, url, id and a list of related items.
> Each item is a hash with a title and url. If the url is external, a rel value can also be provided.
Create a related-items component based on188e526 and on [core stylesheets](https://github.com/alphagov/static/blob/master/app/assets/stylesheets/helpers/_core.scss#L56-L147)
Care must be taken when using the component so that navigation is always
correctly labelled (pattern based on http://tink.uk/screen-readers-aria-roles-html5-support/). When passing in a section id, use this to add an id attribute and a labelledby attribute. This is in favour of generating an id (eg. by parameterising the title) so that the component isn't using rails specific …
=> Related items component

Gemfile, Gemfile.lock, lib/tasks/publishing_api.rake
https://trello.com/c/tx50hSOx/492-add-bearer-token-value-to-all-apps-using-publishing-api
=> Use bearer token for publishing-api authentication

app/assets/javascripts/webchat.js.erb
Includes a new path to said page as requested by HMRC in white_list
array. Tested code on the page where it loaded the iframe and JS when
running contacts-frontend locally.
=> Load Webchat iframe on HMRC Contact-us page

app/assets/javascripts/libs/suchi/isOld.js
Add a test for IE10’s user agent (https://blogs.msdn.microsoft.com/ie/2012/07/12/ie10-user-agent-string-update/) as it goes out of support on 12/1/2016.
cc @tombye
=> Warn IE10 users that they’re out of date

Gemfile, Gemfile.lock, jenkins.sh, jenkins_schema.sh, test/govuk_component/analytics_meta_tags_test.rb, test/govuk_component_test_helper.rb
Verifies the analytics component against the example case study document in the content schemas project. So far, we only integrate with a single case study example. Ideally we'd integrate with as many different examples as possible, but before this can happen we'll need a way of expressing just which capabilities or attributes each component requires from the example documents.
I'll complete the CI configuration to ensure that content schema commits are triggering builds over here, once this is merged.
=> Validate analytics against schemas

app/views/root/_footer_support_links.html.erb
- It was advised that we include this link prominently in the (rare)
event of legal action against us for something on the site.
Trello:
https://trello.com/c/cZrYVw6E/258-gov-uk-terms-and-conditions-need-to-appear-in-the-footer
=> Add a link to GOV.UK's Terms and Conditions to the footer

app/assets/stylesheets/helpers/_layouts.scss
The class for 2/3 columns is `column-two-thirds`, but the 1/3
column class is `column-third`, which has led to me using
`column-one-third` in templates a few times and being confused
why it doesn't work.
Add `column-one-third` as an alias, for ease of use.
Related: https://github.com/alphagov/govuk_elements/pull/127
=> Add an alias for 1/3 width column class

app/assets/javascripts/user-satisfaction-survey.js, spec/javascripts/user-satisfaction-survey-spec.js
Trello: https://trello.com/c/DEStHomZ
Displays the temporary survey link between 26/01 and 27/01. The approach isn't particularly nice, but this is entirely temporary and will be reverted once the survey window closes.
This was previously done (#689) in the ERB template, but during that particular survey window we had some problems with caching. The trello card alludes to this, for reference.
=> Temporary survey

app/assets/javascripts/user-satisfaction-survey.js, spec/javascripts/user-satisfaction-survey-spec.js
Trello: https://trello.com/c/DEStHomZ
There was an issue with the first implementation in that the date portions were ordinal and didn't take into account JavaScript's months being zero-based. This resolves that issue and another issue regarding `Date.now()` IE8 incompatibility.
=> Alter dates for temporary survey period

app/views/govuk_component/breadcrumbs.raw.html.erb, app/views/govuk_component/docs/breadcrumbs.yml, test/govuk_component/breadcrumbs_test.rb
User testing conducted by the Service Manual team has shown that users understand breadcrumbs better when the last breadcrumbs element references the current page, thus giving the user a mental anchor.
Allow passing in a breadcrumb hash with no URL that renders it as a text element. Only the last breadcrumb element should be text-only. There are not checks in code to enforce it, so it's left to a developer of each application.
However we should discuss if we want to allow different application developers to deviate from what is currently on GOV.UK.
=> Allow text-only breadcumbs

app/views/govuk_component/breadcrumbs.raw.html.erb, app/views/govuk_component/docs/breadcrumbs.yml, test/govuk_component/breadcrumbs_test.rb
Allow passing in `include_home: false` to omit the first 'Home' breadcrumb.
Some formats e.g. Service Manual require the root breadcrumb to link to `/service-manual` rather than GOV.UK root.
=> Make 'Home' breadcrumb optional

app/assets/javascripts/govuk-component/option-select.js
When this element is used with forms, pressing enter on a textbox within the same form triggers a synthetic mouselick event on the nearest button in the form.
Adding type button to the button element overrides the button default type of submit within the form.
=> Add button attribute to button element

spec/javascripts/user-satisfaction-survey-spec.js
Now we're in the survey window, these tests were failing as the
alternative URL is mandated. These modifications ensure the tests run
outside the temporary date window.
=> Fix date-dependent tests

app/assets/stylesheets/govuk-component/_component.scss, app/assets/stylesheets/govuk-component/_document-footer.scss, app/assets/stylesheets/govuk-component/_govspeak.scss, app/assets/stylesheets/govuk-component/_metadata.scss, app/assets/stylesheets/govuk-component/_option-select.scss, app/assets/stylesheets/govuk-component/_previous-and-next-navigation.scss, app/assets/stylesheets/govuk-component/_title.scss, app/assets/stylesheets/govuk-component/mixins/_margins.scss, app/assets/stylesheets/helpers/_core.scss
This work follows the principles:
* Include a sensible default margin so that pages can be built quickly with the same vertical spacing
* Removing a margin is easier than adding one
* A sensible default usually looks like a consistent bottom margin
* Top margin should be used sparingly. A good exception is the title component.
Changes to components:
* Remove an unused margin styles from the previous and next component (two apps use it, one was unnecessary, the other was overriding)
* Use responsive top and bottom margins on title, increasing spacing from 30px to 45px
* Add default bottom margin to document footer – this is not responsive as the larger space is useful in separating footer from content at thinner page widths. Once deployed the app specific style in government-frontend can …
=> Standardise margins on components

app/assets/stylesheets/govuk-component/_govspeak.scss
* Use 20px margins (15px at thinner viewports) to match GOV.UK elements. This improves the legibility of content that contains many medium to long paragraphs, it comes at the cost of legibility for content with groups of one line paragraphs, mainly specialist content.
* Add spacing between list items, 5px – matching GOV.UK elements
* Use bold mixins
* Clean up call to action styles
cc @dsingleton @gemmaleigh @alextea 
(The more spaced out examples in the GIFs are the new margins)
* Better legibility on content with long paragraphs
* Clearer spacing at thinner viewports
* Better positioning of call to action when it's the first piece of content
* Better padding on call to action
=> Increase margins between text in govspeak component

app/assets/javascripts/header-footer-only.js, app/assets/javascripts/start-modules.js
Static will now start any govuk_toolkit modules available on the page.
Further info about the modules can be found [here](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/docs/javascript.md#modules).
=> Add starting of govuk_toolkit modules

config/environments/development.rb
This allows be run more easily in more situations;
- On the VM, but not under `bowl`, eg, `bowl frontend --without static` and
running static in another tab (which is common).
- Outside the VM, setting `PLEK_SERVICE_STATIC_URI=http://localhost:3013`,
which is also a common use pattern outside the VM.
Ideally `static` would generate absolute, including host, URLs for
assets and avoid needing the extra additional Plek service ENV var, but
this fixes the two issues described above for now
CC @erikse who was having this issue too, and @alext who I discussed the fix with.
=> Fallback to static host if GOVUK_ASSET_ROOT not set

app/assets/javascripts/analytics.js, app/assets/javascripts/analytics/static-analytics.js
This PR enables the `GOVUK.analyticsPlugins.mailtoLinkTracker` function merged in to the analytics JS of `govuk_frontend_toolkit`.
It requires version 4.7.0 of the  `govuk_frontend_toolkit` gem, which is the current version in the Gemfile.
=> Enable click event tracking on mailto links

app/views/govuk_component/breadcrumbs.raw.html.erb
`role="breadcrumbs"` is not a thing.
https://www.w3.org/TR/wai-aria/roles#role_definitions
cc @alextea @robinwhittleton
=> Remove invalid ARIA role

app/assets/stylesheets/govuk-component/_govspeak-print.scss, app/assets/stylesheets/govuk-component/_govspeak.scss, app/views/govuk_component/docs/govspeak.yml
**Successor to https://github.com/alphagov/static/pull/742, which I couldn't re-open due to a force push :disappointed:**
As part of migration we are moving formats from WH to `content-store` and `government-frontend`. Some of the formats in WH have `body` content that includes embedded attachments, eg, markup describing an attachment in the rendered HTML of a document from content-store.
To render this in a new-world frontend app, like government-frontend the `govspeak` component, that renders a documents `body` content, needs to be able to add styling and behaviour for the attachment markup in the `body`.
This PR adds examples of attachments within govspeak, and ports the CSS/JS that renders them/adds toggling behaviour, to the govspeak component on static.
- Includes changes to work …
=> Govspeak attachments

app/assets/stylesheets/govuk-component/_govspeak-print.scss
**Media player**
| Before | After |
| --- | --- |
|  ![screenshot 2016-02-25 15 00 39](https://cloud.githubusercontent.com/assets/63201/13323296/b52940f2-dbd0-11e5-85ba-b4f06e57e915.png) | ![screenshot 2016-02-25 15 01 03](https://cloud.githubusercontent.com/assets/63201/13323295/b52929be-dbd0-11e5-9821-2271ff68e021.png) |
This is a lot less, but there's not a lot of benefit to including any part of the player in print.
**Callouts**
| Before | After |
| --- | --- |
| ![screenshot 2016-02-25 14 59 52](https://cloud.githubusercontent.com/assets/63201/13323318/ca1736cc-dbd0-11e5-8311-6b7e19cb5e18.png) | ![screenshot 2016-02-25 14 59 12](https://cloud.githubusercontent.com/assets/63201/13323317/ca15c21a-dbd0-11e5-942d-0b737b50d832.png) |
=> Improve Govspeak component print styles

app/assets/stylesheets/govuk-component/_component.scss, app/assets/stylesheets/govuk-component/_govspeak-html-publication.scss, app/assets/stylesheets/govuk-component/_govspeak.scss, app/views/govuk_component/docs/govspeak.yml, app/views/govuk_component/docs/govspeak_html_publication.yml, app/views/govuk_component/govspeak_html_publication.raw.html.erb, test/govuk_component/govspeak_html_publication_test.rb
Create a nested component, an HTML publication wrapper calls the govspeak component and overrides styles specific to the format. It also includes a width constraint for handling large floating numbers that HTML publications use.
Nested components only work with Slimmer 9.1.0 and above.
* Port HTML publication number styles from Whitehall
* Include stat-headline styles in govspeak component
* Switch from right-to-left mixin to `direction-rtl` class
* Improve right-to-left rendering of HTML publications
* Tie tests to govspeak ones so that the two components don't diverge
* Fix alignment bug in current HTML publications (inline-block switched to position absolute)
=> Create HTML publication flavour of the govspeak component

app/assets/stylesheets/govuk-component/_govspeak-print.scss, app/views/govuk_component/docs/govspeak.yml
The styling already existed, having been ported from Whitehall
when the Govspeak component was first created.
The migration of HTML Publications to `government-frontend` means
the fractions SCSS in the component will be used in production and
we should have some examples of how they render, to illustrate the
pattern and make testing regressions easier.
This also improves the print styling of fractions.
**Image based fractions**
| Screen | Print |
| --- | --- | 
| ![image_fractions](https://cloud.githubusercontent.com/assets/63201/13328965/79f73fb6-dbe9-11e5-908a-3f61d2327343.png) | ![image fractions print](https://cloud.githubusercontent.com/assets/63201/13328966/79f7ddc2-dbe9-11e5-88b2-402866b2c739.png) |
**Text based fractions:**
| Screen | Print |
| --- | --- | 
| …
=> Add Govspeak fraction examples

app/views/root/scheduled_maintenance.html.erb
This file is currently [hardcoded in the Puppet repo][1] which is definitely not the correct place for it for lots of reasons. It should be a view in static similar to our error views.
[1]: https://github.com/alphagov/govuk-puppet/blob/d717279c28008e54c0cabab2bd058306301344a8/modules/loadbalancer/templates/usr/share/nginx/html/maintenance_page.erb
=> Add scheduled maintenance view

app/assets/javascripts/analytics/scroll-tracker.js
Have added header scroll tracking to the following pages:
/openingupwork
/guidance/common-technology-services-cts-secure-email-blueprint
/guidance/common-technology-services-cts-guide-to-implementing-the-secure-email-blueprint
Also due to content change, amended the header scroll tracking on
/guidance/universal-credit-how-it-helps-you-into-work
=> Add scroll tracking to 2 DWP UC & 2 CTS pages

app/assets/javascripts/analytics/scroll-tracker.js
Have added header scroll tracking to the following pages:
/openingupwork
/guidance/common-technology-services-cts-secure-email-blueprint
/guidance/common-technology-services-cts-guide-to-implementing-the-secure-email-blueprint
Also due to content change, amended the header scroll tracking on:
/guidance/universal-credit-how-it-helps-you-into-work
=> Add scroll tracking to 2 DWP UC & 2 CTS pages (v2)

app/assets/javascripts/user-satisfaction-survey.js, app/views/root/_base.html.erb, spec/javascripts/user-satisfaction-survey-spec.js
Trello: https://trello.com/c/L9Lk1l4H/308-survey-test-for-start-of-march-small-ish
This promotes the existing test to be the default, and sets up a new test for 48 hours beginning midnight UTC on 2nd March 2016.
This test includes a copy change which will also be reverted at the end of the test.
Best reviewed commit-by-commit due to some refactoring.
=> Implement 48 hour test User Satisfaction Survey

app/assets/javascripts/analytics/scroll-tracker.js
Correcting typo on heading 'When you can claim Universal Credit' on /guidance/universal-credit-how-it-helps-you-into-work which prevented the scroll event from firing.
=> Correcting header typo on scroll-tracking.js

app/assets/javascripts/webchat.js.erb
IE8 is throwing an error on all of GOV.UK (reported by @maxf). Looking at the given line/column number reveals a use of `indexOf` in the webchat code. This isn’t supported by IE8, hence it’s throwing an error. We’ve got jQuery available, so the fix is to swap in `$.inArray()`.
=> Fix IE8 JavaScript error on GOV.UK

app/assets/javascripts/analytics/scroll-tracker.js
HMT have requested to have % scroll tracking on the html doc version of the budget to be published on 16/03/16
=> Add scroll tracking to Budget HTML doc

app/assets/javascripts/analytics/scroll-tracker.js
Correct typo on the Budget 2016 docs page url
=> Update Budget 2016 docs scroll tracking

README.md, app/assets/javascripts/modules/sticky-element-container.js, app/assets/javascripts/start-modules.js, app/assets/stylesheets/govuk-component/_govspeak-html-publication.scss, app/assets/stylesheets/header-footer-only.scss, app/assets/stylesheets/modules/_sticky-element-container.scss, app/views/govuk_component/docs/govspeak_html_publication.yml, app/views/govuk_component/govspeak_html_publication.raw.html.erb, spec/javascripts/modules/sticky-element-container.spec.js, test/govuk_component/govspeak_html_publication_test.rb
This module allows you to stick an element to the bottom of its parent.
This is part of migrating `html_publications` from `whitehall` to `government-frontend`, and is meant to be used to implement the little "&uarr; Contents" button on http://www.gov.uk/government/publications/dwp-single-departmental-plan-2015-to-2020/dwp-single-departmental-plan-2015-to-2020.
Another PR will be opened to `government-frontend` to update the content item template and pass in the correct parameter to use this. (Update: https://github.com/alphagov/government-frontend/issues/122)
Relevant Trello ticket: https://trello.com/c/cJGrtnc1/286-5-html-publications-migration-front-end-work-large
Previous implementation in Whitehall: https://github.com/alphagov/whitehall/blob/master/app/assets/javascripts/application/b …
=> Add sticky-element-container module.

app/assets/stylesheets/govuk-component/_organisation-logo.scss, app/views/govuk_component/docs/organisation_logo.yml
This will match the executive office crest styling to the single identity one, which will bring html publications on `government-frontend` more in line with the ones on `whitehall`.
Part of fixing this visual regression:
Relevant Trello ticket: https://trello.com/c/cJGrtnc1/286-5-html-publications-migration-front-end-work-large
=> Define .crest-eo for organisation_logos.

app/assets/javascripts/webchat.js.erb
HMRC have asked for their web chat trial to show on various tax credit related pages. 
At the same time, the self assessment trial has finished so we should remove those URLs.
=> Change URLs where HMRC web chat can be displayed

app/assets/stylesheets/govuk-component/_govspeak-html-publication.scss, app/views/govuk_component/govspeak_html_publication.raw.html.erb, test/govuk_component/govspeak_html_publication_test.rb
Part of the addressing the final unintended changes introduced with migrating HTML publications in https://trello.com/c/cJGrtnc1/286-5-html-publications-migration-front-end-work-large.
This fixes the positioning of the sticky element. The reason it's done on the parent element is because directly messing with the positioning of the element produces undesirable results.
=> Add RTL support to html publications.

app/assets/stylesheets/govuk-component/_govspeak.scss
IE8 incorrectly asserts the "max-width: 100%" rule to be 0 because of the collapsed width on its floating container.
* Reset the max-width so that thumbnails render at the specified width
For reference:
http://www.456bereastreet.com/archive/201202/using_max-width_on_images_can_make_them_disappear_in_ie8/
Zendesk:
https://govuk.zendesk.com/agent/tickets/1287244
=> Fix display of attachment thumbs in IE8

app/assets/stylesheets/govuk-component/_govspeak.scss, app/views/govuk_component/docs/govspeak.yml
Makes them align better when around headers and other items which don't have an implicit margin-bottom.
Updates documentation with example where this change is visible.
Part of migrating HTML publications in https://trello.com/c/cJGrtnc1/286-5-html-publications-migration-front-end-work-large.
=> Add additional margin-top to govspeak contacts.

app/assets/stylesheets/govuk-component/_govspeak-html-publication.scss, app/assets/stylesheets/govuk-component/_govspeak.scss
This brings it more in line with what is on whitehall, while respecting our new vertical rhythm conventions.
Before:
After (still outstanding differences due to added line-height consistency in government-frontend):
Relevant Trello ticket:
https://trello.com/c/cJGrtnc1/286-5-html-publications-migration-front-end-work-large
=> Change govspeak header margin styling.

app/assets/stylesheets/helpers/_emergency-publishing-notifications.scss, app/views/notifications/banner.erb.example
The link will overlap the text if the last line of the text is too long.
This causes the link to display as it does on mobile, which is left aligned and block-level. I've signed this off with @dsingleton and @Shotclog. It also changes to a semantic CSS class name.
Relevant Trello ticket: https://trello.com/c/cm6VO0q4/341-emergency-publishing-frontend-bugs-medium
A follow-up PR will be submitted to alphagov/fabric-scripts to update the class name. **Update**: comme ça: https://github.com/alphagov/fabric-scripts/pull/214
=> Update emergency banner link styling.

app/views/root/_base.html.erb
It’s content that’s not related to the thing being printed.
cc @dsingleton @boffbowsh
=> Don't print the global bar

app/views/root/related.raw.html.erb, test/integration/related_template_test.rb
**Please don't merge, but give a 👍  so I can merge when ready**
Only on completed transaction format (though we'll extend it to transaction
pages in the near future). Exclude register to vote done page, as there is
not a lot of point promoing something you've just done.
As some done pages will have register-to-vote links in their related links
we need to exclude those, and if they're the only link in a group, the
group as well.
Filtering the register-to-vote link out of the related_artefacts before
grouping makes this much easier, but should only be done for pages where
we're showing the promo.
Note: register-to-vote is filtered out by content id, as the related
artefacts don't have path/slug field, and the full web_url is pretty
long, and can vary per environment, so use the content_id, …
=> Add register-to-vote promo on transaction done pages

app/views/govuk_component/document_footer.raw.html.erb
Add the full history link and the toggling behaviour to the document_footer component.
This changes are related to https://github.com/alphagov/government-frontend/pull/134
=> Add toggle behaviour to history in footer component

app/views/root/_base.html.erb
Screen reader users have the option to navigate by jumping between anchor tags and reading out the content. "More information" does not provide a lot of context about what the link does.
There is another equivalent PR open on `frontend`: https://github.com/alphagov/frontend/pull/945
=> Improve EU referendum homepage link copy for SRs.

app/assets/javascripts/webchat.js.erb
HMRC have asked us to re-enable their web chat trial on various self-assessment related URLs. These were originally removed in #759.
Please note.  This should not be merged until approval is given. I'll comment below when ready.
=> Re-enable HMRC web chat on self assessment URLs

app/views/govuk_component/docs/metadata.yml, app/views/govuk_component/metadata.raw.html.erb
These are metadata parts that should be used consistently by formats.
* Include an option to link to “see all updates”, this isn’t currently configurable as it doesn’t yet need to be.
* Move “Part of” to be alongside contextually similar metadata, “From”. Keeps history and published terms together.
Based on:
https://github.com/alphagov/government-frontend/blob/40ff6681c44d687fdf87015f244ad7ddd36c82db/app/views/content_items/detailed_guide.html.erb#L19-L20
There's already been an expectation that this should be included:
https://github.com/alphagov/government-frontend/blob/40ff6681c44d687fdf87015f244ad7ddd36c82db/app/views/content_items/case_study.html.erb#L28-L30
=> Add first published and last updated to metadata component

app/views/govuk_component/analytics_meta_tags.raw.html.erb, test/govuk_component/analytics_meta_tags_test.rb
* Derive political status based on current-ness of government and political state of content
* Use government slug for publishing-government
* Only include analytics tags if both government and political keys are present
Based on political and government representations in content items, added in: https://github.com/alphagov/govuk-content-schemas/pull/290
And the existing logic in Whitehall:
https://github.com/alphagov/whitehall/blob/bf784b05c467d3ce576fc8729810d21078cbc69c/app/helpers/document_helper.rb#L272-L288
https://github.com/alphagov/whitehall/blob/bf784b05c467d3ce576fc8729810d21078cbc69c/test/functional/publications_controller_test.rb#L668-L691
=> Add political-status and publishing-government to analytics

app/views/govuk_component/document_footer.raw.html.erb, app/views/govuk_component/metadata.raw.html.erb
When passing in an empty array for “Part of” or “From”, these defined keys don’t render any content or title – this reduces the need for logic in the frontend application. An equivalent custom key, eg “Related guides”, if passed an empty array, would output "Related guides: " and then no content after it.
* Update the `other` keys so they have the same behaviour and the components behave consistently.
cc @mgrassotti @dsingleton
=> Make custom "other" keys behave like defined keys

app/assets/javascripts/webchat.js.erb
- Specifically, the lost NI number information and contact pages.
=> Add HMRC webchat to more GOV.UK pages

app/assets/javascripts/user-satisfaction-survey.js, spec/javascripts/user-satisfaction-survey-spec.js
* Remove old test, add new test, fix pending spec.
* Test will run from May 4 to May 5.
https://trello.com/c/YN1CU7jB/385-gov-uk-survey-test-for-may-small
=> Create new survey test - decrease frequency that survey shows for 48 hours

app/assets/javascripts/govuk-component/govspeak-enhance-youtube-video-links.js, spec/javascripts/govuk-component/govspeak-enhance-youtube-video-links-spec.js
When using the [govspeak component](http://govuk-component-guide.herokuapp.com/components/govspeak), all links to YouTube are converted to an [embedded video player](http://govuk-component-guide.herokuapp.com/components/govspeak/fixtures/with_youtube_embed/preview).
This PR allows links to YouTube which aren't converted to an embedded player.
Check for a data attribute `data-youtube-player` if its value is `off`
then don’t convert that link into an embedded player.
For example:
```
<a href="http://www.youtube.com/youtubevidid" data-youtube-player="off">
Watch this related video
</a>
```
Here's a demo: 
http://codepen.io/gemmaleigh/pen/qZJmKB
There are Jasmine tests which can be previewed in the browser.
http://static.dev.gov.uk/specs
=> Check for a data attribute to turn off the video player

app/views/root/related.raw.html.erb
We've seen some issues with users mistakenly thinking they need to register
for the referendum specifically. Be clearer.
=> Make register-to-vote callout copy clearer

app/assets/stylesheets/govuk-component/_metadata.scss, app/views/govuk_component/docs/metadata.yml
Because the base font-size is different on this component, the external
link icon looks a bit off.
=> Fix display of external links in the metadata component.

app/views/root/_base.html.erb, spec/javascripts/global-bar-class-toggle.spec.js
* Check the current date and hide the banner for any time after midnight 26 May
* Set the current date to 25 May for the purpose of tests
* Include a specific test for the banner not showing on 26 May
https://trello.com/c/Bv2wbXTa/403-site-wide-banner-banner-not-visible-after-26th-may
@dsingleton @boffbowsh
=> Hide EU banner from 26 May

app/views/govuk_component/analytics_meta_tags.raw.html.erb, test/govuk_component/analytics_meta_tags_test.rb
This element assumes that the `organisations`, `lead_organisations` and `supporting_organisations` links in the links hash never overlap. This is not the case, and definitely isn't since https://github.com/alphagov/govuk-content-schemas/pull/308. This commit dedupes them before generating the metatag.
=> Dedupe organisations in meta tags

app/assets/stylesheets/helpers/_report-a-problem.scss
This link seems to override the base link classes, but produces a combination that has a poor contrast ratio when focused.
This commit updates the focus styles to fix the contrast.
=> Improve .report-a-problem-toggle:focus contrast

app/views/root/_footer_support_links.html.erb
Will enable screenreaders with multiple languages set to read the link correctly and determine the language of the document linked.
=> Adds lang and hreflang attribute to Welsh translation link

app/assets/javascripts/webchat.js.erb
Request from HMRC
To be merged and deployed on Friday 20 May 2016.
=> Add HMRC webchat to ‘manage your tax credits’ page

app/views/root/related.raw.html.erb, test/integration/related_template_test.rb
These were added as a short-term promotion on Start and Done pages/ We'll be removing them tomorrow. Please give a thumbsup review but don't merge. I'll do that tomorrow before the deploy slot. 
Reverts 
- https://github.com/alphagov/static/pull/784
- https://github.com/alphagov/static/pull/772
<Del>Tests are failing due to CI, they pass locally.</del>
=> [Merge on Wed 25th] Remove register to vote promo slots on Transaction pages

app/views/root/_base.html.erb
* Breadcrumbs is not a valid ARIA role
* It is not being used for styling
We previously removed from the component: https://github.com/alphagov/static/pull/737
Was added in: https://github.com/alphagov/static/pull/238
=> Remove invalid breadcrumbs aria role from base template

app/assets/javascripts/webchat.js.erb
At request of HMRC.
Also re-orders the list of URLs to make it easier to find which URLs are enabled and removes a duplicate URL.
Probably best to review by commit.
=> Turn on HMRC webchat for more tax credit URLS

app/assets/javascripts/webchat.js.erb
We currently track when users interact with HMRC’s webchat service (eg when they click the ‘accept’ or ‘reject’ buttons). This commit adds in an event to track when the webchat service is offered to users.
This event, alongside other data such as page views, will give us an idea of:
1. how many people are being presented with webchat but aren’t doing
anything with it
2. how many people are not being presented with webchat at all
cc @robinwhittleton @dsingleton @davidillsley
=> Track when HMRC webchat is offered to users in analytics

app/views/govuk_component/analytics_meta_tags.raw.html.erb, app/views/govuk_component/docs/analytics_meta_tags.yml, test/govuk_component/analytics_meta_tags_test.rb
These have been deprecated. We've ensured that all `lead_organisations` and `supporting_organisations` have been merged into `organisations` (https://github.com/alphagov/whitehall/pull/2585), so the data will be the same.
=> Remove `lead_organisations` & `supporting_organisations`

app/assets/stylesheets/static.scss
`styleguide/conditionals2`, `helpers/footer` and `helpers/header` are
all already included in `header-footer-only`. This means their styles are duplicated in the generated CSS.
It seems odd that header and footer weren't removed when switching to `header-footer-only`, but I haven't found any explicit reason for them to be kept. Nothing appears to override those styles.
For an example, search for `#user-satisfaction` in https://assets.digital.cabinet-office.gov.uk/static/static-35b681259fdcd07f543889e5711c8dbcf7728a3fa318c4881d0ba2e3d8bb3ac0.css
=> Remove stylesheets duplicated in header-footer-only

app/assets/javascripts/govuk-component/govspeak-enhance-youtube-video-links.js, spec/javascripts/govuk-component/govspeak-enhance-youtube-video-links-spec.js
When using the [govspeak component](http://govuk-component-guide.herokuapp.com/components/govspeak), all links to YouTube are converted to an [embedded video player](http://govuk-component-guide.herokuapp.com/components/govspeak/fixtures/with_youtube_embed/preview).
This PR allows links to YouTube which aren't converted to an embedded player.
Check for a data attribute `data-youtube-player` if its value is `off`
then don’t convert that link into an embedded player.
For example:
```
<a href="http://www.youtube.com/youtubevidid" data-youtube-player="off">
Watch this related video
</a>
```
=> Check if links to youtube should be embedded

app/assets/stylesheets/guides-print.scss
This will bump the text size and make printed text more legible.
Will affect pages such as https://www.gov.uk/after-a-death/print.
=> Add missing print-base helpers to guides-print.scss

test/govuk_component/component_smoke_test.rb
https://en.wikipedia.org/wiki/Smoke_testing_(software)
Each component has a set of fixture data that is used to generate
examples within govuk-component-guide, and show example usage.
Use this example data to run smoke test on each component, which
should give us increased confidence in catching big regressions in
component view logic - or broken fixture data.
It only asserts that components render without exception, not that
the internal logic is correct (this should be covered by view tests).
=> Add component smoke testing, using fixtures

app/assets/javascripts/modules/sticky-element-container.js, app/assets/stylesheets/modules/_sticky-element-container.scss, spec/javascripts/modules/sticky-element-container.spec.js
Since breakpoints in the grid are determined in CSS having
the logic that forces an element to be unstuck will mean
it can track the same variable that the grid system is using.
=> [Do not merge] Move unstuck logic to CSS so that breakpoints are better respected

app/assets/stylesheets/helpers/_header.scss
Bug report: #808
This fixes the search box breaking when someone increases the font size. When something has a height (especially of px) it doesn't grow with the text (not when zooming but increasing just the font size).
Removing the height completely would be the ideal solution but that caused issues in IE9, IE10 and WindowsPhone due to the alignment with the submit button.
The `height` got substituted with `line-height` but that alone caused issues in Safari in many iOS versions and Chrome on some Android phones, the text box somehow had a height of 36px and not 35px which caused a white line to appear below the submit button.
That's why the height of all the things got increased to 36px which fixed it. (Although it is not clear what caused it.)
=> Fix search box breaking when increasing font size

app/assets/javascripts/surveys.js, spec/javascripts/surveys-spec.js
In 8f1f835 when attempting to refactor the transaction detection logic, I inverted the match (returning true if inside a transaction URL, not false if *not* inside a transaction URL) but forgot to invert the if statement to "OR" from "AND".
This commit fixes that, and adds some tests to ensure the mistake can't happen again.
Credit to @knewter who spotted this when I showed him my GOV.UK PR :(.
👍 for coding in the open, though!
=> Fix transaction bug introduced in 8f1f835

app/controllers/root_controller.rb, app/views/govuk_component/document_footer.raw.html.erb, app/views/govuk_component/government_navigation.raw.html.erb, app/views/govuk_component/metadata.raw.html.erb, app/views/govuk_component/previous_and_next_navigation.raw.html.erb, app/views/govuk_component/related_items.raw.html.erb, app/views/locales/en.yml, config/locales/en.yml, test/govuk_component/document_footer_test.rb, test/govuk_component/related_items_test.rb
Continues the work done in https://github.com/alphagov/static/pull/505
Moves the language translation config files back into the conventional place rather than in the view directory.
=> Add translations for all govuk components

app/assets/javascripts/surveys.js, doc/surveys.md, spec/javascripts/surveys-spec.js
Please review commit by commit.
This allows surveys to take place only on certain pages, superseding the default survey.
Now the survey code has reached this level of complexity, let's provide some documentation on it (in `doc/surveys.md`) so people can read about what we support.
ronseal
See commit message for reasoning.
=> Add activeWhen callback for small surveys and use for 9th/10th of August

app/assets/stylesheets/govuk-component/_govspeak.scss, app/views/govuk_component/docs/govspeak.yml
https://govuk.zendesk.com/agent/tickets/1386394
The example callout styles are missing from the govspeak component and giving a different rendering when comparing private-frontend to public frontends.
=> Add missing govspeak example callout styles

app/assets/javascripts/analytics/scroll-tracker.js, spec/javascripts/analytics/scroll-tracker-spec.js
This is a continuation of closed #817.
[Trello card](https://trello.com/c/ZRqYEHab/57-suppress-duplicate-scroll-tracking-events)
This PR contains five sets of changes:
* Cosmetic changes: Remove duplicate function names.
* Handling path comparison better.
* Reducing the scroll delay. By reducing the timeout delay the the scroll tracking is fired more frequently and making it hard to miss out on faster scrolling users. This at the moment works and deemed experimental. 
* To reduce the effect the reduction of the scroll delay has for users, this removes most paths which we don't need to track anymore.
* Remove all code related to percent scroll tracking as that proved not to be useful.
1. Renamed `concatPath` to `normalisePath` as suggested by @dsingleton.
2. @nickcolley looked at potential …
=> Quick fix scroll tracking events for GA campaigns and cosmetic changes

app/assets/stylesheets/helpers/_print-base.scss
[govuk_template](https://github.com/alphagov/govuk_template) prints relative links with [a forced gov.uk prefix](https://github.com/alphagov/govuk_template/blob/master/source/assets/stylesheets/_core-print.scss#L24). This works for gov.uk but not for other services that consume the template. First step to fix this is to insert the prefix as part of static. After this is live we can remove the prefix override from the template (i.e. change the link href printing selector to `a[href^="/"]:after, a[href^="http://"]:after, a[href^="https://"]:after`).
=> Migrate link href printing from template

app/views/root/_error_page.html.erb, test/integration/templates/error_5xx_test.rb
This is GOV.UK style. Suggested by Tom Hughes.
=> Contract "we are" to "we're" on error page

app/assets/javascripts/webchat.js.erb
This page will be getting the new style of HMRC webchat content. So the banners are no longer required.
Related to a PR on `contacts-frontend` to enable the new webchat there. Must be deployed before, or alongside that change.
=> Remove webchat banner on VAT Enquiries page

app/assets/javascripts/webchat.js.erb
This page will be getting the new style of HMRC webchat content. So the banners are no longer required.
It should be merged and deployed alongside https://github.com/alphagov/contacts-frontend/pull/53
=> Remove webchat banner on Tax Credits page

app/assets/javascripts/webchat.js.erb
This page will be getting the new style of HMRC webchat. So the banners are no longer required.
This should be merged and deployed alongside https://github.com/alphagov/contacts-frontend/pull/54
=> Remove webchat banner on SA enquiries page

app/assets/javascripts/report-a-problem-form.js, app/assets/javascripts/report-a-problem.js, spec/javascripts/report-a-problem-form-spec.js, spec/javascripts/report-a-problem-spec.js
[Trello card](https://trello.com/c/mGyllSZu)
To make it easier to gather statistics on which areas get the most feedback, we'd like to track the feedback intent of users by tracking the revealing of the form and its submit (not success or failure).
While I was working on those file I also fixed some linting issues (but two are still in there).
=> Feedback form event tracking

app/views/govuk_component/analytics_meta_tags.raw.html.erb, test/govuk_component/analytics_meta_tags_test.rb
The `format` field is deprecated from the content-store. It has been split into `document_type` and `schema_name`. For compatibility reasons, `schema_name` is used to populate `format` in existing content items. So in reality, this components sets `govuk:format` to the `schema_name` of the page.
We think that `document_type` is more descriptive to use in analytics. Especially since we are adding this component to applications like frontend, calendars, calculators and smart-answers. Pages published to the content-store by those apps have a schema_name of `placeholder`, but a meaningful document type.
At the moment this component is used by 4 applications. Almost all content items rendered by those apps have an indentical document_type and schema_name, so there would be no effect to what's …
=> Use document type for the analytics format

app/views/govuk_component/analytics_meta_tags.raw.html.erb, test/govuk_component/analytics_meta_tags_test.rb
This commit removes the need IDs meta tag. The performance analysts confirmed at a meeting on 12/10/2016 that this tag is no longer required.
=> Remove need IDs meta tag

app/views/root/report_a_problem.raw.html.erb
https://insidegovuk.blog.gov.uk/2016/07/20/changes-to-the-style-guide-no-more-eg-and-ie-etc/
> Terms like eg, ie and etc, while common, make reading difficult for some.
=> Replace "eg" with "like" for report a problem

app/assets/stylesheets/govuk-component/_breadcrumbs.scss, app/assets/stylesheets/govuk-component/_related-items.scss
GOV.UK Components expect that they're included in a page with a certain global CSS reset. This is the case for newly migrated pages (like the ones rendered by government-frontend), but it doesn't apply to pages in older frontend apps like calendars, calculators, smart answers, and others.
While migrating those pages to use the component we introduced the same CSS in all applications. This to prevent extra margins appearing on breadcrumb and related links.
https://github.com/search?q=org%3Aalphagov+%22might+be+pushed+up+to+static+at+some+point%22&type=Code
This puts the CSS back in here, so that we can remove the overrides in individual apps.
https://trello.com/c/5Utjs9qw
cc @carolinegreen @fofr @nickcolley
=> Make sure breadcrumbs and related items look good in older apps

app/views/govuk_component/related_items.raw.html.erb, test/govuk_component/related_items_test.rb
This commit aims to superseed https://github.com/alphagov/frontend/pull/1069
We believe that is the component responsability to make sure the requirements are met
in order to do the the job, in this case, to render the content.
What this commit suggest is that we do our components with [Design by Contract](https://en.wikipedia.org/wiki/Design_by_contract) in mind,
what it means is that the component becomes responsible to dictate how it should be used.
Also there's a certain advantage of doing this at the component level,
this avoids extra work on the developer to chase all the rendering applications to make sure they should or not render the component.
So keeping it on the component side is not only beneficial code wise but also more efficient.
Trello: …
=> Avoid rendering the side content when there's no content

app/assets/javascripts/core.js, app/assets/javascripts/header-footer-only.js
Closes #825
Shims any applications that are using `[role="button"]` so that using the spacebar will click them as expected.
Check out this branch locally and also a frontend application with a button (for example a start page).
Tab to the button, then press the spacebar, the button should be clicked in the same behaviour as pressing enter.
=> Add and init button role shim

Gemfile, Gemfile.lock, lib/tasks/publishing_api.rake
Format was deprecated in favour of `document_type` and `schema_name`.
This commit fixes it so we can publish the special routes to the
Publishing API.
=> Update special route content item

app/views/govuk_component/previous_and_next_navigation.raw.html.erb
There is a typo in the previous_and_next_navigation component as the "previous" link has an invalid [link type](https://www.w3.org/TR/html5/links.html#linkTypes).
This corrects `rel="previous"` to the correct `rel="prev"`.
=> Fix invalid value for rel attribute

app/assets/javascripts/modules/track-breadcrumb-click.js, app/assets/javascripts/modules/track-click.js, app/assets/javascripts/start-modules.js, app/views/govuk_component/breadcrumbs.raw.html.erb, spec/javascripts/modules/track-breadcrumb-click.spec.js, spec/javascripts/modules/track-click.spec.js
This PR adds a new tracker that tracks clicks on breadcrumb links. When a click occurs, it:
- sets a custom dimension in order to report the title of the link clicked;
- calls the `TrackLink` module to track a custom event (`trackEvent`) with the remaining data attributes (category, action and label).
**NOTE**:
Before this can be merged, we need to:
This branch was created off https://github.com/alphagov/static/pull/863, hence the first 2 commits being the same.
=> Track breadcrumb clicks

app/assets/stylesheets/govuk-component/_govspeak-html-publication.scss
We override the default govspeak styles with our HTML publication specific header margins. We need to put back the margin resets too.
Goes with this change: https://github.com/alphagov/government-frontend/pull/223
=> Remove margin on first heading in HTML govspeak

spec/javascripts/jquery-tabs-spec.js
This is not an exhaustive test. It tests the fundamental behaviour of the app in its two modes; accordion and tabs.
It aims to test that the jQuery tabs plugin:
* Runs set up code without error
* Configures tab links and panes
* Hides and shows panes when clicking links
The lack of a unit test meant we missed an error produced when jQuery was upgraded: 
https://github.com/alphagov/static/pull/874
https://github.com/jquery/jquery/issues/2824
When upgrading jQuery again, this test will fail with the error:
```
Error: Syntax error, unrecognized expression: a[href$=#]
```
cc @nickcolley @gpeng
=> Add unit test for jQuery tabs plugin

app/views/root/_base.html.erb, app/views/root/without_footer_links.html.erb
The links that appear in the top half of the footer (.footer-categories) replicate the home page of GOV.UK and represent the needs of the citizens using the site.
As the primary users of the Service Manual (and forthcoming Service Toolkit) are people within government building a services these links are not relevant and may even compete (could be confused with Service Manual content).
=> Add a new layout that excludes footer links

app/assets/stylesheets/helpers/_core.scss
In https://github.com/alphagov/static/pull/879 I removed CSS for breadcrumbs and related links. The `related-container` CSS should not have been deleted, because it determines the size of the sidebar (rather than the appearance of it, which is determined by the govuk component).
https://trello.com/c/7wohUbyo
=> Add back removed CSS for sidebar positioning

app/assets/javascripts/modules/track-click.js, app/views/govuk_component/breadcrumbs.raw.html.erb, app/views/govuk_component/related_items.raw.html.erb, spec/javascripts/modules/track-click.spec.js, test/govuk_component/breadcrumbs_test.rb, test/govuk_component/related_items_test.rb
Creating a single event listener is more efficient than one for every link that could be clicked. It also reduces the number of unique modules that must be started.
* Use new pattern on breadcrumbs and related links
* I've tested the correct events are generated in frontend
Will make https://trello.com/c/62Gy8pyj/77-track-interactions-with-contents-lists-1-s more efficient.
cc @tijmenb @alecgibson @nickcolley
=> Allow tracking of all trackable links within a container

app/assets/javascripts/surveys.js, doc/surveys.md, spec/javascripts/surveys-spec.js
For: 
* https://trello.com/c/8iJaA4Ey/95-gov-uk-survey-remove-standard-survey-from-service-manual-content - exclude surveys from the service-manual
* https://trello.com/c/vaotDp0x/97-gov-uk-survey-education-content-2 - Re-run the education survey added in #862 (and removed in #877)
* https://trello.com/c/d792rO1T/99-gov-uk-survey-environment-user-research-panel-sign-up-set-of-9-surveys - extend the environment user research survey added in #877
* https://trello.com/c/PXBtbvUH/100-gov-uk-survey-ons-government-data - add new ONS survey
=> Late jan 2017 survey changes

app/assets/javascripts/surveys.js
In #879 we replaced the `#global-breadcrumb` container for breadcrumbs
with the govuk component rendered version which uses `.govuk-breadcrumbs`
as the container instead.  This broke our `breadcrumbMatches()` function
so we change the function to grab the correct selector.
We also change the section matcher to use a regexp test instead of direct
equality to check for a matching section.  It's not clear if the section
names have recently changed, or if the matcher never worked but it wasn't
detected because the breadcrumbs worked instead.
=> Fix breadcrumb and section matchers for Education survey

app/assets/javascripts/surveys.js
Note that at the time of writing this survey is running concurrently
with another survey that affects a small number of pages. It was decided
to retain the existing survey for these pages rather than choose between
multiple candidate surveys per page. By placing the new survey at the top of the
array we ensure that it will be "overridden" by a survey that also
applies where that survey is found later in the array.
Trello: https://trello.com/c/J8PdbakJ/108-gov-uk-survey-environment-short-survey
=> Add new environment short survey

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
Link meta tags named `govuk:ab-test` to a custom Google Analytics dimension. The value of the meta tag and the dimension is a combination of the test name and bucket name, such as `EducationNavigation:B`.
~~This links to existing session dimension 13, which has been used for A/B tests in the past.~~ We're not going to use the existing A/B test dimension (13) so that it can continue to be used by JS-based A/B tests. Tara has reserved dimension 40 instead.
Note that only one A/B test can use this dimension at once, otherwise the value will be overridden by different tests.
Trello: https://trello.com/c/g9OyC7Pn/310-tell-google-analytics-about-a-b-tests
=> Add analytics dimension for A/B tests

Jenkinsfile
This commit adds a Jenkinsfile which allows us to move onto the new Jenkins 2 CI infrastructure.
This will replace the existing jenkins.sh file once we’re happy it works.
=> Use Jenkins Pipeline

Jenkinsfile
Having made [changes to the govuk.sassLinter method](https://github.com/alphagov/govuk-puppet/pull/5459) to allow it to take a path or set of paths as an argument, we can now use it whilst passing our custom path.
=> Use govuk.sassLinter

Jenkinsfile
Related to #898 
This makes some changes as per the [instructions] in the opsmanual:
- Adds a IS_SCHEMA_TEST property and sets a default value for it
- Adds a check to ensure that builds only occur if either (the branch name is not deployed-to-production) OR (the branch name is deployed-to-production AND this is a schema test)
[instructions]: https://github.gds/pages/gds/opsmanual/infrastructure/testing/application-testing.html?highlight=testing
=> Modify Jenkinsfile to allow for schema change builds

app/assets/stylesheets/helpers/_draft.scss
Some content is clipping the draft background watermark. This commit adds `background-size: contain` to avoid this.
Before:
After:
Before:
After:
I've not tested the effect on IE so would welcome an opinion on that.
/cc @fofr (thanks for the pointer on how to fix), @nickcolley
=> Fix draft watermark for short content

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
The GA dimensions from 40-49 have been allocated to A/B tests. These may be reserved for any A/B test for the duration of the test.
This commit identifies which dimension to use for the A/B test based on an extra `data` attribute added to the `meta` tag. Only dimensions in the allowed range are permitted. Any others are ignored and are not reported to GA.
It would be good to have some feedback on this approach. I'm aiming to make it as simple as possible for new teams to add an A/B test. With this proposal, they would have to do the following:
- Request one of the dimensions in the 40-49 block from the performance analysts for the duration of the A/B test. They will assign one which isn't currently being used.
- Set a meta tag in the header like `<meta name="govuk:ab-test" …
=> Add block of Google Analytics dimensions for A/B tests

Dockerfile
Means less set-up required to use with docker-compose.
=> Add development defaults to Dockerfile

app/assets/stylesheets/govuk-component/_breadcrumbs.scss, app/views/govuk_component/breadcrumbs.raw.html.erb
This style any breadcrumbs linking to anchors on the current page. This is used in conjunction with https://github.com/alphagov/govuk_navigation_helpers/pull/30 to show users which page they are currently on, when browsing the new taxonomy.
Before:
After:
Trello: https://trello.com/c/MVM5bueS/386-add-current-page-to-taxonomy-breadcrumbs
=> Style breadcrumb anchor links

app/assets/stylesheets/govuk-component/_organisation-logo.scss, app/views/govuk_component/docs/organisation_logo.yml, app/views/govuk_component/organisation_logo.raw.html.erb, test/govuk_component/organisation_logo_test.rb
Goes with https://github.com/alphagov/govuk-content-schemas/pull/514 and https://github.com/alphagov/government-frontend/pull/246
Part of https://trello.com/c/HtSGDoRb/594-add-organisation-logos-that-are-images-to-content-item-2
* Add support for logos for organisations such as HM Prison Service, Land Registry, Environment Agency have a custom logo image.
* Update component to accept an image if provided
=> Add support for custom organisation logos

app/controllers/root_controller.rb
Smart answers uses a "en-GB" locale, but we don't have that in this app. This causes a lot of 404's to be returned and missing translations in smart answers (presumably).
Kibana reports about 3.3 million `404` on this route over the last 24 hours:
This is also caused by smart-answers cache being broken, which is fixed in https://github.com/alphagov/slimmer/pull/183.
https://trello.com/c/D9HmkJwI
=> Fall back to "en" locale for "en-GB"

app/assets/javascripts/modules/track-click.js, spec/javascripts/modules/track-click.spec.js
This will pass an event value through to the trackers, where it is handled in [`govuk_frontend_toolkit`](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/analytics/google-analytics-universal-tracker.js#L78-L87)
This change is required to pass an event value when tracking navigation grid clicks.
Trello: https://trello.com/c/btaOSNax/426-track-position-of-clicks-in-the-new-taxon-grid-pages
=> Track values

app/assets/stylesheets/govuk-component/_alpha-label.scss, app/assets/stylesheets/govuk-component/_beta-label.scss, app/assets/stylesheets/govuk-component/_breadcrumbs.scss, app/assets/stylesheets/govuk-component/_component.scss, app/assets/stylesheets/govuk-component/mixins/_touch-friendly-links.scss
This change is to (slightly) improve the user experience when using the breadcrumb and phase banner links on a touch-enabled device. To do this, we make the touchable area larger.
See the screenshot below for an idea of the change. The blue area is the area that was originally clickable, but now you can also click the green area.
The clickable area has currently been enlarged just `3px` to match the orange `focus` outline. Ideally we would make this area even larger (I've heard numbers around 40px x 40px minimum thrown around before), but you start running into problems with clickable elements overlapping one another - for example when breadcrumbs wrap onto a second line. This particular problem should eventually be solved by [reducing breadcrumbs to a single entry on …
=> Touch-friendly links for breadcrumbs and phase banners

app/assets/stylesheets/govuk-component/_organisation-logo.scss, app/views/govuk_component/docs/organisation_logo.yml
- Adds the support for the dit crest
- Adds fixture to show the example in the Component Guide
To test:
1. Check this branch out
2. Run `./startup.sh`
3. Check https://github.com/alphagov/govuk-component-guide out
4. Run `PLEK_SERVICE_STATIC_URI=http://static.dev.gov.uk ./startup.sh`
5. Visit `http://x.x.x.x:3113/components/organisation_logo/fixtures/department_for_international_trade` where `x.x.x.x` is replaced with your VM or local machines' IP address
6. Check https://github.com/alphagov/government-frontend out
7. Run `PLEK_SERVICE_CONTENT_STORE_URI=https://www.gov.uk/api PLEK_SERVICE_STATIC_URI=http://static.dev.gov.uk ./startup.sh`
8. Visit `http://government-frontend.dev.gov.uk/government/publications/why-overseas-companies-should-set-up-in-the-uk/why-overseas-companies-should-set-u …
=> Add DiT organisation

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
Add Google Analytics dimensions:
- Whether a user is viewing a navigation or a content page, i.e. where they are in their journey through the site
- What type of navigation page they visit, e.g. a taxon page or a mainstream browse page
Don't merge this until we have confirmation of the GA dimensions to use. I've temporarily set them to values outside of the GA range.
Trello: https://trello.com/c/SCsj2A9D/425-add-custom-dimension-to-page-view-tracking-on-new-navigation-pages
=> Add analytics for user navigation journeys

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
For: https://trello.com/c/JX541tka/113-add-tls-version-information-to-google-analytics
The TLS Version supported by the browser will be set as a cookie by the
CDN and so will be available when viewing the page.  We extract the value
from the cookie and send it as the value for custom dimension 16 to
google analytics as part of the initial page view tracking.  Doing it
here has caused some churn in the tests (it's now the 4th arg instead
of the trackPageView message), but it means we don't have to send a
separate GA request so it shouldn't impact performance for the users.
This relies on https://github.com/alphagov/govuk-cdn-config/pull/27 to provide the cookie.
=> Extract TLS Version from cookie and send to GA

app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss, app/views/govuk_component/docs/taxonomy_sidebar.yml, app/views/govuk_component/taxonomy_sidebar.raw.html.erb, test/govuk_component/taxonomy_sidebar_test.rb
This change updates the taxonomy sidebar to accept a list of related content items under each taxon, and updates the styling to match the latest designs.
This is a **breaking change** which will align the API to the slimmed-down version in [this update to `govuk_navigation_helpers`](https://github.com/alphagov/govuk_navigation_helpers/pull/44). Since taxonomy display is still in alpha, and this is a novel component being used only by the navigation team this breakage is assumed to be acceptable.
https://trello.com/c/EJXC60k1/429-add-more-like-this-results-to-side-navigation-in-frontend-apps
=> Display related links in taxonomy sidebar

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
The CDN sets [a cookie called `TLSversion`](https://github.com/alphagov/govuk-cdn-config/blob/f42d9db9f361dd434dfb782c0377ec55fc48495c/vcl_templates/www.vcl.erb#L331) not `TLSVersion`. :man_facepalming: 
Only found this out after deploying to staging to test on an environment that has a CDN.
=> Use the correct cookie name for the TLS version cookie set by the CDN

app/views/govuk_component/analytics_meta_tags.raw.html.erb, test/govuk_component/analytics_meta_tags_test.rb
Add meta tag which identifies the page as being primarily concerned with content or navigation. This will be converted to an analytics dimension by the analytics JavaScript, and will help us analyse users' journeys through the site.
Trello: https://trello.com/c/SCsj2A9D/425-add-custom-dimension-to-page-view-tracking-on-new-navigation-pages
=> Add `user-journey-stage` analytics meta tag

app/assets/stylesheets/govuk-component/_govspeak.scss, app/assets/stylesheets/govuk-component/govspeak/_typography.scss, app/views/govuk_component/docs/govspeak.yml
We don’t style bold text in markdown except for specific places where rich-govspeak is enabled (eg the highway code manual), see https://github.com/alphagov/static/pull/657
If an app uses `core-layout` then it uses a reset that styles strong as bold. See: https://github.com/alphagov/static/pull/483. Any app using core-layout and the govspeak component would render the `strong` text in bold. This is a regression that has gradually affected a greater proportion of content as we have migrated.
Whitehall did not set `strong` styles, so bold was not used in content.
[Our style guide says](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#bold):
> __bold__
> Don’t use bold. It can distract the user and it makes the text longer and more confusing for users of screen readers. Use …
=> Fix regression: Don't style strong text as bold unless using rich govspeak

app/assets/stylesheets/govuk-component/mixins/_touch-friendly-links.scss
The negative margin added to the breadcrumb links to improve the
clickable area introduced a bug in firefox, where the link text wraps to
a new line.
By adding `display: inline-block` we make sure the link doesn't wrap to
a new line like in other browsers.
Trello: https://trello.com/c/QlITug3n/499-firefox-shows-breadcrumbs-wrapped
=> Fix breadcrumbs' layout in Firefox

app/assets/javascripts/modules/track-click.js, spec/javascripts/modules/track-click.spec.js
Some clicks require multiple custom dimensions to be set on them. Our current markup only allows one dimension ID and its corresponding value to be set.
In order to submit multiple custom dimensions, this change adds the ability to set arbitrary Google Analytics tracking events in the [`fieldObject`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference) in the form of JSON.
The corresponding change in `collections` is: https://github.com/alphagov/collections/pull/288
https://trello.com/c/btaOSNax/426-track-position-of-clicks-in-the-new-taxon-grid-pages
=> Track clicks with arbitrary JSON options

app/assets/javascripts/analytics/scroll-tracker.js
Supersedes https://github.com/alphagov/static/pull/930
HMT have asked for scroll tracking to be added to the 2017 budget publication. They want to track the numbers of users who reach the links in the headings I've added to the code.
This pull request replaces #925 (I've created a new one as the headings' titles have changed and this request reflects the change).
=> Update scroll tracker for 2017 budget

app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss, app/views/govuk_component/taxonomy_sidebar.raw.html.erb, test/govuk_component/taxonomy_sidebar_test.rb
Apply the latest set of design changes.
https://trello.com/c/yFhLdgMX/471-style-and-copy-changes-to-the-taxonomy-side-bar
=> Design updates to taxonomy sidebar component

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
Probably easiest to review as individual commits:
- Refactor test of analytics dimensions.
- Add a default value for the `user-journey-stage` dimension. Pages which show navigation rather than content will add the meta tag for this dimension. All other pages should be tracked as 'thing', which identifies pages as containing content rather than navigation.
Marked as DO NOT MERGE until the meta tag has been added to all the navigation page types. Full list in Trello: https://trello.com/c/SCsj2A9D/425-add-custom-dimension-to-page-view-tracking-on-new-navigation-pages
=> Add a default value for the `user-journey-stage` dimension

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
This change closely follows https://github.com/alphagov/static/pull/921
Here, we set a default value of `none` for the `navigation-page-type` custom dimension. This is to ease the processing of Google Analytics results, since fields missing this custom dimension are omitted in some reports.
https://trello.com/c/Eui3OmTB/491-track-navigation-page-type-for-non-taxon-pages
=> Set default navigation page type tracking dimension

app/assets/javascripts/surveys.js
If we're showing the new taxonomy navigation survey, we don't want to
show other banners.
=> Add a taxonomy survey notification ID to surveys.js

app/assets/javascripts/mobile.js
This adds a click tracker on opening and closing guide navigation. 
This is needed to track usage of the open and close mechanism for template consolidating.
=> Add guide link tracking on open navigation

app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss
Trello: https://trello.com/c/koyo5MKj/48-topic-titles-in-sidebar-should-be-underlined
@alextea is this what you expect?
=> Taxon names should be underlined in sidebar

app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss
This makes sure we allow enough spacing in between the sidebar and the
content underneath it in mobile viewports.
Trello: https://trello.com/c/tTLH10ht/50-mobile-layout-margins-below-related-component-too-tight
=> Add padding bottom to taxonomy sidebar

app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss
There was a gap between multiline links in the sidebar that you couldn't click. `display: block` makes these links wrap the entire li element
Trello card: https://trello.com/c/xshqCdju/33-it-s-possible-to-click-in-the-middle-of-related-links-and-not-go-anywhere
=> Fix gap in sidebar links

app/assets/stylesheets/govuk-component/govspeak/_contact.scss
* Port fix from https://github.com/alphagov/whitehall/pull/2367
* Also remove custom paragraph rule, Whitehall had padding so these items were slightly spaced
* Addresses https://govuk.zendesk.com/agent/tickets/1918092
Fix was made to Whitehall after styles were cut for govspeak component.
http://webarchive.nationalarchives.gov.uk/+/https://www.gov.uk/government/news/future-life-expectancy-to-be-considered-in-first-state-pension-age-review
=> Render govspeak contact details inline for legibility

app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss, app/views/govuk_component/taxonomy_sidebar.raw.html.erb
Fixes an issue where pseudo elements on an anchor tag receive the same
text decoration as the anchor tag.
=> Workaround for IE8 bug on related link bullet points

app/assets/javascripts/surveys.js, app/assets/stylesheets/helpers/_header.scss
The send button in the email survey UI used the ".button" class to get the
styling defined in `helpers/_buttons`.  Unfortunately this styling is not
included in all layouts that an app might request from static.  For example
it is included in the static layout, but not the header_and_footer_only or
core_layout.  This means that only some frontend rendering apps will style
the button correctly.
Instead we explicitly include the button styling mixin in the css for a
button in the user-satisfaction-survey in `helpers/_header`.  This helper
is included in all layouts so all frontend rendering apps will style the
button correctly.
For: https://trello.com/c/dfSufy85/114-develop-a-new-survey-delivery-method
=> Explicitly include button styles for the email survey submit button

app/assets/javascripts/modules/global-bar.js, app/assets/javascripts/start-modules.js, app/assets/javascripts/surveys.js, app/assets/stylesheets/helpers/_header.scss, app/views/root/_base.html.erb, app/views/root/_promo_banner_example.html.erb, spec/javascripts/global-bar-class-toggle.spec.js, spec/javascripts/modules/global-bar.spec.js, test/functional/root_controller_test.rb
Allows for a partial to be deployed based on `app/views/root/_promo_banner_example.html.erb`. This should include the `global-bar` javascript module in order to enable view count tracking. The banner won't display alongside the survey banner or the emergency publishing banner.
`app/views/root/_promo_banner.html.erb` should remain empty if the banner isn't in use.
Example:
=> Add support for displaying a banner across all of GOV.UK

app/assets/stylesheets/govuk-component/_govspeak-print.scss
Add styles to the `help-notice` block in govspeak when printing
Part of https://github.com/alphagov/government-frontend/pull/274 and https://trello.com/c/MluRcP1W/
* Help notices need to be visually stronger
* The call to action is in bold, print in bold too
* The background image won’t print, use a border instead – matching other calls to action
cc @36degrees
=> Add warning callout print styles to govspeak component

app/assets/javascripts/surveys.js
[Trello card](https://trello.com/c/mQwppzsQ/127-re-run-email-survey-from-17th-march-to-21st-march)
This email survey will run with a 1-in-50 frequency, from when we first deploy it (Friday, 17.03.2017 at 1 PM) to the end of Sunday (20.03.2017 at 23:59:59)
=> Add new email survey

app/assets/stylesheets/govuk-component/_breadcrumbs.scss, app/assets/stylesheets/govuk-component/_component.scss, app/assets/stylesheets/govuk-component/mixins/_back-arrow.scss, app/views/govuk_component/breadcrumbs.raw.html.erb
When viewing the new taxonomy navigation on mobile, we want to show the parent taxon only rather than the full breadcrumb.
This commit allows a 'collapse_on_mobile' flag to be passed in by any app rendering the component, changing the applied CSS accordingly.
https://trello.com/c/Y7OirowB/472-mobile-version-of-breadcrumbs-should-only-show-previous-link
This is a continuation of @mobaig's PR #944 - I can't reopen it because I force-pushed the branch first. TIL.
I've added my changes to Mo's original PR as a separate commit so you can see the diff. I'll squash before merging to master.
This will need a corresponding change in govuk_navigation_helpers to add the flag: https://github.com/alphagov/govuk_navigation_helpers/compare/master...breadcrumb-parents?expand=1
=> Update breadcrumb component to allow optional collapsed display

app/views/govuk_component/alpha_label.raw.html.erb, app/views/govuk_component/beta_label.raw.html.erb
When reading out of context, for example when using a screen reader, "find out what this means" is not very clear.
=> Change link text in banners to be more accessible

app/views/govuk_component/related_items.raw.html.erb, app/views/govuk_component/taxonomy_sidebar.raw.html.erb, test/govuk_component/related_items_test.rb, test/govuk_component/taxonomy_sidebar_test.rb, test/govuk_component_test_helper.rb
When a related link in the sidebar is clicked, track the size of the list that it is in:
- If a taxon name or a 'more' link is clicked, track the number of sections
- If a related link within a section is clicked, track the number of links in the section
This will help us analyse whether users are finding useful content in those lists.
https://trello.com/c/JffDJtJ5/500-track-the-number-of-items-in-accordions-breadcrumbs-and-related-links
=> Track total number of related links in Google Analytics

app/views/govuk_component/breadcrumbs.raw.html.erb, test/govuk_component/breadcrumbs_test.rb
When a breadcrumb link is clicked, report the full length of the breadcrumb list as well as the existing tracking of title, position, etc.
This will help us understand the tracked breadcrumb position in the context of the full taxon list.
https://trello.com/c/JffDJtJ5/500-track-the-number-of-items-in-accordions-breadcrumbs-and-related-links
=> Track total number of breadcrumbs in Google Analytics

app/assets/javascripts/analytics/static-analytics.js, app/views/govuk_component/analytics_meta_tags.raw.html.erb, spec/javascripts/analytics/static-analytics-spec.js, test/govuk_component/analytics_meta_tags_test.rb
Track the type of page using dimension 34. Pages are currently classified as 'guidance' or 'other', but more page types may be added in future.
This will help us understand user journeys through the new navigation, because only guidance content appears on the new taxonomy pages.
https://trello.com/c/Tkn0P6Fm/532-track-guidance-navigation-supertype-in-google-analytics
=> Track the navigation document type in Google analytics

app/views/govuk_component/taxonomy_sidebar.raw.html.erb, test/govuk_component/taxonomy_sidebar_test.rb
We want to use this component with the "Elsewhere on GOV.UK" heading,
which doesn't have a link.
Trello:
https://trello.com/c/vM6Kaw9B/505-ias-and-content-designers-can-curate-related-links-for-any-content-type
=> Allow the sidebar heading to not be a link

app/assets/javascripts/analytics/init.js
- Enable Google Analytics Cross Domain Tracking to the campaign site.
- Pass the client id from the session on our domain to the session on the other domain.
- Joins up the user journey tracking.
- More information about Cross Domain Tracking can be found [here](https://support.google.com/analytics/answer/1034342?hl=en).
=> Cross domain tracking

app/assets/javascripts/analytics/init.js.erb
This reverts commit 8a7bd892c8ec1f7fb9f8d5b08968b19675a22725.
This is a revert of #961, which can't be reverted automatically due to conflicts.
=> Revert "Cross domain tracking"

app/assets/javascripts/analytics/init.js.erb
Adds linked tracking without creating a new tracker, as per
https://developers.google.com/analytics/devguides/collection/analyticsjs/linker. 
As this is a temporary measure, we’re calling `ga` directly
rather than adding the functionality to
`GOVUK.GoogleAnalyticsUniversalTracker` in `govuk_frontend_toolkit`.
=> Add linked domain tracking to Plan For Britain campaign

app/assets/javascripts/analytics/init.js.erb
Removing the `govukTrackerGifUrl` config parameter will disable analytics tracking,
we need to do this because requests to origin for this asset have increased
with adverse effects.
Some analysis of the impact of this config is needed before re-enabling.
=> Remove govukTrackerGifUrl config parameter

app/views/govuk_component/breadcrumbs.raw.html.erb, app/views/govuk_component/related_items.raw.html.erb, app/views/govuk_component/taxonomy_sidebar.raw.html.erb, test/govuk_component/breadcrumbs_test.rb, test/govuk_component/related_items_test.rb, test/govuk_component/taxonomy_sidebar_test.rb
Update the breadcrumb and related link tracking which tracks the total number of links against dimension 28. Convert the count to a string, which gets rid of the Google Analytics JavaScript warning: `Expected a string value for field: "dimension28". but found: "number"`.
https://trello.com/c/JffDJtJ5/500-track-the-number-of-items-in-accordions-breadcrumbs-and-related-links
=> Fix Google Analytics warning about using integers rather than strings

app/assets/javascripts/analytics/static-analytics.js, app/views/govuk_component/analytics_meta_tags.raw.html.erb, spec/javascripts/analytics/static-analytics-spec.js, test/govuk_component/analytics_meta_tags_test.rb
This change adds a tracking `meta` tag for tracking the "theme" of a document. Its theme is defined as its root taxon, and is tracked for both taxons and content items. The tracked themes should contain all possible themes (ie if a content item or taxon has multiple root taxons), and should be set as `other` if no themes are present.
Note that the implementation here involves defining a method in a `.erb` template, which feels un-idiomatic. However, given that this (complex) logic can't be moved into a helper method because of the way templates are distributed and rendered, it seemed like the neatest way to implement this solution in this way.
Alternative solutions may include:
- Storing the theme directly in the content store, although this would involve changes to publishing and content …
=> Track themes

app/views/govuk_component/related_items.raw.html.erb, test/govuk_component/related_items_test.rb
Google Analytics dimension 28 is used to track the length of a list of links. Update this value for mainstream related links so that it tracks the full length of the list including the "More" links, and update the "More" link itself to track the link list length within a section rather than the number of sections.
This makes dimension 28 consistent with dimension 29 which tracks the position in the list and already includes the "More" link in that list.
https://trello.com/c/JffDJtJ5/500-track-the-number-of-items-in-accordions-breadcrumbs-and-related-links
=> Fix tracking of "More" link in mainstream related links

app/assets/javascripts/surveys.js
[Trello card](https://trello.com/c/4gNFt4un/138-replace-url-for-default-survey-when-no-tests-are-running) 
This will replace the current default url survey with a new one. It will run at the same frequence: 1 in 50.
=> Replaces default survey url

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
Add a default value for the navigation document type, so that all pages (which include the JS from static) track the page as 'other' rather than a specific navigation type like 'guidance'.
https://trello.com/c/Tkn0P6Fm/532-track-guidance-navigation-supertype-in-google-analytics
Marked as DO NOT MERGE until we've checked that this dimension is giving us the expected results for pages which explicitly add the `meta` tag for navigation document types.
=> Track the navigation document type for all pages

app/assets/javascripts/surveys.js
This commit will revert: https://github.com/alphagov/static/pull/979/files
Reason: There is currently an error when sending email surveys. It might be related to these changes so I am reverting them and testing the error separately. This is done to unblock static and feedback from being deployed to production.
=> Reverts previous commit

app/assets/javascripts/analytics/static-analytics.js, app/views/govuk_component/analytics_meta_tags.raw.html.erb, spec/javascripts/analytics/static-analytics-spec.js, test/govuk_component/analytics_meta_tags_test.rb
This reverts commit c2a8ce7c726fc1a3505ac3ade1775b641184bb25.
Putting this back for product review after it was [reverted for a deployment](https://github.com/alphagov/static/pull/982).
=> Revert "Revert “Revert “Revert “Track themes”””"

app/views/govuk_component/analytics_meta_tags.raw.html.erb, test/govuk_component/analytics_meta_tags_test.rb
This change will report the taxon slugs rather than their titles, in line with the Trello card.
https://trello.com/c/kLfd977R/555-track-the-theme-in-google-analytics
=> Track taxon slugs rather than titles

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
Trello: https://trello.com/c/wCb2VvDw/132-custom-dimension-content-unique-id
> We need to have a canonical key for joining GA data to other sources of data about content. The URI is the only thing currently in GA and is not authoritative.
This PR ensures that the `content-id` meta tag is sent as dimension 4.
=> Add a custom GA dimension for content-id meta tag

app/assets/javascripts/analytics/static-analytics.js, app/views/govuk_component/analytics_meta_tags.raw.html.erb, spec/javascripts/analytics/static-analytics-spec.js, test/govuk_component/analytics_meta_tags_test.rb
Track taxons of content items. We'll be using 4 custom dimensions to track:
- The slug (without the theme) of the first taxon (eg if the taxon has slug `/education/a-taxon`, we track `a-taxon`), when taxons are sorted alphabetically
- The content ID of the first taxon, when taxons are sorted alphabetically
- The list of all slugs without their themes for all taxons tagged to the content
- The list of all content IDs for all taxons tagged to the content
If a page is a taxon, we track the taxon itself.
https://trello.com/c/6lLHmlEe/495-track-the-taxon-of-content-items-in-google-analytics
=> Track taxons

Gemfile, Gemfile.lock, app/assets/stylesheets/header-footer-only.scss, app/assets/stylesheets/helpers/_emergency-banner-notifications.scss, app/helpers/notification_helper.rb, app/views/notifications/_emergency_banner.erb, app/views/root/_base.html.erb, lib/emergency_banner.rb, test/functional/root_controller_test.rb, test/integration/notifications_test.rb, test/unit/emergency_banner_test.rb
Trello card: https://trello.com/c/EPTEOgHJ
Depends on
The current emergency banner doesn't allow static to be deployed while the banner is up.
This PR uses values in Redis to determine whether:
* The banner should be displayed
* What the contents of the banner should be, i.e. the heading and banner colour etc.
The functionality for the old emergency banner has not been removed yet to allow comparison testing of the old and new emergency banners.
=> Use Redis to show emergency banner in static

Jenkinsfile
Use the common jenkinslib build task to build the project. This improves performance by fixing job throttling, and means that static will share any future build improvements.
Override the test task so that the Ruby and JS tests are run separately. Running them in same default rake task causes confusing test errors: http://stackoverflow.com/questions/26235828/actionviewtemplateerror-wrong-number-of-arguments-3-for-1-2
=> Use shared `buildProject` task in CI

app/assets/stylesheets/govuk-component/_govspeak-print.scss
When printing `legislative-lists` the browser generated list numbering is doubling up with numbering / lettering put in the markup by publishers. This results in confusing list numbering in the print version.
Trello: https://trello.com/c/UibrijCb/6-2-immigration-manual-print-page-numbering
Example: https://www.gov.uk/guidance/immigration-rules/immigration-rules-appendix-fm-se-family-members-specified-evidence
This PR adds a `legislative-list` specific print style to hide the browser generated list numbers so that the publishers original numbering alone is visible in the print version.
=> Legislative list print styles

app/assets/stylesheets/helpers/_emergency-banner-notifications.scss, app/views/notifications/_homepage_emergency_banner.erb, app/views/root/_base.html.erb, app/views/root/homepage.html.erb, test/integration/notifications_test.rb
We are consolidating the emergency banner templates in Static and Frontend - see the [Trello card](https://trello.com/c/3eq0AeHA/30-consolidate-emergency-banner-templates-in-static-and-frontend)
This PR does the work of bringing the homepage emergency banner display into Static. This will result in two different partials in Static that are responsible for displaying the emergency banner. One for the home page and one for all other pages. Although not ideal, at the moment, this is a good first step because the markup and styling is different between the two classes of page.
Work included in this PR:
* Create new partial that will render the emergency banner for the homepage.
* Include logic in `_base` to selectively display the correct emergency banner partial.
* Pass additional …
=> Add emergency banner for homepage

app/assets/javascripts/analytics/static-analytics.js, app/views/govuk_component/related_items.raw.html.erb, app/views/govuk_component/taxonomy_sidebar.raw.html.erb, spec/javascripts/analytics/static-analytics-spec.js
At the moment we only record related link and accordion link information
on the click event (ie only if someone uses the link). We have no
information about if links are not used, since they don’t get clicked
and then never send a tracking event.
This change will add tracking for custom dimensions on the page view,
which will report information on:
- the total number of “sections” on the page
- the total number of “section links” on the page
These values will have different meanings depending on the type of page
we are on.
On a content item, the number of sections will refer to the number of
sections of related links in the sidebar. The total number of links
is the total number of related links in the sidebar (not including
the heading in a taxon sidebar, but including the “More” link). …
=> Track total number of sections and section links

app/assets/stylesheets/govuk-component/_taxonomy-sidebar.scss, app/views/govuk_component/taxonomy_sidebar.raw.html.erb
This Pull Request fixes an earlier attempt to simply resize bullet points. The previous attempt to do this used pseudoelements, which:
- is not a very typical pattern
- does not play nice with screenreaders, which try to read out the bullets
Note that this PR replaces https://github.com/alphagov/static/pull/945
https://trello.com/c/37jp8eJQ/514-taxonomy-sidebar-related-links-bullet-points-can-we-make-these-better-for-screenreaders
=> Resize bullets

app/assets/stylesheets/govuk-component/govspeak/_contact.scss, app/views/govuk_component/docs/govspeak.yml
Addresses are used in the $A markdown pattern:
https://github.com/alphagov/govspeak/blob/a04ef6b54f090ec03911d0daaed4c74741578fea/lib/govspeak.rb#L249-L251
This pattern is used in specialist documents that include contacts:
https://www.gov.uk/drug-device-alerts/transwarmer-infant-transport-mattress-novaplus-transwarmer-infant-heat-therapy-mattress-with-warmgel-infant-heel-warmer-risk-of-serious-burn
| Before | After |
|--|--|
|![screen shot 2017-04-19 at 14 40 08](https://cloud.githubusercontent.com/assets/319055/25184158/883bad74-2511-11e7-870a-c8af183ceace.png)|![screen shot 2017-04-19 at 14 45 42](https://cloud.githubusercontent.com/assets/319055/25184157/883b4596-2511-11e7-9847-a2b585d9e7f0.png)|
=> Style address blocks with margins

Dockerfile
This is used to run https://github.com/alphagov/publishing-e2e-tests
Currently we're seeing a bunch of errors from Redis not connecting.
=> Add REDIS_URL to Dockerfile

app/assets/javascripts/analytics/static-analytics.js, app/views/govuk_component/analytics_meta_tags.raw.html.erb, spec/javascripts/analytics/static-analytics-spec.js, test/govuk_component/analytics_meta_tags_test.rb
Part of https://trello.com/c/0xPPAdDd/286-track-schema-name-in-google-analytics
Paired with @michaelihejirika 
Also tested locally with government-frontend and can confirm calls to GA with dimension17 are set correctly.
=> Add schema name analytics meta tag

app/assets/stylesheets/govuk-component/govspeak/_typography.scss
Publishers unofficially add button html to mainstream content
This has not been componentised yet. Button styles need to be
provided by the app.
BEFORE
AFTER
=> Remove underline from buttons

app/assets/stylesheets/govuk-component/_govspeak.scss, app/views/govuk_component/docs/govspeak.yml
this was an oversight from a previous commit
=> Add missing step css from govspeak import

app/assets/javascripts/analytics/init.js.erb
The configuration variable is misnamed and will be changed once this is
proven to work. The endpoint is now served entirely by Fastly, and
returns an empty 200 response. We only call the endpoint using
`$.get()` and ignore the response so its `Content-Type` doesn’t matter.
=> Enable GOV.UK analytics tracker configuration

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
We have a bug that means that some page views do not correctly have
the number of links and sections set. This could be because these values
are tracked through counting DOM elements, but the code is run before
`document.ready`.
This change attempts to fix the bug by performing the count after the
DOM has fully loaded, and only then tracking the page view.
https://trello.com/c/irHlKtYL/50-review-number-of-links-sections-tracking
=> Track page views on DOM ready

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
This reverts commit 8cc61f56d8c1762f1589348153be10d0719f7ff1.
We previously pushed a speculative fix to track down an unreproducible tracking bug. The fix was not effective, so we're backing it out.
https://trello.com/c/irHlKtYL/50-review-number-of-links-sections-tracking
=> Revert "Track page views on DOM ready"

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
We’re seeing some weird behaviour on our Google Analytics tracking:
- Some pages appear to have a very high (10-100) repeat visit rate
within a single (half hour) session
- Dimensions that rely on the DOM having loaded also are reporting 0
count sometimes.
Noteably, when the count *is* reported correctly, the repeat visit
rate also appears to drop back to “normal levels” (~2).
This could be because of setting custom dimensions at the “session”
level, rather than passing them directly into the page view tracking,
but this is hard to test because we cannot reproduce the bug on our
machines.
In order to debug, we’re attempting to pass custom dimensions
directly to the page view tracking.
https://trello.com/c/irHlKtYL/50-review-number-of-links-sections-tracking
=> Pass custom dimensions directly to page tracking

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
This reverts commit 17265dde863b65f801425dc19d37f1cb2fd19d64.
The bug was not fixed by this change, so roll it back.
https://trello.com/c/irHlKtYL/50-review-number-of-links-sections-tracking
=> Revert "Pass custom dimensions directly to page tracking"

app/assets/javascripts/govuk-component/govspeak-enhance-youtube-video-links.js, app/views/govuk_component/docs/govspeak.yml, app/views/govuk_component/govspeak.raw.html.erb, app/views/govuk_component/govspeak_html_publication.raw.html.erb, spec/javascripts/govuk-component/govspeak-enhance-youtube-video-links-spec.js, test/govuk_component/govspeak_test.rb
this disables youtube expansion on a flag, this is needed for mainstream content
to work correctly in government-frontend as it is being migrated over by
template consolidation
=> Add flag to disable youtube expansion

app/assets/javascripts/surveys.js, doc/surveys.md, spec/javascripts/surveys-spec.js
[Trello card](https://trello.com/c/fg1pm35A/157-re-add-custom-variable-to-survey)
This will add back the custom variable that was being appended to the end of survey monkey urls.
All survey monkey urls have been replaced with smart survey urls, so this should have been corrected as well.
=> Replaces survey monkey with smart survey

app/assets/stylesheets/govuk-component/_related-items.scss, app/views/govuk_component/related_items.raw.html.erb
This change is required so we can display the new Register to Vote
section in the related links sidebar. Because there needs to be a
description in there, we need to make sure we add it to the section,
when available.
Trello: https://trello.com/c/QbnidEBA/97-add-promotion-for-register-to-vote-to-transaction-done-pages
Waiting on product/design feedback before this should be merged. This needs data from `govuk_navigation_helpers` in order to display the description. The PR is here: https://github.com/alphagov/govuk_navigation_helpers/pull/76
It currently looks like this:
=> Allow for a description in related link sections

app/views/govuk_component/document_footer.raw.html.erb, app/views/govuk_component/metadata.raw.html.erb
https://trello.com/c/AmrwFMJU/22-implement-ga-event-tracking-on-content-history-see-all-updates-and-full-page-history-links
We'd like to understand how users interact with the page history
and updates links on a page, so add the data attributes which
enable tracking and provide the appropriate tracking options
cc @fofr
=> Add data attributes to track history link events

app/views/govuk_component/analytics_meta_tags.raw.html.erb, app/views/govuk_component/analytics_meta_tags_navigation.raw.html.erb, app/views/govuk_component/docs/analytics_meta_tags_navigation.yml, test/govuk_component/analytics_meta_tags_navigation_test.rb, test/govuk_component/analytics_meta_tags_test.rb
In order to remove the navigation analytics meta tags, we need to do
two stages:
1. Remove all references to the meta tags (ie in taxonomy sidebar
and related items)
2. Remove the component itself
This is because Static/Slimmer will have a cached set of sidebar
components that will continue trying to use the old meta tags. Hence
we need to leave the meta tags in place, and then remove them after
the cache has cleared.
=> Add Navigation Tracking Metatags shim

app/assets/stylesheets/govuk-component/_govspeak-print.scss
* Match print styles for other callouts
* Matches frontend’s print styles for information notices
=> Add border to info-notice when printing

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
We currently have some generic methods for calling arbitrary methods
within the Analytics object on the next page view. This is actually only
ever used to set a custom dimension.
In order to close down our API, this change removes this generic,
reflective and overly open method, and instead exposes a method to set
an options object for the next tracked pageview, which is really what
we’re trying to achieve.
This will enable us to also remove the externally-exposed, specialised
dimension-setting methods.
A number of `TODO`s have been raised in this PR - these will be resolved
after we have merged https://github.com/alphagov/frontend/pull/1221
https://trello.com/c/5dIbwHvU/120-tidy-up-tracking-changes
=> Enable setting options for the next tracked pageview

app/assets/javascripts/analytics/static-analytics.js
In order to compare with the new taxonomy navigation pages, we are
adding similar tracking for the browse pages, where a “section” is a
demarcated list of links.
https://trello.com/c/eiosXmG5/102-add-navigation-link-tracking-to-browse
=> Track navigation sections and links on browse pages

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
When we removed the session-level custom dimension setting, we did not
add these explicitly to the event or share tracking.
This change passes these options on to the `trackEvent` and `trackShare`
methods so that they are tracked as well as on `trackPageview`.
=> Pass custom dimension to event and share tracking

app/assets/javascripts/modules/toggle.js, app/assets/javascripts/start-modules.js, spec/javascripts/modules/toggle.spec.js
* Changes in metadata expand/collapse PR had included linting, making reading the changes difficult. This commit contains all of the linting and none of the changes, so should make that PR more readable once merged
=> Linting to unpollute metadata pull request

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
As part of a refactor to reduce the number of public functions we expose on the `StaticAnalytics` object, we have removed now-unused public methods:
- `callOnNextPage`
- `callMethodRequestedByPreviousPage`
- `setSectionDimension`
- `setResultCountDimension`
- `setSearchPositionDimension`
Notably, we have _not_ removed `setDimension`, which is still in use by a range of applications across GDS.
### Trello
https://trello.com/c/5dIbwHvU/120-tidy-up-tracking-changes
=> Remove unused tracking code

app/views/govuk_component/metadata_sentence.raw.html.erb, test/govuk_component/metadata_test.rb
* Specifically, '+ 139 more' was failing to show the number correctly
* Tests updated to check this in both English and a foreign language
=> Fixed bug with metadata expand in foreign language

app/assets/stylesheets/guides-print.scss, app/views/root/print.html.erb, config/initializers/assets.rb
The `print` template is used by travel advice publisher.
https://govuk.zendesk.com/agent/tickets/2159900
https://errbit.publishing.service.gov.uk/apps/53c7ae830da1154f2b000469/problems/5922b4476578632ab5482a00
Reverts alphagov/static#1015.
=> Revert "Remove un-used print template"

app/assets/javascripts/core.js, app/assets/javascripts/header-footer-only.js, app/assets/javascripts/surveys.js, app/views/root/_javascript.html.erb, spec/javascripts/surveys-spec.js
For: https://trello.com/c/ZEJRuWiU/151-reduce-need-to-change-static-js-when-deploying-surveys-part-2
The contents of surveys.js can change frequently as we introduce new
surveys and retire old ones.  Every time we deploy these changes the
application.js bundle gets a new digest hash and so frequent visitors
have to re-download the whole JS bundle just to get these updates to
surveys.  To avoid this we separate the surveys.js so it is required
separately and changes to it will not change the digest of the main
application.js.
The assumption here is that applications using the JS provided by
static only do so by using the layouts via slimmer and not by requesting
the application.js or header-footer-only.js files directly.  If that
is the case they will also need to be updated to also …
=> Extract surveys.js as a separate JS bundle

app/assets/stylesheets/govuk-component/_previous-and-next-navigation.scss, app/views/govuk_component/docs/previous_and_next_navigation.yml, app/views/govuk_component/previous_and_next_navigation.raw.html.erb
We're updating the previous and next component, this iteration makes it more consistent with the new [back-to-top update](https://github.com/alphagov/government-frontend/pull/367).
This also aligns the component against the content.
I've tested this in Safari, Firefox, Edge, IE8-11, Galaxy S7 Chrome for Android, Safari 7 and 9
IE8 (When inline SVG is not supported)
---
---
Manuals
cc @miaallers
=> Previous and Next component design iteration

app/assets/javascripts/analytics/static-analytics.js, app/views/govuk_component/analytics_meta_tags.raw.html.erb, spec/javascripts/analytics/static-analytics-spec.js, test/govuk_component/analytics_meta_tags_test.rb
This will be set in the various frontends.
[Trello Card](https://trello.com/c/uHiHx5RQ/56-custom-dimension-to-identify-session-where-content-history-is-available)
=> Add an analytics dimension for 'govuk:content-has-history'

app/assets/stylesheets/helpers/_govuk-emergency-banner.scss
Trello card: https://trello.com/c/WoTcRfeI
Related to PR: https://github.com/alphagov/static/pull/1049
The black, red and green campaign classes are no longer being used to define the type of emergency banner. They have been replaced with notable-death, national-emergency and local-emergency.
This PR removes the old CSS styles.
=> Remove old emergency banner "colour" styles

app/views/govuk_component/taxonomy_sidebar.raw.html.erb, test/govuk_component/taxonomy_sidebar_test.rb
We previously hid any related links for any sections after the second
section in the taxonomy sidebar.
This logic is actually already handled in `govuk_navigation_helpers`,
which takes responsibility for what to show in the taxonomy sidebar,
so we can remove this logic.
https://trello.com/c/J8ofEnrt/167-display-curated-related-links-in-the-sidebar
=> No longer check how many sections are displayed on the taxonomy sidebar

app/assets/stylesheets/helpers/_header.scss
* Safari rendered this with a 1px gap between the input and the button, all other non-IE browsers happy
* Fixes  #848 
**Safari before**
**Safari after**
**Chrome before**
**Chrome after**
Worth noting that the negative outline offset isn't supported in IE (even newer versions) so this is generally broken/different in IE anyway. An alternative could be to change the border colour rather than use an outline but I assume there's a good reason for this so didn't want to go off the reservation.
=> Adjusting header search box focus style

app/assets/stylesheets/helpers/_report-a-problem.scss
When on mobile, in some layouts the report a problem link and form get indented twice – once because of a 15px margin applied to #wrapper, and once again on report a problem itself.
* If the link is nested within wrapper, don’t indent again
* Keeps indentation if no wrapper is present
The homepage is a special case, it uses #wrapper but removes the margin
* Include site-width-container again with higher specificity for the homepage. This prevents the `0` margin resets from taking effect.
Previous attempt to fix: https://github.com/alphagov/static/pull/660 reverted in https://github.com/alphagov/static/pull/662
Fixes #998
=> Indent report a problem toggle and form correctly

app/assets/javascripts/modules/sticky-element-container.js, app/assets/stylesheets/govuk-component/_govspeak-html-publication-print.scss, app/assets/stylesheets/govuk-component/_govspeak-html-publication.scss, app/assets/stylesheets/modules/_sticky-element-container.scss, app/views/govuk_component/govspeak_html_publication.raw.html.erb, spec/javascripts/modules/sticky-element-container.spec.js
* At foot of page was possible to get 'Contents' fixed position link to briefly overlap content below it
* Problem was due to height of parent element including height of Contents link, then changing after it was set to position fixed
* Fixed by defaulting Contents link to position absolute so it never adds any height to the parent
Relates to https://github.com/alphagov/government-frontend/pull/367
=> Fix for sticky contents link overlap issue

app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
We no longer have a particular range of custom dimensions that can be
used for A/B tests. This was an old limitation that no longer exists and
is preventing new A/B tests with values outside that range to not report
correctly to Google Analytics.
Trello: https://trello.com/c/S5jp2jih/179-setup-technical-implementation-for-a-b-testing-the-blue-box
=> Remove conditions around dimension values

app/assets/javascripts/surveys.js, app/assets/stylesheets/helpers/_header.scss, doc/surveys.md, spec/javascripts/surveys-spec.js
This has been tested in VoiceOver for OSX, and will be talked through with the Accessibility team next Monday.
* Allows users of assistive technology to use the survey email form by ensuring context is kept and focus is moved around when interacting
* Restyles survey based on @markhurrell 's designs
* Lints JavaScript with Standard
* Simplifies CSS to be closer to the GOV.UK Publishing Component structure
* Changes 'no thanks' to close with additional labelling to provide better context
* Persists the section title between views to keep context of what the form is for
URL
Email
Realise this a big diff so I'm willing to try and reduce the amount of changes if it's too hard to review as is.
Best reviewed commit by commit, to reduce whitespace updates you can use the 'w' flag: …
=> Make email survey banner accessible

app/assets/javascripts/surveys.js, doc/surveys.md
For: https://trello.com/c/m9pylftF/172-govuk-survey-configure-new-default-survey-using-email-type
This replaces the existing default survey for the site (1 in 50, url style) with a new one (1 in 10, email).
Note: needs to be deployed after the corresponding PR on feedback (see: https://github.com/alphagov/feedback/pull/205) which configures the backend to send the correct survey via email.
=> Configure new default survey to use email template

app/assets/stylesheets/helpers/_header.scss
In the newer templates e.g. core_layout this is not a problem but with wrapper
we're seeing a slight misalignment, this patch overrides wrapper.
Before
After
Offending code is here: https://github.com/alphagov/static/blob/9e8795b262c948a65b798029864cbe04f193262a/app/assets/stylesheets/helpers/_buttons.scss#L103
Spotted by @fofr
=> Overrides global styling from the wrapper template causing misalignment

app/assets/javascripts/analytics.js, app/assets/javascripts/analytics/custom-dimensions.js, app/assets/javascripts/analytics/ecommerce.js, app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/ecommerce.spec.js, spec/javascripts/analytics/static-analytics-spec.js
We want to start using the Ecommerce tooling to track search results that are not clicked on a page. 
In order to minimise the number of data requests that we send to GA we need to setup the ecommerce data prior to performing the pageview event.
https://trello.com/c/WlBZo8Sl/118-move-ecommerce-ga-to-use-govukfrontendtoolkit
=> Add ecommerce search results plugin

app/assets/javascripts/surveys.js, spec/javascripts/surveys-spec.js
For: https://trello.com/c/X88IDU6Q/117-permit-concurrent-short-surveys-for-the-same-page
The previous algorithm was to choose the default survey and then ask every
other survey defined in `smallSurveys` in turn if it was active. If the
survey says it is then we record it as the active survey and move on to
the next survey to ask if it is active. Once we have a survey then we
check if the survey has already been completed, and roll the dice to check
against the frequency.  Only then do we show it.
There are a couple of problems with this algorithm.  First; if we have two
or more active surveys that could run on a given page we always pick the
one defined last in smallSurveys.  This means that on that page we'll
never show the ones defined earlier.  Specifically this means that we'll
never …
=> Better algorithm for picking surveys

doc/architecture-decisions/0001-record-architecture-decisions.md, doc/architecture-decisions/0002-add-enhanced-ecommerce.md
Add some documentation to explain how we've implemented Enhanced E-commerce. 
Trello: https://trello.com/c/jIJOJwXB/142-documentation-for-enhanced-e-commerce
Rendered: https://github.com/alphagov/static/blob/f82a2e82c93906eb9d970f29de793d196584242c/doc/architecture-decisions/0002-add-enhanced-ecommerce.md
I've put this into [ADR](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions) format so we can keep this close to the code. I'm open to suggestions if people would rather move it somewhere else, like the developer docs.
=> Document Enhanced E-commerce plugin

app/assets/javascripts/surveys.js, doc/surveys.md, spec/javascripts/surveys-spec.js
For: https://trello.com/c/WaguHidO/184-adding-a-display-limit-to-the-govuk-survey-banner
We want to increase the frequency that some surveys appear, but we don't want to annoy frequent visitors to GOV.UK who show no interest in the survey.  To this end we:
1. introduce a surveySeen cookie for each survey that tracks how many times it has been presented to the user
2. don't show the survey to a user if it has been shown already to that user twice
3. allow a survey to configure the limit for how many times it considers too many (default is 2)
4. allow a survey to configure the number of days to persist the cookie that counts how many times it has been seen (default is to use a session cookie)
We also reduce the number of days for the "I've taken this survey don't show it again" cookie from …
=> Add limiting to how many times a user can be shown a survey

app/assets/javascripts/surveys.js
For: https://trello.com/c/WrsJq0E1/185-change-govuk-survey-banner-frequency-to-1-in-6-pageviews
Now that we have functionality to stop showing a survey over and over to
a user who has not interacted with it (see #1075) we can be bolder about how often
we show the default survey.  This should mean we get more results and
better data about what people think of the platform.
=> Make the default survey appear 1 in 6 times

app/assets/stylesheets/govuk-component/_metadata.scss
* Increase from 14px to 16px
* Rewritten slightly to use mobile first
* Width of dt and dd set at 30% and 70%, max width applied to prevent large gap between the two when in a wide space
* Fixed bug where elements collapsed to single column then back to two column before ending up as single column as screen width reduced
**Before, desktop:**
**After, desktop:**
**Before, mobile:**
**After, mobile:**
https://trello.com/c/2pik3I0j/109-1-increase-font-size-in-metadata-component-in-static
=> Metadata font size increase

app/assets/stylesheets/helpers/_print-base.scss
* Problem in print view when ordered lists have more than 9 items in them, only enough space on the left to display the last digit, so the numbering appears to reach 9 and then reset to 0
* Padding left increased to counter this problem, should now be good up to 999 items
* Issue documented here https://trello.com/c/CuYEun0D/110-content-list-print-view-content-list-numbering-10-issues
**Old**
**New**
=> Fix print view of numbered lists

app/assets/stylesheets/govuk-component/_organisation-logo.scss
Organisation logos were blurry on low-dpi screens. Adjusted background-size of images by 1px to improve blurriness.
**Fixes #916**
**Before (low-dpi screen):**
**After (low-dpi screen):**
**Before (hi-dpi screen)**
**After (hi-dpi screen):**
Issue on Trello here: https://trello.com/c/ChvtIxBx/126-organisation-logos-are-blurry
=> Removing blurriness from organisation logos

app/assets/stylesheets/helpers/_text.scss
Fixes #1061 . Previously, the warning sign on transaction pages was misaligned on mobile due to the default margin being overridden by a separate style. It looks like this separate style was being wrongly applied to multiple elements when it should have just been applied to the first paragraph of any transaction page, to reduce the distance between the first heading and p.
This fix makes the CSS selector more specific to make sure this selector only applies as described above, and no longer effects warning signs.
**Icon looks partially hidden. Looking more closely, we can see a margin-top: 0 is causing this.**
**The icon is now not hidden as the margin-top: 0 is no longer being applied.**
**We can also see that the margin-top: 0 is still being correctly applied to the first line of the …
=> Fixing misaligned warning sign on mobile

app/assets/javascripts/analytics/custom-dimensions.js, spec/javascripts/analytics/static-analytics-spec.js
We are adding tracking events to old navigation pages in order to track
how people use them. We have added tracking events when users click on
topic links, but we also need information on how many sections there are
on those pages, so that the custom dimension is reported accurately to
Google Analytics.
This commit makes sure we set the custom dimension 26 with the correct
number of topic sections.
This is related with the GitHub PR [1] and the Trello ticker [2].
- [1] https://github.com/alphagov/collections/pull/361
- [2] https://trello.com/c/5YQVnGVr/32-add-total-links-total-sections-counting-to-whitehall-navigation
=> Track total number of topic sections

app/assets/javascripts/analytics/custom-dimensions.js, spec/javascripts/analytics/static-analytics-spec.js
We are adding tracking events to old navigation pages in order to track
how people use them. We have added tracking events when users click on
document collection links, but we also need information on how many
sections there are on those pages, so that the custom dimension is
reported accurately to Google Analytics.
This commit makes sure we set the custom dimension 26 with the correct
number of document collection sections.
This is related with the GitHub PR [1] and the Trello ticker [2].
[1] - https://github.com/alphagov/government-frontend/pull/399
[2] - https://trello.com/c/5YQVnGVr/32-add-total-links-total-sections-counting-to-whitehall-navigation
=> Track total number of document collection sections

Gemfile, Gemfile.lock
This version has a fix for overlapping volume controls in the media player (see PR https://github.com/alphagov/govuk_frontend_toolkit/pull/429).
Upgrade to 7.x.x also includes removal of multivariate test javascript (see PR https://github.com/alphagov/govuk_frontend_toolkit/pull/420)
=> Upgrade frontend toolkit to 7.0.1

app/assets/javascripts/analytics/custom-dimensions.js, spec/javascripts/analytics/static-analytics-spec.js
This commit correctly sets the dimension27 with the number of links in
any topic page. This will then be attached to page view events and sent
to Google Analytics so we can run reports.
=> Track number of links in topic pages

app/assets/javascripts/analytics/custom-dimensions.js, spec/javascripts/analytics/static-analytics-spec.js
This commit correctly sets the dimension26 and dimension27 with the
number of sections and links in any policty area page. This will then
be attached to page view events and sent to Google Analytics so we
can run reports.
=> Track sections and links on policy area pages

app/assets/javascripts/analytics/custom-dimensions.js, spec/javascripts/analytics/static-analytics-spec.js
This commit correctly sets the dimension 27 value with the number of
links present in a Whitehall finder page. Those finders show
announcements, statistics, consultations and publications.
=> Track number of links on Whitehall finder pages

lib/tasks/publishing_api.rake, public/BingSiteAuth.xml
Add XML file to public pages and special routes.
The file specifies a verification code generated by Tara Stockford for https://www.gov.uk. It will verify our ownership of the site in Bing Webmaster Tools: https://www.bing.com/webmaster/help/how-to-verify-ownership-of-your-site-afcfefc6
This will help us to improve user journeys from Bing to GOV.UK.
https://trello.com/c/gBIgYRaV/174-set-up-bing-webmaster-tools
=> Add Bing site verification page

app/assets/javascripts/surveys.js
We want them to have custom titles and links to better target the people
they want to take the surveys.
These surveys are all live now,  but we were waiting for #1078 to land before we made these changes as it makes them a lot easier.
For: https://trello.com/c/t8HJ6lFM/190-govuk-survey-user-research-panel-invite-hmrc, https://trello.com/c/t8HJ6lFM/190-govuk-survey-user-research-panel-invite-hmrc, & https://trello.com/c/nHar0yr3/191-govuk-survey-user-research-panel-invite-dfe,
=> Customise the publishing guidance, hmrc, and dfe surveys

app/assets/javascripts/surveys.js
The custom call to action already ends with a period so we don't need
to add one to the postscript.  Even if we wanted to have the period out
side the all to action text, there's a big gap between it and the
postscript text when they're actually rendered so we shouldn't
do it this way.
=> Remove leading period from custom survey postscripts

app/assets/javascripts/surveys.js
In [#1078](https://github.com/alphagov/static/pull/1078) we changed the
behaviour of the surveys system to make the `activeWhen` property a list
of arguments instead of a function.  However, we forgot to reconfigure
the existing small surveys to use this functionality.  This results in
all the surveys behing potential candidates for every page.
=> Reconfigure smallSurveys to use arguments not functions

app/assets/javascripts/analytics/custom-dimensions.js, spec/javascripts/analytics/static-analytics-spec.js
This commit makes sure we track how many links there are on a document
collection. It also makes sure we track the number of sections
accurately, by first checking if we are in a document collection page.
Since document collections are content items and therefore might have
related links, the order in which we check for these counts matter.
=> Track document collection links and sections

app/assets/javascripts/analytics/custom-dimensions.js, spec/javascripts/analytics/static-analytics-spec.js
This commit makes sure we don't count email subscription links on
subtopic pages. That means making the CSS selector more specific, and
the consequence of that is that we now need to treat topic pages
differently.
=> Fix subtopic page link count

app/assets/javascripts/analytics/custom-dimensions.js, spec/javascripts/analytics/static-analytics-spec.js
This commit correctly sets dimension 27 with the number of links present
in a finder page such as `/government/policies`.
Trello: https://trello.com/c/vRtpDbnk/56-investigate-getting-nav-beta-analytics-tracking-onto-finder-template
Example on integration:
=> Calculate how many links are on a finder

lib/tasks/publishing_api.rake
This commit changes the description of the `publish_special_routes` rake task to not reference `robots.txt`, which is no longer published by this rake task.
=> Change description of publish_special_routes rake task

app/assets/javascripts/surveys.js
A 1 in 20 url survey that runs on all pages published by transport related
departments and agencies. The survey has a default serve limit of '2' and will run for 30 days.
The survey runs on the pages where the primary organisation is any of the following:
`<D9>|<D1117>|<EA74>|<EA78>|<EA80>|<EA1114>|<EA570>|<PB459>|<PB460>|<PB461>|<PB462>|<PB463>|<PB1118>|<PB247>|<PB465>|<PC469>|<PC472>|<PC493>|<OT248>|<OT249>`
and on any pages which have `Driving and transport` as a breadcrumb (which indicates they
are part of the `Driving` section on gov.uk).
The survey will also show up on the `gov.uk/browse/driving` navigation pages.
See: https://trello.com/c/bxxpMD1m/203-transport-survey-banner
=> Add a new survey for Transport content

app/assets/javascripts/analytics.js, app/assets/javascripts/analytics/custom-dimensions.js, app/assets/javascripts/analytics/page-content.js, spec/javascripts/analytics/static-analytics-spec.js
This commit moves the logic of determining how many sections and links
are on a given page to a new module, which has more granular functions
to extract all the necessary bits from a page to make a decision.
This refactoring aims at making it clearer what the steps are. Ideally,
each rendering application would set these counts in a meta tag and this
code would only read from it, but it's a bit more complicated than that,
especially for JS-driven finders.
What do you think?
=> Refactor how we calculate section and link counts

app/assets/javascripts/analytics/page-content.js, spec/javascripts/analytics/static-analytics-spec.js
We should default to 1 section in all finders, so that it's comparable with navigations with only an A-Z section.
This is a request from Vin, performance analyst.
Trello: https://trello.com/c/vRtpDbnk/56-investigate-getting-nav-beta-analytics-tracking-onto-finder-template
**Note to the reviewer:** this was built on top of https://github.com/alphagov/static/pull/1103, please review that one first and I will rebase this branch to remove the cherry-picked commit.
=> [DO NOT MERGE] Count finder sections as one

app/assets/javascripts/analytics/custom-dimensions.js, app/views/govuk_component/analytics_meta_tags.raw.html.erb, spec/javascripts/analytics/ecommerce.spec.js, spec/javascripts/analytics/static-analytics-spec.js
For:
https://trello.com/c/zBBaVUGk/178-custom-dimension-publication-status
https://trello.com/c/cbycNx3y/201-custom-dimension-languages
Sends the publishing state (withdrawn/not withdrawn) of the document and the language it's written in to Google Analytics. It will do this on every pageview event for publications, if it finds the state and/or the current language.
The purpose is to gather more data about which documents are viewed the most when filtered by publishing state and language.
=> [DO NOT MERGE] Send state and language to GA

app/assets/javascripts/surveys.js
Change frequency of `publisher_guidance_survey` from `1 in 6 times` to `1 in 1 times`. This is a result of noticing that there aren't a lot of visitors to the pages where this survey is running.
For: https://trello.com/c/Ye7GkB92/204-change-frequency-of-publisher-guidance-survey-from-1-in-6-to-1-in-1
=> Change frequency of publisher guidance survey

app/views/notifications/_emergency_banner.html.erb, doc/emergency-banner.md, lib/emergency_banner/deploy.rb, lib/emergency_banner/display.rb, lib/tasks/emergency_banner.rake, test/integration/notifications_test.rb, test/tasks/emergency_banner_test.rb, test/unit/emergency_banner/deploy_test.rb, test/unit/emergency_banner/display_test.rb
Emergency banners have the option of displaying a hyperlink for more information. The hyperlink text is currently hard coded to "More information" in the view. This PR makes the anchor text user definable.
* Add a parameter to the EmergencyBanner::Deploy class which writes the emergency banner data to Redis.
* Expose the new parameter that we store in Redis above via EmergencyBanner::Display. Also include a little logic to set a default value of "More information" since it isn't a mandatory field.
* Using the new "property" in EmergencyBanner::Display, show the anchor text in the view
* Update the rake task that we call from Jenkins to deploy the banner to include the new variable.
This should be released in conjunction with:
[Trello](https://trello.com/c/ZPkk7hnk/58-add-new-field-for-link …
=> Add user defined link text to emergency banner

app/assets/stylesheets/govuk-component/_button.scss, app/assets/stylesheets/govuk-component/_component.scss, app/assets/stylesheets/govuk-component/_govspeak.scss, app/assets/stylesheets/govuk-component/govspeak/_button.scss, app/assets/stylesheets/govuk-component/govspeak/_typography.scss, app/views/govuk_component/button.raw.html.erb, app/views/govuk_component/docs/button.yml, app/views/govuk_component/docs/govspeak.yml, test/govuk_component/button_test.rb
Adds a button component to be used across applications
Note: We do not consume GOV.UK Elements directly due to the naming conventions being leaky, in time this component will be a wrapper for the [GOV.UK Frontend](https://github.com/alphagov/govuk-frontend) project's button component.
Global button styles seen at `app/assets/stylesheets/helpers/_buttons.scss`
should be considered deprecated with this component replacing any instances.
govuk-* namespace replaced with pub-c-* otherwise we will conflict with https://github.com/alphagov/govuk-frontend/blob/master/docs/components.md
government-frontend PR using this component: https://github.com/alphagov/government-frontend/pull/418
| Before   |
|---|
| Big |
|   ![big](https://user-images.githubusercontent.com/2445413/28710090-b1a285fe-737a-11 …
=> Add button component

app/assets/javascripts/webchat.js.erb, spec/javascripts/hmrc-webchat-spec.js
For: https://trello.com/c/nC2DtWRS/176-reduce-webchat-events-analytics
webchat.js polls the webchat iframe every second and when it detects that it is ready to be used it sends an "open" message.  Among other things this message causes an "offered" event to be send to GA.  This happens once a second while the webchat is available, which is flooding our GA hits.  This PR reduces the volume of hits by only sending the GA event when we detect a change in the status.  To this end we introduce an event for when we detect that the webchat system is closed (so we can track a state change from open to closed and backagain as advisors become available and unavailable.
This follows a pattern established in the new webchat system implemented in government-frontend (see: …
=> Send ga events for webchat less often

app/assets/javascripts/surveys.js
Following the styleguide (see:
https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#titles)
titles should not end with a fullstop.
Thanks to @fofr for pointing it out
=> Remove full stop from titles of surveys

app/assets/javascripts/analytics/custom-dimensions.js, spec/javascripts/analytics/ecommerce.spec.js
For: [Trello card](https://trello.com/c/KXyHx427/212-rename-current-to-not-withdrawn-when-sending-data-to-ga-on-publication-status)
This is aimed at clearing up some confusion in GA data where documents that are marked as current/withdrawn may actually be in a third state where they are not relevant anymore but have not yet been withdrawn.
For this purpose, we're renaming the word "current" to "not withdrawn" to keep the current binary classification and reduce confusion.
=> Rename "current" to "not withdrawn"

app/assets/javascripts/analytics/page-content.js, spec/javascripts/analytics/static-analytics-spec.js
It should return 1 for the number of sections on a leaf page to be
consistent with the tracking on the legacy navigation.
https://trello.com/c/4RaDaoiX/151-amend-dimension-26-navigation-sections-analytics-tracking-on-leaf-pages
=> Change PageContent.getNumberOfSections to handle leaf pages

app/assets/javascripts/analytics/page-content.js, spec/javascripts/analytics/static-analytics-spec.js
This needs to return either 1 or 2 as a value. 1 by default and 2 if
there is a leaf section at the bottom of the grid.
https://trello.com/c/DEhfAo80/149-amend-dimension26-navigation-sections-analytics-tracking-on-grid-pages
=> Fix section tracking for grid pages

app/assets/javascripts/surveys.js
For: https://trello.com/c/p5i0D2IU/214-extend-dfe-and-hmrc-surveys-for-another-month
The surveys are due to end in the following days and will be extended until the end of September 2017 at midnight.
Originally added here: 
HMRC survey: https://github.com/alphagov/static/commit/581cfa19d0b15bb7410414568d3460e11df0b2ef
Dfe survey: https://github.com/alphagov/static/commit/8fa83662e4f8ee3793c77c39e3cdf22142006bfc
=> Extends DfE and HMRC surveys until Sept 30, 2017

app/assets/stylesheets/govuk-component/_previous-and-next-navigation.scss, app/views/govuk_component/docs/previous_and_next_navigation.yml, app/views/govuk_component/previous_and_next_navigation.raw.html.erb, test/govuk_component/previous_and_next_navigation_test.rb
- to use CSS class naming convention for components
- adds accessibility criteria to documentation
- tests for navigation role
https://trello.com/c/3rWOvqBG/95-2-update-pagination-component-to-be-inline-with-component-principles
Should look exactly the same as the current one, but here's some screenshots for examples.
See also related but non-dependent PR: https://github.com/alphagov/finder-frontend/pull/301
=> Update pagination component

app/assets/javascripts/analytics/custom-dimensions.js, app/assets/javascripts/analytics/static-analytics.js, spec/javascripts/analytics/static-analytics-spec.js
For: https://trello.com/c/n22tcj9Q/206-custom-dimension-google-analytics-client-id-and-session-id
In order to track user journeys in GA, it's been requested that we send the client ID as a custom dimension. The docs for extracting the client id can be found here: https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id?hl=en#getting_the_client_id_from_the_cookie
Using the recommended way means we're expecting a tracker to be loaded, which may or may not have happened at that point. Because our method is asynchronous, it might be called before `trackPageView` and not have a tracker object to query for the client ID.
In order to avoid this, we've put the call for `trackPageView` inside the asynchronous method for setting the client ID. This will guarantee …
=> Send the client ID inside a custom dimension

app/assets/stylesheets/govuk-component/_title-print.scss, app/assets/stylesheets/govuk-component/_title.scss, app/views/govuk_component/docs/title.yml, app/views/govuk_component/title.raw.html.erb, test/govuk_component/title_test.rb
Updating static title component to meet government-frontend component conventions.
This includes:
* Using pub-c namespace for CSS classes
* Use of BEM
* Adding accessibility criteria to docs
=> Update title component to meet chosen conventions

app/views/govuk_component/docs/previous_and_next_navigation.yml, app/views/govuk_component/previous_and_next_navigation.raw.html.erb, test/govuk_component/previous_and_next_navigation_test.rb
- add a visually hidden element containing a colon so screenreaders pause between the navigation part of the link (ie. next/previous) and the label part, if present
- update accessibility criteria and test to include this
https://trello.com/c/0kYwSKe4/120-investigate-accessibility-of-next-previous-component
=> Improve accessibility of pagination component

app/assets/javascripts/surveys.js
For: https://trello.com/c/b4J4OpaM/218-emotional-survey-test-banner  This survey is to run 1 in 6 frequency, on all pages (hence the lack of any `activeWhen` arguments in the definition) and only last for one week (Thursday -> Monday).
=> Add new user satisfaction survey

app/assets/javascripts/surveys.js, doc/surveys.md, spec/javascripts/surveys-spec.js
For: https://trello.com/c/F5wcNrsV/219-clientid-pushed-into-survey-urls-as-custom-data
In order to track the user journey when a user completes a survey, we can use the GA client ID to identify a session for a user and check all the pages he has visited before arriving to our survey. This will provide more detailed data about a user's browsing habits and will help to separate the data out, since the info collected on surveys is anonymous.
Sends client ID alongside the currentPath param when completing survey. This will help in identifying the session in GA.
=> Send client ID with survey currentPath param

app/assets/javascripts/surveys.js
For: https://trello.com/c/b4J4OpaM/218-emotional-survey-test-banner
Due to a misunderstanding when interpreting the card we
set this survey to end a week later than it should do.  It should run
from Friday 1st to Tuesday 5th, not Tuesday 12th.
=> Fix end date of emotional survey

app/assets/javascripts/surveys.js, doc/surveys.md, spec/javascripts/surveys-spec.js
For: https://trello.com/c/xDdnial5/220-clientid-pushed-into-email-surveys-as-custom-data
In order to track the user journey when a user completes an EMAIL survey, we can use the client ID to identify a session for a user and record all the pages he has visited before arriving to our survey. This will provide a more detailed picture about our user's browsing habits and will help to separate the data out, since the info collected on surveys is anonymous.
Depends on this PR: https://github.com/alphagov/feedback/pull/211
=> Add gaClientId to email surveys

app/assets/javascripts/analytics/static-analytics.js, app/assets/javascripts/surveys.js
For: https://trello.com/c/AokZntDm/221-investigate-why-client-id-isnt-being-loaded-for-all-surveys
The assignment of the GA client ID happens by invoking a bound function in `static-analytics.js` (seen below), which is passed to `ga`:
```
// static-analytics.js
ga(function (tracker) {
this.gaClientId = tracker.get('clientId')
// Track initial pageview
this.trackPageview(null, null, trackingOptions);
//   ...
}.bind(this));
```
Normally this happens immediately, and would initialise the GA Client ID which could then be used in `surveys.js` to send the ID along in the survey URL. 
Empirically, we've discovered that this only happens 50% of the time, because `surveys.js` might load before `static-analytics.js`. This means that for 50% of our survey responses we can't track the user in GA …
=> Wait for GA Client ID to be loaded before surveys

app/assets/javascripts/analytics/custom-dimensions.js, spec/javascripts/analytics/ecommerce.spec.js, spec/javascripts/analytics/static-analytics-spec.js
In order to make accurate comparisons of legacy and beta navigation we
need to know which pages to compare.  
This change will pick up any values set in a `govuk:navigation-legacy` meta tag, and add them to dimension 30 with a default of 'none'.
The [backend implementation change in Collections](https://github.com/alphagov/collections/pull/379)
[Trello](https://trello.com/c/IPAyElBg/248-send-identifying-value-for-legacy-education-childcare-navigation-pages)
=> Send identifying value for legacy Education & Childcare navigation pages

Gemfile, Gemfile.lock
New version includes:
* dark_background context
* ability to add descriptions to component examples
* showing incomplete warnings in aXe
=> Update govuk_publishing_components to new version

app/assets/stylesheets/govuk-component/_title.scss, app/views/govuk_component/docs/search.yml, app/views/govuk_component/docs/title.yml, app/views/govuk_component/title.raw.html.erb
Passing inverse: true to title component means the title can work on a dark background.
**Note: needs to be merged before updating HTML publications in government-frontend, but only after update to govuk_publishing_components.**
=> Adding inverse flag to title component

doc/static-components.md
Update static component docs to reference old govuk- namespace and reference new recommended pub-c- namespace.
=> Update docs to reference deprecated namespaces

Gemfile
Due to a ruby version mixup, `Numeric#positive?` isn't a method available in our production stack. 
Temporary fix to get deployments moving again. I hope to be able to move the logic out of this Gemfile in a later PR.
=> Fix issue preventing deployment

Gemfile, config/application.rb
Move the decision point for the `require` out of the Gemfile and into application.rb
=> Remove 'require' logic from Gemfile

Gemfile, Gemfile.lock
Update to 1.5.0, adds links to documentation
=> Bump govuk_publishing_components gem

Dockerfile, Gemfile
We have had issues with static not running correctly based on the ruby version being different
on Heroku and production, this change ensures the version is the same
Thanks to @tijmenb for this 👍
=> Update Gemfile to reference ruby-version file

Gemfile.lock, test/integration/component_guide_test.rb
Test that all components render without error
* Require webmock minitest for `stub_request` in stub_shared_component_locales
* Add an ActiveSupport concern to avoid hitting Slimmer for component guide requests (this matches the way we avoid hitting Slimmer when using Jasmine)
* This doesn’t explicitly run Javascript, accessibility tests will not yet be running
Follow on from #1125 
Part of https://trello.com/c/Yq9FFia1/
=> Include integration tests for static component guide

app/assets/stylesheets/govuk-component/_title.scss, app/views/govuk_component/docs/title.yml, app/views/govuk_component/title.raw.html.erb
- remove bottom margin from component
- add margin helper class for original component bottom margin
- default component state will use that class unless an alternative is passed i.e. 0, which means there is no need to update any instance of the component as it will still be as it was before this change
https://trello.com/c/KEkNsxG3/142-3-implement-customisable-spacing-for-components
This issue is complicated by our need for responsive margins. The ideal would be a mechanism where we pass a number to the component to interpret as margin-bottom e.g. 0 = no margin, 1 = gutter-half, 2 = gutter, etc. but an [https://docs.google.com/spreadsheets/d/1mL-zAgi_Vfb7BO3KPF8b9xAPq_pIXIZHHSjvlB1Tulg/edit#gid=0](audit of the components) reveals there is no simple scale for doing this when responsive is …
=> Implement customisable spacing for title component

startup.sh
This is a fix to the startup file which is currently failing.
The output of "bundle show govuk_frontend_toolkit" currently
contains warnings about us not running the latest version of
bundler which means the script fails. This fix simply
truncates the output at the first line.
(Note this is not a merge into master.)
=> Fix output of finding installed location

app/assets/javascripts/govuk-component/option-select.js, app/assets/stylesheets/govuk-component/_option-select.scss, app/views/govuk_component/docs/option_select.yml, spec/javascripts/govuk-component/option-select-spec.js
- set aria-expanded to true by default when initialising rather than performing a check as it will always be open on load, unless it's set to be closed in which case the code will change it back to false anyway as it then closes it
- fix for height issue by calling setheight on initialisation, code is structured already so that it won't get called again unless it needs to be
- fixes #860
- includes some CSS optimisation/improvements (tested in various including IE8, 9, 10, 11, Firefox current, 48, Edge, Chrome current, 54, Opera 40, Safari 5.1, iphone 6s, ipad mini)
Before:
After:
https://govuk-static-pr-1146.herokuapp.com/component-guide/option_select
=> Fix aria expanded and height of option select

Gemfile, Gemfile.lock, test/integration/component_guide_test.rb
- modify component guide test to account for changes in 1.9.0
=> Bump publishing component gem to 1.9.0

Gemfile, Gemfile.lock
We bump `gds-api-adapters` to 48.0 as we need to send the `update_type` of
special routes with PUT content requests to the Publishing API, which is soon
to become a requirement.
For [Trello](https://trello.com/c/UaxgGUDI/1115-require-updatetype-in-put-content)
=> Bump gds-api-adapters to 48.0

app/assets/javascripts/surveys.js
For: https://trello.com/c/svj1oEoM/249-adjustment-to-education-top-tasks-survey
We're not getting a great response so we make it slightly likely to appear
and tweak the wording to try to pull people in more.
=> Change wording and frequency of education top tasks survey

app/assets/javascripts/surveys.js
For: https://trello.com/c/svj1oEoM/249-adjustment-to-education-top-tasks-survey
In #1155 we changed the frequency and title, but didn't spot that the survey had already ended so the changes would be very unlikely to increase the response rate.  In this commit we extend it to run for another week.
=> Extend education top tasks survey

app/assets/stylesheets/govuk-component/_title.scss, app/views/govuk_component/docs/title.yml, app/views/govuk_component/title.raw.html.erb, test/govuk_component/title_test.rb
* Allows titles in Collections app to switch to the title component
* It’s not clear how useful this feature is and if users are clicking on it, include data attributes to allow tracking and include caveat in the docs
* Use API that matches HTML
* Keep backwards compatibility with setting context to a string
https://govuk-static-pr-1160.herokuapp.com/component-guide/title
Used on:
https://www.gov.uk/topic/business-tax/vat
=> Allow context in titles to be a link

app/assets/javascripts/surveys.js
For: https://trello.com/c/24xJ1dah/263-whitehall-finders-formats-research-banners and https://trello.com/c/xcvqIxHr/224-hmrc-user-research-panel-banners
We add a new survey for whitehall finders and documents to run for one month, and extend two existing hmrc surveys to run for another month.
=> Whitehall finders user research survey and extend hmrc survey

app/assets/stylesheets/govuk-component/_button.scss
The button includes CSS to set the outline, this means when
it's mixed in to the govspeak component it's too specific and overrides the
global outline selectors.
Tested locally (http://government-frontend.dev.gov.uk/log-in-file-self-assessment-tax-return) and in the static component guide.
http://govuk-static-pr-1164.herokuapp.com/component-guide/govspeak/button/preview
http://govuk-static-pr-1164.herokuapp.com/component-guide/button/preview
=> Force button outlines to be shown on focus

app/assets/stylesheets/govuk-component/_component.scss, app/assets/stylesheets/govuk-component/_lead-paragraph.scss, app/views/govuk_component/docs/lead_paragraph.yml, app/views/govuk_component/lead_paragraph.raw.html.erb, test/govuk_component/lead_paragraph_test.rb
- Imports the lead paragraph component from government-frontend
so that it can be shared across applications
Goes with https://github.com/alphagov/government-frontend/pull/504
=> Add lead paragraph component

app/views/govuk_component/docs/breadcrumbs.yml
The new navigation on the Education A/B tests uses a slightly enhanced breadcrumb with highlighting for the current page and collapsing on mobile. This adds those examples to the component guide.
https://govuk-static-pr-1169.herokuapp.com/component-guide/breadcrumbs
=> Add new breadcrumb examples to component guide

config/locales/ar.yml
This commit adds some Arabic translations to the `metadata` and `document_footer` components, as provided by MoD.
Trello: https://trello.com/c/dY6RL5BP/197-display-from-and-published-in-arabic-on-arabic-pages
=> Add Arabic translations to metadata components

app/views/govuk_component/document_footer.raw.html.erb
This commit changes the hardcoded "From" string in the `document_footer` component to be translatable.
=> Allow document_footer "from" field to be translatable

app/views/govuk_component/document_footer.raw.html.erb, app/views/govuk_component/metadata.raw.html.erb
Make document_footer and metadata components more flexible for tracking link clicks.
By passing tracking attributes to any link the component will track their clicks.
Avoids instantiating the track-click module and adding an event listener for every link.
=> Allow any links in footer or metadata components to be tracked

app/assets/javascripts/surveys.js
For: https://trello.com/c/NDPcQSmk/283-govuk-survey-hmrc-manuals
This PR adds a new survey for HMRC manuals content, but also removes some retired survey definitions and fixes the end date on a deployed one (we had Jan 2017 instead of Jan 2018!).
=> Hmrc manuals survey oct 2017

app/assets/javascripts/surveys.js
For: https://trello.com/c/NDPcQSmk/283-govuk-survey-hmrc-manuals
This survey should work on all paths under hmrc-internal-manuals, but we
left a slash in our regexp matcher that means it would only match entries
with a double slash (e.g. /hrmc-internal-manuals//foo instead of
/hrmrc-internal-manuals/foo).
We probably need to think about an abstraction for defining these matches
to make it hard to make this kind of mistake in the future.
=> Remove stray slash in hrmc manuals survey

app/assets/javascripts/govuk-component/tasklist.js, app/assets/stylesheets/govuk-component/_task-list.scss, app/views/govuk_component/docs/task_list.yml, spec/javascripts/govuk-component/task-list-spec.js
- update JS to include code to determine which element in the task list accordion header was clicked (button, plus/minus, or white space) from service manual
- dimension26 records total number of expand/collapse sections in task list
- dimension27 records total number of component links in task list (links that are part of the component)
- dimension28 records number of component links in the section that was opened/closed (handled in click event)
Trello card: https://trello.com/c/EiXT7IAh/227-implement-tracking-on-the-beta-task-list
PR: https://govuk-static-pr-1179.herokuapp.com/component-guide/task_list (no visual changes but tracking can be viewed using the GA Chrome plugin)
=> Improve task list Google Analytics

app/assets/stylesheets/govuk-component/_search.scss
Chrome 62 [updates the default styles for buttons to add a default `border-radius` of 4px][1], which is affecting the buttons in the search box (noticed on the homepage).
This sets an explicit border radius of `0`, which corrects the search button to look like it does in Chrome 61.
[1]: https://www.chromestatus.com/features/5743649186906112
=> Fix search button radius in Chrome 62 (Mac)

app/views/govuk_component/button.raw.html.erb, app/views/govuk_component/docs/button.yml, test/govuk_component/button_test.rb
This is needed for transactions that applies rel="external"
See https://github.com/alphagov/frontend/blob/master/app/views/transaction/show.html.erb#L20
https://govuk-static-pr-1180.herokuapp.com/component-guide/button/start_now_button/preview
=> Add ability to pass rel attributes to buttons
